/**
  * @ cqiyi create in 2014/7/24 21:26:52 by Template
  * This class generated by Forever Web Rapid Framework Code Generator
  */
  
package hply.mapper;

import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;
import hply.domain.Arrears;



/**
  * 数据表： [t_arrears]
  * 
  */
@Repository
public interface ArrearsMapper {

	  public void insert(Arrears arrears);
	  
	  public void update(Arrears arrears);
	  
	  public void delete(String id);
	  
	  public Arrears get(String id);
      
	  public int getVersion(String id);
	  
	  public List<Arrears> getAll();
}

