/**
  * @ cqiyi create in 2014/7/18 16:09:21 by Template
  * This class generated by Forever Web Rapid Framework Code Generator
  */
  
package org.hhwy.fweb1.mapper;

import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;
import org.hhwy.fweb1.domain.Chop;



/**
  * 数据表： [t_chop]
  * 09_盖章管理
  */
@Repository
public interface ChopMapper {

	  public void insert(Chop chop);
	  
	  public void update(Chop chop);
	  
	  public void delete(String id);
	  
	  public Chop get(String id);
      
	  public int getVersion(String id);
	  
	  public List<Chop> getAll();
}

