/**
  * @ cqiyi create in 2014/7/17 20:31:35 by Template
  * This class generated by Forever Web Rapid Framework Code Generator
  */
  
package org.hhwy.rdc.fweb1.mapper;

import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;
import org.hhwy.rdc.fweb1.domain.ContractChange;



/**
  * 数据表： [t_contract_change]
  * 02_合同补充协议
  */
@Repository
public interface ContractChangeMapper {

	  public void insert(ContractChange contractChange);
	  
	  public void update(ContractChange contractChange);
	  
	  public void delete(String id);
	  
	  public ContractChange get(String id);
      
	  public int getVersion(String id);
	  
	  public List<ContractChange> getAll();
}

