/**
  * @ cqiyi create in 2014/7/24 21:26:52 by Template
  * This class generated by Forever Web Rapid Framework Code Generator
  */
  
package hply.mapper;

import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;
import hply.domain.Profile;



/**
  * 数据表： [t_profile]
  * 
  */
@Repository
public interface ProfileMapper {

	  public void insert(Profile profile);
	  
	  public void update(Profile profile);
	  
	  public void delete(String id);
	  
	  public Profile get(String id);
      
	  public int getVersion(String id);
	  
	  public List<Profile> getAll();
}

