/**
  * @ cqiyi create in 2014/8/5 18:13:27 by Template
  * This class generated by Forever Web Rapid Framework Code Generator
  */
  
package org.hhwy.fweb1.mapper;

import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;
import org.hhwy.fweb1.domain.SysAuthorization;
import org.hhwy.fweb1.mapper.partial.PartialSysAuthorizationMapper;



/**
  * 数据表： [t_sys_authorization]
  * 授权关系
  */
@Repository
public interface SysAuthorizationMapper extends PartialSysAuthorizationMapper {

}

