/**
  * @ cqiyi create in 2014/8/5 18:13:27 by Template
  * This class generated by Forever Web Rapid Framework Code Generator
  */
  
package org.hhwy.fweb1.mapper;

import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;
import org.hhwy.fweb1.domain.SysRole;
import org.hhwy.fweb1.mapper.partial.PartialSysRoleMapper;



/**
  * 数据表： [t_sys_role]
  * 系统角色表
  */
@Repository
public interface SysRoleMapper extends PartialSysRoleMapper {

}

