/**
  * @ cqiyi create in 2014-8-25 23:07:45 by Template
  * This class generated by Forever Web Rapid Framework Code Generator
  */
  
package hply.mapper.partial;

import hply.domain.InformationChange;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;



/**
  * 数据表： [t_information_change]
  * 10+A_信息登记补充修改表
  */
@Repository
public interface PartialInformationChangeMapper {

	  public void insert(InformationChange informationChange);
	  
	  public void update(InformationChange informationChange);
	  
	  public void delete(String id);
	  
	  public InformationChange get(String id);
      
	  public int getVersion(String id);
	  
	  public List<InformationChange> getAll();
      
	  public int getRowCount(@Param("queryText") String queryText);
	  
	  public List<InformationChange> getAllPaged(@Param("queryText") String queryText, @Param("pageIndex") int pageIndex, @Param("pageSize") int pageSize);
}

