/**
  * @ cqiyi create in 2014-8-10 20:38:00 by Template
  * This class generated by Forever Web Rapid Framework Code Generator
  */
  
package hply.mapper.partial;

import java.util.List;
import org.springframework.stereotype.Repository;
import hply.domain.CustomerBilling;



/**
  * 数据表： [t_customer_billing]
  * 04_客户开票情况
  */
@Repository
public interface PartialCustomerBillingMapper {

	  public void insert(CustomerBilling customerBilling);
	  
	  public void update(CustomerBilling customerBilling);
	  
	  public void delete(String id);
	  
	  public CustomerBilling get(String id);
      
	  public int getVersion(String id);
	  
	  public List<CustomerBilling> getAll();
}

