/**
  * @ cqiyi create in 2014-8-25 23:07:45 by Template
  * This class generated by Forever Web Rapid Framework Code Generator
  */
  
package hply.mapper.partial;

import hply.domain.FieldTypes;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;



/**
  * 数据表： [t_field_types]
  * 所有数据类型的测试样表
  */
@Repository
public interface PartialFieldTypesMapper {

	  public void insert(FieldTypes fieldTypes);
	  
	  public void update(FieldTypes fieldTypes);
	  
	  public void delete(String id);
	  
	  public FieldTypes get(String id);
      
	  public int getVersion(String id);
	  
	  public List<FieldTypes> getAll();
      
	  public int getRowCount();
	  
	  public List<FieldTypes> getAllPaged(@Param("pageIndex") int pageIndex, @Param("pageSize") int pageSize);
}

