/**
 * @ cqiyi create in 2014-8-25 23:07:45 by Template
 * This class generated by Forever Web Rapid Framework Code Generator
 */

package hply.mapper.partial;

import hply.domain.PaymentDifferentTaxAmount;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

/**
 * 数据表： [t_payment_different_tax_amount] 异地税金
 */
@Repository
public interface PartialPaymentDifferentTaxAmountMapper {

	public void insert(PaymentDifferentTaxAmount paymentDifferentTaxAmount);

	public void update(PaymentDifferentTaxAmount paymentDifferentTaxAmount);

	public void delete(String id);

	public void check(String id);

	public PaymentDifferentTaxAmount get(String id);

	public int getVersion(String id);

	public List<PaymentDifferentTaxAmount> getAll();

	public int getRowCount();

	public List<PaymentDifferentTaxAmount> getAllPaged(@Param("pageIndex") int pageIndex, @Param("pageSize") int pageSize);
}
