/**
 * @Template info: 2013/08/16, Chengqiyi.
 * ChengQiyi create in 2014-7-13 15:01:55
 * This class generated by CodeSmith Generator
 */

package hply.persistence;

import hply.domain.ContractSupplementalAgreement;

import java.util.List;

import org.springframework.stereotype.Repository;

@Repository(value = "contractSupplementalAgreementMapper")
public interface ContractSupplementalAgreementMapper {

	public void insert(
			ContractSupplementalAgreement contractSupplementalAgreement);

	public void update(
			ContractSupplementalAgreement contractSupplementalAgreement);

	public void delete(String id);

	public ContractSupplementalAgreement get(String id);

	public List<ContractSupplementalAgreement> getAll();
}
