/**
 * @Template info: 2013/08/16, Chengqiyi.
 * ChengQiyi create in 2014-7-13 15:01:55
 * This class generated by CodeSmith Generator
 */

package hply.persistence;

import hply.domain.CustomerBilling;

import java.util.List;

import org.springframework.stereotype.Repository;

@Repository(value = "customerBillingMapper")
public interface CustomerBillingMapper {

	public void insert(CustomerBilling customerBilling);

	public void update(CustomerBilling customerBilling);

	public void delete(String id);

	public CustomerBilling get(String id);

	public List<CustomerBilling> getAll();
}
