/**
 * @Template info: 2013/08/16, Chengqiyi.
 * ChengQiyi create in 2014-7-13 15:01:55
 * This class generated by CodeSmith Generator
 */

package hply.persistence;

import hply.domain.Profile;

import java.util.List;

import org.springframework.stereotype.Repository;

@Repository(value = "profileMapper")
public interface ProfileMapper {

	public void insert(Profile profile);

	public void update(Profile profile);

	public void delete(String id);

	public Profile get(String id);

	public List<Profile> getAll();
}
