/**
 * @Template info: 2013/08/16, Chengqiyi.
 * ChengQiyi create in 2014-7-13 15:01:55
 * This class generated by CodeSmith Generator
 */

package hply.persistence;

import hply.domain.Project;

import java.util.List;

import org.springframework.stereotype.Repository;

@Repository(value = "projectMapper")
public interface ProjectMapper {

	public void insert(Project project);

	public void update(Project project);

	public void delete(String id);

	public Project get(String id);

	public List<Project> getAll();
}
