/**
  * @Template info: 2013/08/16, Chengqiyi.
  * ChengQiyi create in 2014/7/7 20:58:17
  * This class generated by CodeSmith Generator
  */

package hply.persistence;

import hply.domain.SysAuthorization;

import java.util.List;

public interface SysAuthorizationMapper {

	  public void insert(SysAuthorization sysAuthorization);
	  
	  public void update(SysAuthorization sysAuthorization);
	  
	  public void delete(SysAuthorization sysAuthorization);
	  
	  public SysAuthorization get(String id);
	  
	  public List<SysAuthorization> getAll();
}


