/**
 * @Template info: 2013/08/16, Chengqiyi.
 * ChengQiyi create in 2014-7-13 15:01:55
 * This class generated by CodeSmith Generator
 */

package hply.persistence;

import hply.domain.SysOrganization;

import java.util.List;

import org.springframework.stereotype.Repository;

@Repository(value = "sysOrganizationMapper")
public interface SysOrganizationMapper {

	public void insert(SysOrganization sysOrganization);

	public void update(SysOrganization sysOrganization);

	public void delete(String id);

	public SysOrganization get(String id);

	public List<SysOrganization> getAll();
}
