/**
 * @Template info: 2013/08/16, Chengqiyi.
 * ChengQiyi create in 2014-7-13 15:01:55
 * This class generated by CodeSmith Generator
 */

package hply.persistence;

import hply.domain.SysParameter;

import java.util.List;

import org.springframework.stereotype.Repository;

@Repository(value = "sysParameterMapper")
public interface SysParameterMapper {

	public void insert(SysParameter sysParameter);

	public void update(SysParameter sysParameter);

	public void delete(String id);

	public SysParameter get(String id);

	public List<SysParameter> getAll();
}
