/**
  * @Template info: 2013/08/16, Chengqiyi.
  * ChengQiyi create in 2014/7/7 20:57:53
  * This class generated by CodeSmith Generator
  */

package hply.persistence;

import java.util.List;
import java.util.Map;

import hply.domain.SysParameter;

public interface SysParameterMapper {

	  public void insert(SysParameter sysParameter);
	  
	  public void update(SysParameter sysParameter);
	  
	  public void delete(SysParameter sysParameter);
	  
	  public SysParameter get(String id);
	  
	  public List<SysParameter> getAll();
}


