/**
  * @Template info: 2013/08/16, Chengqiyi.
  * ChengQiyi create in 2014/7/7 20:56:57
  * This class generated by CodeSmith Generator
  */

package hply.persistence;

import java.util.List;
import java.util.Map;

import hply.domain.SysResource;

public interface SysResourceMapper {

	  public void insert(SysResource sysResource);
	  
	  public void update(SysResource sysResource);
	  
	  public void delete(SysResource sysResource);
	  
	  public SysResource get(String id);
	  
	  public List<SysResource> getAll();
}


