/**
  * @Template info: 2013/08/16, Chengqiyi.
  * ChengQiyi create in 2014/7/8 8:16:29
  * This class generated by CodeSmith Generator
  */

package hply.persistence;

import hply.domain.SysUser;
import java.util.List;
import org.springframework.stereotype.Repository;

@Repository(value = "sysUserMapper")
public interface SysUserMapper {

	  public void insert(SysUser sysUser);
	  
	  public void update(SysUser sysUser);
	  
	  public void delete(SysUser sysUser);
	  
	  public SysUser get(String id);
	  
	  public List<SysUser> getAll();
}


