/**
  * @Template info: 2013/08/16, Chengqiyi.
  * ChengQiyi create in 2014/7/7 20:56:40
  * This class generated by CodeSmith Generator
  */

package hply.persistence;

import java.util.List;
import java.util.Map;

import hply.domain.SysUser;

public interface SysUserMapper {

	  public void insert(SysUser sysUser);
	  
	  public void update(SysUser sysUser);
	  
	  public void delete(SysUser sysUser);
	  
	  public SysUser get(String id);
	  
	  public List<SysUser> getAll();
}


