/**
  * @ ChengQiyi create in 2014-7-12 15:57:57 by Template at 2014年6月25日21:26:55
  * This class generated by CodeSmith Generator
  */

package hply.domain;

import java.io.Serializable;
import java.util.Date;
import java.text.MessageFormat;
import hply.common.Utility;


/**
  * 模型类，对应的数据库表： [t_arrears]
  * 
  */
public class Arrears implements Serializable {
        
  private String id;
  
/**
  * 读，数据库列：id  
  * 
  */
	public String getId() {
		return id;
	}

/**
  * 写，数据库列：id  
  * 
  */
	public void setId(String id) {
		this.id = id;
	}
		
        
  private String projectId;
  
/**
  * 读，数据库列：project_id  
  * 
  */
	public String getProjectId() {
		return projectId;
	}

/**
  * 写，数据库列：project_id  
  * 
  */
	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}
		
        
  private String arrearsType;
  
/**
  * 读，数据库列：arrears_type  
  * 
  */
	public String getArrearsType() {
		return arrearsType;
	}

/**
  * 写，数据库列：arrears_type  
  * 
  */
	public void setArrearsType(String arrearsType) {
		this.arrearsType = arrearsType;
	}
		
        
  private String payType;
  
/**
  * 读，数据库列：pay_type  
  * 
  */
	public String getPayType() {
		return payType;
	}

/**
  * 写，数据库列：pay_type  
  * 
  */
	public void setPayType(String payType) {
		this.payType = payType;
	}
		
        
  private double amount;
  
/**
  * 读，数据库列：amount  
  * 
  */
	public double getAmount() {
		return amount;
	}

/**
  * 写，数据库列：amount  
  * 
  */
	public void setAmount(double amount) {
		this.amount = amount;
	}
		
        
  private String bankAccount;
  
/**
  * 读，数据库列：bank_account  
  * 
  */
	public String getBankAccount() {
		return bankAccount;
	}

/**
  * 写，数据库列：bank_account  
  * 
  */
	public void setBankAccount(String bankAccount) {
		this.bankAccount = bankAccount;
	}
		
        
  private String bankName;
  
/**
  * 读，数据库列：bank_name  
  * 
  */
	public String getBankName() {
		return bankName;
	}

/**
  * 写，数据库列：bank_name  
  * 
  */
	public void setBankName(String bankName) {
		this.bankName = bankName;
	}
		
        
  private Date trice;
  
/**
  * 读，数据库列：trice  
  * 
  */
	public Date getTrice() {
		return trice;
	}

/**
  * 写，数据库列：trice  
  * 
  */
	public void setTrice(Date trice) {
		this.trice = trice;
	}
		
        
  private Date createTime;
  
/**
  * 读，数据库列：create_time  
  * 
  */
	public Date getCreateTime() {
		return createTime;
	}

/**
  * 写，数据库列：create_time  
  * 
  */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
		
        
  private String createUser;
  
/**
  * 读，数据库列：create_user  
  * 
  */
	public String getCreateUser() {
		return createUser;
	}

/**
  * 写，数据库列：create_user  
  * 
  */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}
		
        
  private Date updateTime;
  
/**
  * 读，数据库列：update_time  
  * 
  */
	public Date getUpdateTime() {
		return updateTime;
	}

/**
  * 写，数据库列：update_time  
  * 
  */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
		
        
  private String updateUser;
  
/**
  * 读，数据库列：update_user  
  * 
  */
	public String getUpdateUser() {
		return updateUser;
	}

/**
  * 写，数据库列：update_user  
  * 
  */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}
		
        
  private String description;
  
/**
  * 读，数据库列：description  
  * 
  */
	public String getDescription() {
		return description;
	}

/**
  * 写，数据库列：description  
  * 
  */
	public void setDescription(String description) {
		this.description = description;
	}
		
        
    @Override
	public String toString() {
		System.out.println(this.getClass().getName() + ".toString():");
        
        String str = Utility.EMPTY_STRING;
        str += MessageFormat.format("\tId=\"{0}\"\n", this.getId());
        str += MessageFormat.format("\tProjectId=\"{0}\"\n", this.getProjectId());
        str += MessageFormat.format("\tArrearsType=\"{0}\"\n", this.getArrearsType());
        str += MessageFormat.format("\tPayType=\"{0}\"\n", this.getPayType());
        str += MessageFormat.format("\tAmount=\"{0}\"\n", this.getAmount());
        str += MessageFormat.format("\tBankAccount=\"{0}\"\n", this.getBankAccount());
        str += MessageFormat.format("\tBankName=\"{0}\"\n", this.getBankName());
        str += MessageFormat.format("\tTrice=\"{0}\"\n", this.getTrice());
        str += MessageFormat.format("\tCreateTime=\"{0}\"\n", this.getCreateTime());
        str += MessageFormat.format("\tCreateUser=\"{0}\"\n", this.getCreateUser());
        str += MessageFormat.format("\tUpdateTime=\"{0}\"\n", this.getUpdateTime());
        str += MessageFormat.format("\tUpdateUser=\"{0}\"\n", this.getUpdateUser());
        str += MessageFormat.format("\tDescription=\"{0}\"\n", this.getDescription());;
        return str;
                        
	}
    
//======================================================================================
// TODO: 附加的其他方法 （ hply.domain.Arrears ）
//======================================================================================


}

