/**
  * @ ChengQiyi create in 2014-7-13 16:09:15 by Template at 2014年6月25日21:26:55
  * This class generated by CodeSmith Generator
  */

package hply.domain;

import hply.common.Utils;

import java.io.Serializable;
import java.text.MessageFormat;
import java.util.Date;

import org.apache.commons.lang3.StringUtils;


/**
  * 模型类，对应的数据库表： [t_chop]
  * 
  */
public class Chop implements Serializable {
        
  /**
	 * 
	 */
	private static final long serialVersionUID = 5479064606249621018L;
private String id;
  
/**
  * 读，数据库列： ID  
  * 
  */
	public String getId() {
        return StringUtils.trimToEmpty(id);
	}

/**
  * 写，数据库列：ID  
  * 
  */
	public void setId(String id) {
		this.id = id;
	}
		
        
  private String chopcode;
  
/**
  * 读，数据库列： ChopCode  
  * 
  */
	public String getChopcode() {
        return StringUtils.trimToEmpty(chopcode);
	}

/**
  * 写，数据库列：ChopCode  
  * 
  */
	public void setChopcode(String chopcode) {
		this.chopcode = chopcode;
	}
		
        
  private String projectid;
  
/**
  * 读，数据库列： ProjectID  
  * 
  */
	public String getProjectid() {
        return StringUtils.trimToEmpty(projectid);
	}

/**
  * 写，数据库列：ProjectID  
  * 
  */
	public void setProjectid(String projectid) {
		this.projectid = projectid;
	}
		
        
  private String projectcode;
  
/**
  * 读，数据库列： ProjectCode  
  * 
  */
	public String getProjectcode() {
        return StringUtils.trimToEmpty(projectcode);
	}

/**
  * 写，数据库列：ProjectCode  
  * 
  */
	public void setProjectcode(String projectcode) {
		this.projectcode = projectcode;
	}
		
        
  private String projectname;
  
/**
  * 读，数据库列： ProjectName  
  * 
  */
	public String getProjectname() {
        return StringUtils.trimToEmpty(projectname);
	}

/**
  * 写，数据库列：ProjectName  
  * 
  */
	public void setProjectname(String projectname) {
		this.projectname = projectname;
	}
		
        
  private String manager;
  
/**
  * 读，数据库列： Manager  
  * 
  */
	public String getManager() {
        return StringUtils.trimToEmpty(manager);
	}

/**
  * 写，数据库列：Manager  
  * 
  */
	public void setManager(String manager) {
		this.manager = manager;
	}
		
        
  private String content;
  
/**
  * 读，数据库列： Content  
  * 
  */
	public String getContent() {
        return StringUtils.trimToEmpty(content);
	}

/**
  * 写，数据库列：Content  
  * 
  */
	public void setContent(String content) {
		this.content = content;
	}
		
        
  private String applyuser;
  
/**
  * 读，数据库列： ApplyUser  
  * 
  */
	public String getApplyuser() {
        return StringUtils.trimToEmpty(applyuser);
	}

/**
  * 写，数据库列：ApplyUser  
  * 
  */
	public void setApplyuser(String applyuser) {
		this.applyuser = applyuser;
	}
		
        
  private Date applytime;
  
/**
  * 读，数据库列： ApplyTime  
  * 
  */
	public Date getApplytime() {
		return applytime;
	}

/**
  * 写，数据库列：ApplyTime  
  * 
  */
	public void setApplytime(Date applytime) {
		this.applytime = applytime;
	}
		
        
  private String organizationid;
  
/**
  * 读，数据库列： OrganizationID  
  * 
  */
	public String getOrganizationid() {
        return StringUtils.trimToEmpty(organizationid);
	}

/**
  * 写，数据库列：OrganizationID  
  * 
  */
	public void setOrganizationid(String organizationid) {
		this.organizationid = organizationid;
	}
		
        
  private String step1idea;
  
/**
  * 读，数据库列： Step1Idea  
  * 
  */
	public String getStep1idea() {
        return StringUtils.trimToEmpty(step1idea);
	}

/**
  * 写，数据库列：Step1Idea  
  * 
  */
	public void setStep1idea(String step1idea) {
		this.step1idea = step1idea;
	}
		
        
  private String step1user;
  
/**
  * 读，数据库列： Step1User  
  * 
  */
	public String getStep1user() {
        return StringUtils.trimToEmpty(step1user);
	}

/**
  * 写，数据库列：Step1User  
  * 
  */
	public void setStep1user(String step1user) {
		this.step1user = step1user;
	}
		
        
  private Date step1time;
  
/**
  * 读，数据库列： Step1Time  
  * 
  */
	public Date getStep1time() {
		return step1time;
	}

/**
  * 写，数据库列：Step1Time  
  * 
  */
	public void setStep1time(Date step1time) {
		this.step1time = step1time;
	}
		
        
  private String step2idea;
  
/**
  * 读，数据库列： Step2Idea  
  * 
  */
	public String getStep2idea() {
        return StringUtils.trimToEmpty(step2idea);
	}

/**
  * 写，数据库列：Step2Idea  
  * 
  */
	public void setStep2idea(String step2idea) {
		this.step2idea = step2idea;
	}
		
        
  private String step2user;
  
/**
  * 读，数据库列： Step2User  
  * 
  */
	public String getStep2user() {
        return StringUtils.trimToEmpty(step2user);
	}

/**
  * 写，数据库列：Step2User  
  * 
  */
	public void setStep2user(String step2user) {
		this.step2user = step2user;
	}
		
        
  private Date step2time;
  
/**
  * 读，数据库列： Step2Time  
  * 
  */
	public Date getStep2time() {
		return step2time;
	}

/**
  * 写，数据库列：Step2Time  
  * 
  */
	public void setStep2time(Date step2time) {
		this.step2time = step2time;
	}
		
        
  private String step3idea;
  
/**
  * 读，数据库列： Step3Idea  
  * 
  */
	public String getStep3idea() {
        return StringUtils.trimToEmpty(step3idea);
	}

/**
  * 写，数据库列：Step3Idea  
  * 
  */
	public void setStep3idea(String step3idea) {
		this.step3idea = step3idea;
	}
		
        
  private String step3user;
  
/**
  * 读，数据库列： Step3User  
  * 
  */
	public String getStep3user() {
        return StringUtils.trimToEmpty(step3user);
	}

/**
  * 写，数据库列：Step3User  
  * 
  */
	public void setStep3user(String step3user) {
		this.step3user = step3user;
	}
		
        
  private Date step3time;
  
/**
  * 读，数据库列： Step3Time  
  * 
  */
	public Date getStep3time() {
		return step3time;
	}

/**
  * 写，数据库列：Step3Time  
  * 
  */
	public void setStep3time(Date step3time) {
		this.step3time = step3time;
	}
		
        
  private String stepstatus;
  
/**
  * 读，数据库列： StepStatus  
  * 
  */
	public String getStepstatus() {
        return StringUtils.trimToEmpty(stepstatus);
	}

/**
  * 写，数据库列：StepStatus  
  * 
  */
	public void setStepstatus(String stepstatus) {
		this.stepstatus = stepstatus;
	}
		
        
    @Override
	public String toString() {
		System.out.println(this.getClass().getName() + ".toString():");
        
        String str = Utils.EMPTY;
        str += MessageFormat.format("\tId=\"{0}\"\n", this.getId());
        str += MessageFormat.format("\tChopcode=\"{0}\"\n", this.getChopcode());
        str += MessageFormat.format("\tProjectid=\"{0}\"\n", this.getProjectid());
        str += MessageFormat.format("\tProjectcode=\"{0}\"\n", this.getProjectcode());
        str += MessageFormat.format("\tProjectname=\"{0}\"\n", this.getProjectname());
        str += MessageFormat.format("\tManager=\"{0}\"\n", this.getManager());
        str += MessageFormat.format("\tContent=\"{0}\"\n", this.getContent());
        str += MessageFormat.format("\tApplyuser=\"{0}\"\n", this.getApplyuser());
        str += MessageFormat.format("\tApplytime=\"{0}\"\n", this.getApplytime());
        str += MessageFormat.format("\tOrganizationid=\"{0}\"\n", this.getOrganizationid());
        str += MessageFormat.format("\tStep1idea=\"{0}\"\n", this.getStep1idea());
        str += MessageFormat.format("\tStep1user=\"{0}\"\n", this.getStep1user());
        str += MessageFormat.format("\tStep1time=\"{0}\"\n", this.getStep1time());
        str += MessageFormat.format("\tStep2idea=\"{0}\"\n", this.getStep2idea());
        str += MessageFormat.format("\tStep2user=\"{0}\"\n", this.getStep2user());
        str += MessageFormat.format("\tStep2time=\"{0}\"\n", this.getStep2time());
        str += MessageFormat.format("\tStep3idea=\"{0}\"\n", this.getStep3idea());
        str += MessageFormat.format("\tStep3user=\"{0}\"\n", this.getStep3user());
        str += MessageFormat.format("\tStep3time=\"{0}\"\n", this.getStep3time());
        str += MessageFormat.format("\tStepstatus=\"{0}\"\n", this.getStepstatus());;
        return str;
                        
	}

}

