/**
  * @ ChengQiyi create in 2014-7-13 15:01:53 by Template at 2014年6月25日21:26:55
  * This class generated by CodeSmith Generator
  */

package hply.domain;

import java.io.Serializable;
import java.util.Date;
import java.text.MessageFormat;
import hply.common.Utility;


/**
  * 模型类，对应的数据库表： [t_contract_supplemental_agreement]
  * 
  */
public class ContractSupplementalAgreement implements Serializable {
        
  private String id;
  
/**
  * 读，数据库列： ID  
  * 
  */
	public String getId() {
		return id;
	}

/**
  * 写，数据库列：ID  
  * 
  */
	public void setId(String id) {
		this.id = id;
	}
		
        
  private String projectid;
  
/**
  * 读，数据库列： ProjectID  
  * 
  */
	public String getProjectid() {
		return projectid;
	}

/**
  * 写，数据库列：ProjectID  
  * 
  */
	public void setProjectid(String projectid) {
		this.projectid = projectid;
	}
		
        
  private String csacode;
  
/**
  * 读，数据库列： CsaCode  
  * 
  */
	public String getCsacode() {
		return csacode;
	}

/**
  * 写，数据库列：CsaCode  
  * 
  */
	public void setCsacode(String csacode) {
		this.csacode = csacode;
	}
		
        
  private double managementrate;
  
/**
  * 读，数据库列： ManagementRate  
  * 
  */
	public double getManagementrate() {
		return managementrate;
	}

/**
  * 写，数据库列：ManagementRate  
  * 
  */
	public void setManagementrate(double managementrate) {
		this.managementrate = managementrate;
	}
		
        
  private double changeamount;
  
/**
  * 读，数据库列： ChangeAmount  
  * 
  */
	public double getChangeamount() {
		return changeamount;
	}

/**
  * 写，数据库列：ChangeAmount  
  * 
  */
	public void setChangeamount(double changeamount) {
		this.changeamount = changeamount;
	}
		
        
  private Date trice;
  
/**
  * 读，数据库列： Trice  
  * 
  */
	public Date getTrice() {
		return trice;
	}

/**
  * 写，数据库列：Trice  
  * 
  */
	public void setTrice(Date trice) {
		this.trice = trice;
	}
		
        
  private Date createtime;
  
/**
  * 读，数据库列： CreateTime  
  * 
  */
	public Date getCreatetime() {
		return createtime;
	}

/**
  * 写，数据库列：CreateTime  
  * 
  */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}
		
        
  private String createuser;
  
/**
  * 读，数据库列： CreateUser  
  * 
  */
	public String getCreateuser() {
		return createuser;
	}

/**
  * 写，数据库列：CreateUser  
  * 
  */
	public void setCreateuser(String createuser) {
		this.createuser = createuser;
	}
		
        
  private Date updatetime;
  
/**
  * 读，数据库列： UpdateTime  
  * 
  */
	public Date getUpdatetime() {
		return updatetime;
	}

/**
  * 写，数据库列：UpdateTime  
  * 
  */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}
		
        
  private String updateuser;
  
/**
  * 读，数据库列： UpdateUser  
  * 
  */
	public String getUpdateuser() {
		return updateuser;
	}

/**
  * 写，数据库列：UpdateUser  
  * 
  */
	public void setUpdateuser(String updateuser) {
		this.updateuser = updateuser;
	}
		
        
  private String description;
  
/**
  * 读，数据库列： Description  
  * 
  */
	public String getDescription() {
		return description;
	}

/**
  * 写，数据库列：Description  
  * 
  */
	public void setDescription(String description) {
		this.description = description;
	}
		
        
    @Override
	public String toString() {
		System.out.println(this.getClass().getName() + ".toString():");
        
        String str = Utility.EMPTY_STRING;
        str += MessageFormat.format("\tId=\"{0}\"\n", this.getId());
        str += MessageFormat.format("\tProjectid=\"{0}\"\n", this.getProjectid());
        str += MessageFormat.format("\tCsacode=\"{0}\"\n", this.getCsacode());
        str += MessageFormat.format("\tManagementrate=\"{0}\"\n", this.getManagementrate());
        str += MessageFormat.format("\tChangeamount=\"{0}\"\n", this.getChangeamount());
        str += MessageFormat.format("\tTrice=\"{0}\"\n", this.getTrice());
        str += MessageFormat.format("\tCreatetime=\"{0}\"\n", this.getCreatetime());
        str += MessageFormat.format("\tCreateuser=\"{0}\"\n", this.getCreateuser());
        str += MessageFormat.format("\tUpdatetime=\"{0}\"\n", this.getUpdatetime());
        str += MessageFormat.format("\tUpdateuser=\"{0}\"\n", this.getUpdateuser());
        str += MessageFormat.format("\tDescription=\"{0}\"\n", this.getDescription());;
        return str;
                        
	}

}

