/**
 * @ cqiyi create in 2014/7/24 20:49:20 by Template
 * This class generated by Forever Web Rapid Framework Code Generator
 */

package hply.domain;

import hply.Utility;

import java.io.Serializable;
import java.text.MessageFormat;
import java.util.Date;

import javax.validation.constraints.NotNull;

import org.apache.commons.lang3.StringUtils;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.format.annotation.DateTimeFormat.ISO;

/**
 * 数据表： [t_customer_billing]
 * 
 */
public class CustomerBilling implements Serializable {

	/*
	 * 默认构造函数
	 */
	public CustomerBilling() {
		this.id = Utility.getRandomUUID();
		this.version = -1;
	}

	/**
	 * [id]，
	 * 
	 */

	@NotNull
	private String id;

	/**
	 * [project_id]，
	 * 
	 */

	private String projectId;

	/**
	 * [invoice_code]，
	 * 
	 */

	private String invoiceCode;

	/**
	 * [invoice_type]，
	 * 
	 */

	private String invoiceType;

	/**
	 * [amount]，
	 * 
	 */

	@NotNull
	private double amount;

	/**
	 * [trice]，
	 * 
	 */

	@DateTimeFormat(iso = ISO.DATE)
	private Date trice;

	/**
	 * [create_time]，
	 * 
	 */

	@DateTimeFormat(iso = ISO.DATE)
	private Date createTime;

	/**
	 * [create_user]，
	 * 
	 */

	private String createUser;

	/**
	 * [update_time]，
	 * 
	 */

	@DateTimeFormat(iso = ISO.DATE)
	private Date updateTime;

	/**
	 * [update_user]，
	 * 
	 */

	private String updateUser;

	/**
	 * [description]，
	 * 
	 */

	private String description;

	/**
	 * [version]，
	 * 
	 */

	@NotNull
	private int version;

	/**
	 * [id] getter，
	 * 
	 */
	public String getId() {
		return StringUtils.trimToEmpty(id);
	}

	/**
	 * [id] setter，
	 * 
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * [project_id] getter，
	 * 
	 */
	public String getProjectId() {
		return StringUtils.trimToEmpty(projectId);
	}

	/**
	 * [project_id] setter，
	 * 
	 */
	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}

	/**
	 * [invoice_code] getter，
	 * 
	 */
	public String getInvoiceCode() {
		return StringUtils.trimToEmpty(invoiceCode);
	}

	/**
	 * [invoice_code] setter，
	 * 
	 */
	public void setInvoiceCode(String invoiceCode) {
		this.invoiceCode = invoiceCode;
	}

	/**
	 * [invoice_type] getter，
	 * 
	 */
	public String getInvoiceType() {
		return StringUtils.trimToEmpty(invoiceType);
	}

	/**
	 * [invoice_type] setter，
	 * 
	 */
	public void setInvoiceType(String invoiceType) {
		this.invoiceType = invoiceType;
	}

	/**
	 * [amount] getter，
	 * 
	 */
	public double getAmount() {
		return amount;
	}

	/**
	 * [amount] setter，
	 * 
	 */
	public void setAmount(double amount) {
		this.amount = amount;
	}

	/**
	 * [trice] getter，
	 * 
	 */
	public Date getTrice() {
		return trice;
	}

	/**
	 * [trice] setter，
	 * 
	 */
	public void setTrice(Date trice) {
		this.trice = trice;
	}

	/**
	 * [create_time] getter，
	 * 
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * [create_time] setter，
	 * 
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * [create_user] getter，
	 * 
	 */
	public String getCreateUser() {
		return StringUtils.trimToEmpty(createUser);
	}

	/**
	 * [create_user] setter，
	 * 
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * [update_time] getter，
	 * 
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * [update_time] setter，
	 * 
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * [update_user] getter，
	 * 
	 */
	public String getUpdateUser() {
		return StringUtils.trimToEmpty(updateUser);
	}

	/**
	 * [update_user] setter，
	 * 
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	/**
	 * [description] getter，
	 * 
	 */
	public String getDescription() {
		return StringUtils.trimToEmpty(description);
	}

	/**
	 * [description] setter，
	 * 
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * [version] getter，
	 * 
	 */
	public int getVersion() {
		return version;
	}

	/**
	 * [version] setter，
	 * 
	 */
	public void setVersion(int version) {
		this.version = version;
	}

	@Override
	public String toString() {
		System.out.println(this.getClass().getName() + ".toString():");

		String str = StringUtils.EMPTY;
		str += MessageFormat.format("Id=\"{0}\",", this.getId());
		str += MessageFormat.format("ProjectId=\"{0}\",", this.getProjectId());
		str += MessageFormat.format("InvoiceCode=\"{0}\",",
				this.getInvoiceCode());
		str += MessageFormat.format("InvoiceType=\"{0}\",",
				this.getInvoiceType());
		str += MessageFormat.format("Amount=\"{0}\",", this.getAmount());
		str += MessageFormat.format("Trice=\"{0}\",", this.getTrice());
		str += MessageFormat
				.format("CreateTime=\"{0}\",", this.getCreateTime());
		str += MessageFormat
				.format("CreateUser=\"{0}\",", this.getCreateUser());
		str += MessageFormat
				.format("UpdateTime=\"{0}\",", this.getUpdateTime());
		str += MessageFormat
				.format("UpdateUser=\"{0}\",", this.getUpdateUser());
		str += MessageFormat.format("Description=\"{0}\",",
				this.getDescription());
		str += MessageFormat.format("Version=\"{0}\",", this.getVersion());
		;
		return str;

	}
}
