/**
  * @ cqiyi create in 2014-12-8 6:26:38 by Template
  * This class generated by Forever Web Rapid Framework Code Generator
  */

package hply.domain;

import java.io.Serializable;
import java.text.MessageFormat;
import java.util.Date;

import org.apache.commons.lang3.StringUtils;
import hply.core.Utility;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.format.annotation.DateTimeFormat.ISO;

/**
  * 数据表： [t_information]
  * 10_信息登记
  */
public class Information implements Serializable {
    
    	/**
	 * 
	 */
	private static final long serialVersionUID = -7141284040589002950L;
		/*
    	 * ID
    	 */
        public static final String FIELD_ID = "id";
    	/*
    	 * 所属部门
    	 */
        public static final String FIELD_ORGANIZATION_ID = "organization_id";
    	/*
    	 * 工程名称
    	 */
        public static final String FIELD_PROJECT_NAME = "project_name";
    	/*
    	 * 工程地点
    	 */
        public static final String FIELD_ADDRESS = "address";
    	/*
    	 * 建设单位
    	 */
        public static final String FIELD_CONSTRUCTION_COMPANY = "construction_company";
    	/*
    	 * 总包方
    	 */
        public static final String FIELD_GENERAL_CONTRACTOR = "general_contractor";
    	/*
    	 * 加盟客户姓名
    	 */
        public static final String FIELD_JOIN_REAL_NAME = "join_real_name";
    	/*
    	 * 装饰类别
    	 */
        public static final String FIELD_DECORATION_TYPE = "decoration_type";
    	/*
    	 * 工程量
    	 */
        public static final String FIELD_QUANTITIES = "quantities";
    	/*
    	 * 综合服务费
    	 */
        public static final String FIELD_SERVICE_AMOUNT = "service_amount";
    	/*
    	 * 缴费标识0-未缴费，1-已缴费
    	 */
        public static final String FIELD_PAY_FLAG = "pay_flag";
    	/*
    	 * 确认缴费时间
    	 */
        public static final String FIELD_PAY_TIME = "pay_time";
    	/*
    	 * 确认缴费用户
    	 */
        public static final String FIELD_PAY_USER = "pay_user";
    	/*
    	 * 盖章标识0-未盖章，1-已盖章
    	 */
        public static final String FIELD_SEAL_FLAG = "seal_flag";
    	/*
    	 * 确认盖章时间
    	 */
        public static final String FIELD_SEAL_TIME = "seal_time";
    	/*
    	 * 确认盖章用户
    	 */
        public static final String FIELD_SEAL_USER = "seal_user";
    	/*
    	 * 确认审核时间
    	 */
        public static final String FIELD_AUDIT_TIME = "audit_time";
    	/*
    	 * 确认审核用户
    	 */
        public static final String FIELD_AUDIT_USER = "audit_user";
    	/*
    	 * 应收证书费
    	 */
        public static final String FIELD_CERTIFICATE_PLAN_AMOUNT = "certificate_plan_amount";
    	/*
    	 * 已收证书费
    	 */
        public static final String FIELD_CERTIFICATE_REAL_AMOUNT = "certificate_real_amount";
    	/*
    	 * 尚欠证书费
    	 */
        public static final String FIELD_CERTIFICATE_OWE_AMOUNT = "certificate_owe_amount";
    	/*
    	 * 登记人
    	 */
        public static final String FIELD_SUBSCRIBER = "subscriber";
    	/*
    	 * 登记时间
    	 */
        public static final String FIELD_TRICE = "trice";
    	/*
    	 * 创建时间
    	 */
        public static final String FIELD_CREATE_TIME = "create_time";
    	/*
    	 * 创建用户
    	 */
        public static final String FIELD_CREATE_USER = "create_user";
    	/*
    	 * 修改时间
    	 */
        public static final String FIELD_UPDATE_TIME = "update_time";
    	/*
    	 * 修改用户
    	 */
        public static final String FIELD_UPDATE_USER = "update_user";
    	/*
    	 * 备注
    	 */
        public static final String FIELD_DESCRIPTION = "description";
    	/*
    	 * 
    	 */
        public static final String FIELD_VERSION = "version";
    	/*
    	 * 数据状态，0：草稿/1：正式
    	 */
        public static final String FIELD_STATUS = "status";
    	/*
    	 * 预留字段01
    	 */
        public static final String FIELD_FIELD_01 = "field_01";
    	/*
    	 * 预留字段02
    	 */
        public static final String FIELD_FIELD_02 = "field_02";
    	/*
    	 * 预留字段03
    	 */
        public static final String FIELD_FIELD_03 = "field_03";
    	/*
    	 * 预留字段04
    	 */
        public static final String FIELD_FIELD_04 = "field_04";
    	/*
    	 * 预留字段05
    	 */
        public static final String FIELD_FIELD_05 = "field_05";

	/*
	 * 默认构造函数
	 */
	public Information() {
		this.id = Utility.getRandomUUID(); 
        this.payFlag = "0"; 
        this.sealFlag = "0"; 
        this.trice = new Date(); 
        String userId = Utility.getCurrentUserId();
        this.subscriber = userId; 
        this.createTime = new Date(); 
		this.createUser = userId; 
        this.status = 0; 
        this.version = -1; 
	}

    /**
      * [id]，
      * ID
      */
      
      private String id;
      
    /**
      * [organization_id]，
      * 所属部门
      */
      
      private String organizationId;
      
    /**
      * [project_name]，
      * 工程名称
      */
      
      private String projectName;
      
    /**
      * [address]，
      * 工程地点
      */
      
      private String address;
      
    /**
      * [construction_company]，
      * 建设单位
      */
      
      private String constructionCompany;
      
    /**
      * [general_contractor]，
      * 总包方
      */
      
      private String generalContractor;
      
    /**
      * [join_real_name]，
      * 加盟客户姓名
      */
      
      private String joinRealName;
      
    /**
      * [decoration_type]，
      * 装饰类别
      */
      
      private String decorationType;
      
    /**
      * [quantities]，
      * 工程量
      */
      
      private String quantities;
      
    /**
      * [service_amount]，
      * 综合服务费
      */
      
      private double serviceAmount;
      
    /**
      * [pay_flag]，
      * 缴费标识0-未缴费，1-已缴费
      */
      
      private String payFlag;
      /**
       * [pay_time]，
       * 确认缴费时间
       */
       @DateTimeFormat(iso=ISO.DATE)
       private Date payTime;
       
     /**
       * [pay_user]，
       * 确认缴费用户
       */
       
       private String payUser;
      
    /**
      * [seal_flag]，
      * 盖章标识0-未盖章，1-已盖章
      */
      
      private String sealFlag;
      /**
       * [seal_time]，
       * 确认盖章时间
       */
       @DateTimeFormat(iso=ISO.DATE)
       private Date sealTime;
       
     /**
       * [seal_user]，
       * 确认盖章用户
       */
       
       private String sealUser;
       /**
        * [audit_time]，
        * 确认审核时间
        */
        @DateTimeFormat(iso=ISO.DATE)
        private Date auditTime;
        
      /**
        * [audit_user]，
        * 确认审核用户
        */
        
        private String auditUser;
            
    /**
      * [certificate_plan_amount]，
      * 应收证书费
      */
      
      private double certificatePlanAmount;
      
    /**
      * [certificate_real_amount]，
      * 已收证书费
      */
      
      private double certificateRealAmount;
      
    /**
      * [certificate_owe_amount]，
      * 尚欠证书费
      */
      
      private double certificateOweAmount;
      
    /**
      * [subscriber]，
      * 登记人
      */
      
      private String subscriber;
      
    /**
      * [trice]，
      * 登记时间
      */
      @DateTimeFormat(iso=ISO.DATE)
      private Date trice;
      
    /**
      * [create_time]，
      * 创建时间
      */
      @DateTimeFormat(iso=ISO.DATE)
      private Date createTime;
      
    /**
      * [create_user]，
      * 创建用户
      */
      
      private String createUser;
      
    /**
      * [update_time]，
      * 修改时间
      */
      @DateTimeFormat(iso=ISO.DATE)
      private Date updateTime;
      
    /**
      * [update_user]，
      * 修改用户
      */
      
      private String updateUser;
      
    /**
      * [description]，
      * 备注
      */
      
      private String description;
      
    /**
      * [version]，
      * 
      */
      
      private Integer version;
      
    /**
      * [status]，
      * 数据状态，0：草稿/1：正式
      */
      
      private Integer status;
      
    /**
      * [field_01]，
      * 预留字段01
      */
      
      private String field01;
      
    /**
      * [field_02]，
      * 预留字段02
      */
      
      private String field02;
      
    /**
      * [field_03]，
      * 预留字段03
      */
      
      private String field03;
      
    /**
      * [field_04]，
      * 预留字段04
      */
      
      private String field04;
      
    /**
      * [field_05]，
      * 预留字段05
      */
      
      private String field05;
      
    
    /**
      * [id] getter，
      * ID
      */
    	public String getId () {
    		return this.id;
    	}

    /**
      * [id] setter，
      * ID
      */
    	public void setId(String id) {
    		this.id = id;
    	}
    /**
      * [organization_id] getter，
      * 所属部门
      */
    	public String getOrganizationId () {
    		return this.organizationId;
    	}

    /**
      * [organization_id] setter，
      * 所属部门
      */
    	public void setOrganizationId(String organizationId) {
    		this.organizationId = organizationId;
    	}
    /**
      * [project_name] getter，
      * 工程名称
      */
    	public String getProjectName () {
    		return this.projectName;
    	}

    /**
      * [project_name] setter，
      * 工程名称
      */
    	public void setProjectName(String projectName) {
    		this.projectName = projectName;
    	}
    /**
      * [address] getter，
      * 工程地点
      */
    	public String getAddress () {
    		return this.address;
    	}

    /**
      * [address] setter，
      * 工程地点
      */
    	public void setAddress(String address) {
    		this.address = address;
    	}
    /**
      * [construction_company] getter，
      * 建设单位
      */
    	public String getConstructionCompany () {
    		return this.constructionCompany;
    	}

    /**
      * [construction_company] setter，
      * 建设单位
      */
    	public void setConstructionCompany (String constructionCompany) {
    		this.constructionCompany = constructionCompany;
    	}
    /**
      * [general_contractor] getter，
      * 总包方
      */
    	public String getGeneralContractor () {
    		return this.generalContractor;
    	}

    /**
      * [general_contractor] setter，
      * 总包方
      */
    	public void setGeneralContractor(String generalContractor) {
    		this.generalContractor = generalContractor;
    	}
    /**
      * [join_real_name] getter，
      * 加盟客户姓名
      */
    	public String getJoinRealName () {
    		return this.joinRealName;
    	}

    /**
      * [join_real_name] setter，
      * 加盟客户姓名
      */
    	public void setJoinRealName(String joinRealName) {
    		this.joinRealName = joinRealName;
    	}
        /**
         * [decoration_type] getter，
         * 装饰类别
         */
       	public String getDecorationType () {
       		return this.decorationType;
       	}

       /**
         * [decoration_type] setter，
         * 装饰类别
         */
       	public void setDecorationType(String decorationType) {
       		this.decorationType = decorationType;
       	}
        /**
         * [quantities] getter，
         * 工程量
         */
       	public String getQuantities () {
       		return this.quantities;
       	}

       /**
         * [quantities] setter，
         * 工程量
         */
       	public void setQuantities(String quantities) {
       		this.quantities = quantities;
       	}
	
		public double getServiceAmount() {
			return serviceAmount;
		}
	
		public void setServiceAmount(double serviceAmount) {
			this.serviceAmount = serviceAmount;
		}
    /**
      * [pay_flag] getter，
      * 缴费标识0-未缴费，1-已缴费
      */
    	public String getPayFlag () {
    		return this.payFlag;
    	}

    /**
      * [pay_flag] setter，
      * 缴费标识0-未缴费，1-已缴费
      */
    	public void setPayFlag(String payFlag) {
    		this.payFlag = payFlag;
    	}

        /**
          * [pay_time] getter，
          * 确认缴费时间
          */
        	public Date getPayTime () {
        		return this.payTime;
        	}

        /**
          * [pay_time] setter，
          * 确认缴费时间
          */
        	public void setPayTime(Date payTime) {
        		this.payTime = payTime;
        	}
        /**
          * [pay_user] getter，
          * 确认缴费用户
          */
        	public String getPayUser () {
        		return this.payUser;
        	}

        /**
          * [pay_user] setter，
          * 确认缴费用户
          */
        	public void setPayUser(String payUser) {
        		this.payUser = payUser;
        	}
    /**
      * [seal_flag] getter，
      * 盖章标识0-未盖章，1-已盖章
      */
    	public String getSealFlag () {
    		return this.sealFlag;
    	}

    /**
      * [seal_flag] setter，
      * 盖章标识0-未盖章，1-已盖章
      */
    	public void setSealFlag(String sealFlag) {
    		this.sealFlag = sealFlag;
    	}

        /**
          * [seal_time] getter，
          * 确认盖章时间
          */
        	public Date getSealTime () {
        		return this.sealTime;
        	}

        /**
          * [seal_time] setter，
          * 确认盖章时间
          */
        	public void setSealTime(Date sealTime) {
        		this.sealTime = sealTime;
        	}
        /**
          * [seal_user] getter，
          * 确认盖章用户
          */
        	public String getSealUser () {
        		return this.sealUser;
        	}

        /**
          * [seal_user] setter，
          * 确认盖章用户
          */
        	public void setSealUser(String sealUser) {
        		this.sealUser = sealUser;
        	}

            /**
              * [audit_time] getter，
              * 确认审核时间
              */
            	public Date getAuditTime () {
            		return this.auditTime;
            	}

            /**
              * [audit_time] setter，
              * 确认审核时间
              */
            	public void setAuditTime(Date auditTime) {
            		this.auditTime = auditTime;
            	}
            /**
              * [audit_user] getter，
              * 确认审核用户
              */
            	public String getAuditUser () {
            		return this.auditUser;
            	}

            /**
              * [audit_user] setter，
              * 确认审核用户
              */
            	public void setAuditUser(String auditUser) {
            		this.auditUser = auditUser;
            	}
	
		public double getCertificatePlanAmount() {
			return certificatePlanAmount;
		}
	
		public void setCertificatePlanAmount(double certificatePlanAmount) {
			this.certificatePlanAmount = certificatePlanAmount;
		}
	
		public double getCertificateRealAmount() {
			return certificateRealAmount;
		}
	
		public void setCertificateRealAmount(double certificateRealAmount) {
			this.certificateRealAmount = certificateRealAmount;
		}
	
		public double getCertificateOweAmount() {
			return certificateOweAmount;
		}
	
		public void setCertificateOweAmount(double certificateOweAmount) {
			this.certificateOweAmount = certificateOweAmount;
		}

	/**
      * [subscriber] getter，
      * 登记人
      */
    	public String getSubscriber () {
    		return this.subscriber;
    	}

    /**
      * [subscriber] setter，
      * 登记人
      */
    	public void setSubscriber(String subscriber) {
    		this.subscriber = subscriber;
    	}
    /**
      * [trice] getter，
      * 登记时间
      */
    	public Date getTrice () {
    		return this.trice;
    	}

    /**
      * [trice] setter，
      * 登记时间
      */
    	public void setTrice(Date trice) {
    		this.trice = trice;
    	}
    /**
      * [create_time] getter，
      * 创建时间
      */
    	public Date getCreateTime () {
    		return this.createTime;
    	}

    /**
      * [create_time] setter，
      * 创建时间
      */
    	public void setCreateTime(Date createTime) {
    		this.createTime = createTime;
    	}
    /**
      * [create_user] getter，
      * 创建用户
      */
    	public String getCreateUser () {
    		return this.createUser;
    	}

    /**
      * [create_user] setter，
      * 创建用户
      */
    	public void setCreateUser(String createUser) {
    		this.createUser = createUser;
    	}
    /**
      * [update_time] getter，
      * 修改时间
      */
    	public Date getUpdateTime () {
    		return this.updateTime;
    	}

    /**
      * [update_time] setter，
      * 修改时间
      */
    	public void setUpdateTime(Date updateTime) {
    		this.updateTime = updateTime;
    	}
    /**
      * [update_user] getter，
      * 修改用户
      */
    	public String getUpdateUser () {
    		return this.updateUser;
    	}

    /**
      * [update_user] setter，
      * 修改用户
      */
    	public void setUpdateUser(String updateUser) {
    		this.updateUser = updateUser;
    	}
    /**
      * [description] getter，
      * 备注
      */
    	public String getDescription () {
    		return this.description;
    	}

    /**
      * [description] setter，
      * 备注
      */
    	public void setDescription(String description) {
    		this.description = description;
    	}
    /**
      * [version] getter，
      * 
      */
    	public Integer getVersion () {
    		return this.version;
    	}

    /**
      * [version] setter，
      * 
      */
    	public void setVersion(Integer version) {
    		this.version = version;
    	}
    /**
      * [status] getter，
      * 数据状态，0：草稿/1：正式
      */
    	public Integer getStatus () {
    		return this.status;
    	}

    /**
      * [status] setter，
      * 数据状态，0：草稿/1：正式
      */
    	public void setStatus(Integer status) {
    		this.status = status;
    	}
    /**
      * [field_01] getter，
      * 预留字段01
      */
    	public String getField01 () {
    		return this.field01;
    	}

    /**
      * [field_01] setter，
      * 预留字段01
      */
    	public void setField01(String field01) {
    		this.field01 = field01;
    	}
    /**
      * [field_02] getter，
      * 预留字段02
      */
    	public String getField02 () {
    		return this.field02;
    	}

    /**
      * [field_02] setter，
      * 预留字段02
      */
    	public void setField02(String field02) {
    		this.field02 = field02;
    	}
    /**
      * [field_03] getter，
      * 预留字段03
      */
    	public String getField03 () {
    		return this.field03;
    	}

    /**
      * [field_03] setter，
      * 预留字段03
      */
    	public void setField03(String field03) {
    		this.field03 = field03;
    	}
    /**
      * [field_04] getter，
      * 预留字段04
      */
    	public String getField04 () {
    		return this.field04;
    	}

    /**
      * [field_04] setter，
      * 预留字段04
      */
    	public void setField04(String field04) {
    		this.field04 = field04;
    	}
    /**
      * [field_05] getter，
      * 预留字段05
      */
    	public String getField05 () {
    		return this.field05;
    	}

    /**
      * [field_05] setter，
      * 预留字段05
      */
    	public void setField05(String field05) {
    		this.field05 = field05;
    	}
    
	@Override
	public String toString() {
		System.out.println(this.getClass().getName() + ".toString():");
        
        String str = StringUtils.EMPTY;
        str += MessageFormat.format("Id=\"{0}\",", StringUtils.trimToEmpty(this.getId()));
        str += MessageFormat.format("OrganizationId=\"{0}\",", StringUtils.trimToEmpty(this.getOrganizationId()));
        str += MessageFormat.format("ProjectName=\"{0}\",", StringUtils.trimToEmpty(this.getProjectName()));
        str += MessageFormat.format("Address=\"{0}\",", StringUtils.trimToEmpty(this.getAddress()));
        str += MessageFormat.format("ConstructionCompany=\"{0}\",", StringUtils.trimToEmpty(this.getConstructionCompany()));
        str += MessageFormat.format("GeneralContractor=\"{0}\",", StringUtils.trimToEmpty(this.getGeneralContractor()));
        str += MessageFormat.format("JoinRealName=\"{0}\",", StringUtils.trimToEmpty(this.getJoinRealName()));
        str += MessageFormat.format("DecorationType=\"{0}\",", StringUtils.trimToEmpty(this.getDecorationType()));
        str += MessageFormat.format("Quantities=\"{0}\",", StringUtils.trimToEmpty(this.getQuantities()));
        str += MessageFormat.format("ServiceAmount=\"{0}\",", this.getServiceAmount());
        str += MessageFormat.format("PayFlag=\"{0}\",", StringUtils.trimToEmpty(this.getPayFlag()));
        str += MessageFormat.format("PayTime=\"{0}\",", this.getPayTime());
        str += MessageFormat.format("PayUser=\"{0}\",", StringUtils.trimToEmpty(this.getPayUser()));
        str += MessageFormat.format("SealFlag=\"{0}\",", StringUtils.trimToEmpty(this.getSealFlag()));
        str += MessageFormat.format("SealTime=\"{0}\",", this.getSealTime());
        str += MessageFormat.format("SealUser=\"{0}\",", StringUtils.trimToEmpty(this.getSealUser()));
        str += MessageFormat.format("AuditTime=\"{0}\",", this.getAuditTime());
        str += MessageFormat.format("AuditUser=\"{0}\",", StringUtils.trimToEmpty(this.getAuditUser()));
        str += MessageFormat.format("CertificatePlanAmount=\"{0}\",", this.getCertificatePlanAmount());
        str += MessageFormat.format("CertificateRealAmount=\"{0}\",", this.getCertificateRealAmount());
        str += MessageFormat.format("CertificateOweAmount=\"{0}\",", this.getCertificateOweAmount());
        str += MessageFormat.format("Subscriber=\"{0}\",", StringUtils.trimToEmpty(this.getSubscriber()));
        str += MessageFormat.format("Trice=\"{0}\",", this.getTrice());
        str += MessageFormat.format("CreateTime=\"{0}\",", this.getCreateTime());
        str += MessageFormat.format("CreateUser=\"{0}\",", StringUtils.trimToEmpty(this.getCreateUser()));
        str += MessageFormat.format("UpdateTime=\"{0}\",", this.getUpdateTime());
        str += MessageFormat.format("UpdateUser=\"{0}\",", StringUtils.trimToEmpty(this.getUpdateUser()));
        str += MessageFormat.format("Description=\"{0}\",", StringUtils.trimToEmpty(this.getDescription()));
        str += MessageFormat.format("Version=\"{0}\",", this.getVersion());
        str += MessageFormat.format("Status=\"{0}\",", this.getStatus());
        str += MessageFormat.format("Field01=\"{0}\",", StringUtils.trimToEmpty(this.getField01()));
        str += MessageFormat.format("Field02=\"{0}\",", StringUtils.trimToEmpty(this.getField02()));
        str += MessageFormat.format("Field03=\"{0}\",", StringUtils.trimToEmpty(this.getField03()));
        str += MessageFormat.format("Field04=\"{0}\",", StringUtils.trimToEmpty(this.getField04()));
        str += MessageFormat.format("Field05=\"{0}\",", StringUtils.trimToEmpty(this.getField05()));
        return str;
                        
	}
}

