/**
  * @ ChengQiyi create in 2014-7-12 23:05:31 by Template at 2014年6月25日21:26:55
  * This class generated by CodeSmith Generator
  */

package hply.domain;

import java.io.Serializable;
import java.util.Date;
import java.text.MessageFormat;
import hply.common.Utility;


/**
  * 模型类，对应的数据库表： [t_project]
  * 
  */
public class Project implements Serializable {
        
  private String id;
  
/**
  * 读，数据库列： ID  
  * 
  */
	public String getId() {
		return id;
	}

/**
  * 写，数据库列：ID  
  * 
  */
	public void setId(String id) {
		this.id = id;
	}
		
        
  private String projectcode;
  
/**
  * 读，数据库列： ProjectCode  
  * 
  */
	public String getProjectcode() {
		return projectcode;
	}

/**
  * 写，数据库列：ProjectCode  
  * 
  */
	public void setProjectcode(String projectcode) {
		this.projectcode = projectcode;
	}
		
        
  private String projectname;
  
/**
  * 读，数据库列： ProjectName  
  * 
  */
	public String getProjectname() {
		return projectname;
	}

/**
  * 写，数据库列：ProjectName  
  * 
  */
	public void setProjectname(String projectname) {
		this.projectname = projectname;
	}
		
        
  private String organizationid;
  
/**
  * 读，数据库列： OrganizationID  
  * 
  */
	public String getOrganizationid() {
		return organizationid;
	}

/**
  * 写，数据库列：OrganizationID  
  * 
  */
	public void setOrganizationid(String organizationid) {
		this.organizationid = organizationid;
	}
		
        
  private String partyname;
  
/**
  * 读，数据库列： PartyName  
  * 
  */
	public String getPartyname() {
		return partyname;
	}

/**
  * 写，数据库列：PartyName  
  * 
  */
	public void setPartyname(String partyname) {
		this.partyname = partyname;
	}
		
        
  private String partyaddress;
  
/**
  * 读，数据库列： PartyAddress  
  * 
  */
	public String getPartyaddress() {
		return partyaddress;
	}

/**
  * 写，数据库列：PartyAddress  
  * 
  */
	public void setPartyaddress(String partyaddress) {
		this.partyaddress = partyaddress;
	}
		
        
  private String manager;
  
/**
  * 读，数据库列： Manager  
  * 
  */
	public String getManager() {
		return manager;
	}

/**
  * 写，数据库列：Manager  
  * 
  */
	public void setManager(String manager) {
		this.manager = manager;
	}
		
        
  private String contractcode;
  
/**
  * 读，数据库列： ContractCode  
  * 
  */
	public String getContractcode() {
		return contractcode;
	}

/**
  * 写，数据库列：ContractCode  
  * 
  */
	public void setContractcode(String contractcode) {
		this.contractcode = contractcode;
	}
		
        
  private String cooperation;
  
/**
  * 读，数据库列： Cooperation  
  * 
  */
	public String getCooperation() {
		return cooperation;
	}

/**
  * 写，数据库列：Cooperation  
  * 
  */
	public void setCooperation(String cooperation) {
		this.cooperation = cooperation;
	}
		
        
  private String legalassignee;
  
/**
  * 读，数据库列： LegalAssignee  
  * 
  */
	public String getLegalassignee() {
		return legalassignee;
	}

/**
  * 写，数据库列：LegalAssignee  
  * 
  */
	public void setLegalassignee(String legalassignee) {
		this.legalassignee = legalassignee;
	}
		
        
  private int iswithholdingoffsite;
  
/**
  * 读，数据库列： ISWithholdingOffsite  
  * 
  */
	public int getIswithholdingoffsite() {
		return iswithholdingoffsite;
	}

/**
  * 写，数据库列：ISWithholdingOffsite  
  * 
  */
	public void setIswithholdingoffsite(int iswithholdingoffsite) {
		this.iswithholdingoffsite = iswithholdingoffsite;
	}
		
        
  private double managementrate;
  
/**
  * 读，数据库列： ManagementRate  
  * 
  */
	public double getManagementrate() {
		return managementrate;
	}

/**
  * 写，数据库列：ManagementRate  
  * 
  */
	public void setManagementrate(double managementrate) {
		this.managementrate = managementrate;
	}
		
        
  private double taxrate;
  
/**
  * 读，数据库列： TaxRate  
  * 
  */
	public double getTaxrate() {
		return taxrate;
	}

/**
  * 写，数据库列：TaxRate  
  * 
  */
	public void setTaxrate(double taxrate) {
		this.taxrate = taxrate;
	}
		
        
  private double contractamount;
  
/**
  * 读，数据库列： ContractAmount  
  * 
  */
	public double getContractamount() {
		return contractamount;
	}

/**
  * 写，数据库列：ContractAmount  
  * 
  */
	public void setContractamount(double contractamount) {
		this.contractamount = contractamount;
	}
		
        
  private double settlementamount;
  
/**
  * 读，数据库列： SettlementAmount  
  * 
  */
	public double getSettlementamount() {
		return settlementamount;
	}

/**
  * 写，数据库列：SettlementAmount  
  * 
  */
	public void setSettlementamount(double settlementamount) {
		this.settlementamount = settlementamount;
	}
		
        
  private Date dutypaidtime;
  
/**
  * 读，数据库列： DutyPaidTime  
  * 
  */
	public Date getDutypaidtime() {
		return dutypaidtime;
	}

/**
  * 写，数据库列：DutyPaidTime  
  * 
  */
	public void setDutypaidtime(Date dutypaidtime) {
		this.dutypaidtime = dutypaidtime;
	}
		
        
  private double dutypaidamount;
  
/**
  * 读，数据库列： DutyPaidAmount  
  * 
  */
	public double getDutypaidamount() {
		return dutypaidamount;
	}

/**
  * 写，数据库列：DutyPaidAmount  
  * 
  */
	public void setDutypaidamount(double dutypaidamount) {
		this.dutypaidamount = dutypaidamount;
	}
		
        
  private String dutypaidcode;
  
/**
  * 读，数据库列： DutyPaidCode  
  * 
  */
	public String getDutypaidcode() {
		return dutypaidcode;
	}

/**
  * 写，数据库列：DutyPaidCode  
  * 
  */
	public void setDutypaidcode(String dutypaidcode) {
		this.dutypaidcode = dutypaidcode;
	}
		
        
  private double capitaloccupied;
  
/**
  * 读，数据库列： CapitalOccupied  
  * 
  */
	public double getCapitaloccupied() {
		return capitaloccupied;
	}

/**
  * 写，数据库列：CapitalOccupied  
  * 
  */
	public void setCapitaloccupied(double capitaloccupied) {
		this.capitaloccupied = capitaloccupied;
	}
		
        
  private int projectstatus;
  
/**
  * 读，数据库列： ProjectStatus  
  * 
  */
	public int getProjectstatus() {
		return projectstatus;
	}

/**
  * 写，数据库列：ProjectStatus  
  * 
  */
	public void setProjectstatus(int projectstatus) {
		this.projectstatus = projectstatus;
	}
		
        
  private Date trice;
  
/**
  * 读，数据库列： Trice  
  * 
  */
	public Date getTrice() {
		return trice;
	}

/**
  * 写，数据库列：Trice  
  * 
  */
	public void setTrice(Date trice) {
		this.trice = trice;
	}
		
        
  private Date createtime;
  
/**
  * 读，数据库列： CreateTime  
  * 
  */
	public Date getCreatetime() {
		return createtime;
	}

/**
  * 写，数据库列：CreateTime  
  * 
  */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}
		
        
  private String createuser;
  
/**
  * 读，数据库列： CreateUser  
  * 
  */
	public String getCreateuser() {
		return createuser;
	}

/**
  * 写，数据库列：CreateUser  
  * 
  */
	public void setCreateuser(String createuser) {
		this.createuser = createuser;
	}
		
        
  private Date updatetime;
  
/**
  * 读，数据库列： UpdateTime  
  * 
  */
	public Date getUpdatetime() {
		return updatetime;
	}

/**
  * 写，数据库列：UpdateTime  
  * 
  */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}
		
        
  private String updateuser;
  
/**
  * 读，数据库列： UpdateUser  
  * 
  */
	public String getUpdateuser() {
		return updateuser;
	}

/**
  * 写，数据库列：UpdateUser  
  * 
  */
	public void setUpdateuser(String updateuser) {
		this.updateuser = updateuser;
	}
		
        
  private String description;
  
/**
  * 读，数据库列： Description  
  * 
  */
	public String getDescription() {
		return description;
	}

/**
  * 写，数据库列：Description  
  * 
  */
	public void setDescription(String description) {
		this.description = description;
	}
		
        
    @Override
	public String toString() {
		System.out.println(this.getClass().getName() + ".toString():");
        
        String str = Utility.EMPTY_STRING;
        str += MessageFormat.format("\tId=\"{0}\"\n", this.getId());
        str += MessageFormat.format("\tProjectcode=\"{0}\"\n", this.getProjectcode());
        str += MessageFormat.format("\tProjectname=\"{0}\"\n", this.getProjectname());
        str += MessageFormat.format("\tOrganizationid=\"{0}\"\n", this.getOrganizationid());
        str += MessageFormat.format("\tPartyname=\"{0}\"\n", this.getPartyname());
        str += MessageFormat.format("\tPartyaddress=\"{0}\"\n", this.getPartyaddress());
        str += MessageFormat.format("\tManager=\"{0}\"\n", this.getManager());
        str += MessageFormat.format("\tContractcode=\"{0}\"\n", this.getContractcode());
        str += MessageFormat.format("\tCooperation=\"{0}\"\n", this.getCooperation());
        str += MessageFormat.format("\tLegalassignee=\"{0}\"\n", this.getLegalassignee());
        str += MessageFormat.format("\tIswithholdingoffsite=\"{0}\"\n", this.getIswithholdingoffsite());
        str += MessageFormat.format("\tManagementrate=\"{0}\"\n", this.getManagementrate());
        str += MessageFormat.format("\tTaxrate=\"{0}\"\n", this.getTaxrate());
        str += MessageFormat.format("\tContractamount=\"{0}\"\n", this.getContractamount());
        str += MessageFormat.format("\tSettlementamount=\"{0}\"\n", this.getSettlementamount());
        str += MessageFormat.format("\tDutypaidtime=\"{0}\"\n", this.getDutypaidtime());
        str += MessageFormat.format("\tDutypaidamount=\"{0}\"\n", this.getDutypaidamount());
        str += MessageFormat.format("\tDutypaidcode=\"{0}\"\n", this.getDutypaidcode());
        str += MessageFormat.format("\tCapitaloccupied=\"{0}\"\n", this.getCapitaloccupied());
        str += MessageFormat.format("\tProjectstatus=\"{0}\"\n", this.getProjectstatus());
        str += MessageFormat.format("\tTrice=\"{0}\"\n", this.getTrice());
        str += MessageFormat.format("\tCreatetime=\"{0}\"\n", this.getCreatetime());
        str += MessageFormat.format("\tCreateuser=\"{0}\"\n", this.getCreateuser());
        str += MessageFormat.format("\tUpdatetime=\"{0}\"\n", this.getUpdatetime());
        str += MessageFormat.format("\tUpdateuser=\"{0}\"\n", this.getUpdateuser());
        str += MessageFormat.format("\tDescription=\"{0}\"\n", this.getDescription());;
        return str;
                        
	}

}

