/**
  * @ cqiyi create in 2014-12-8 6:26:38 by Template
  * This class generated by Forever Web Rapid Framework Code Generator
  */

package hply.domain;

import java.io.Serializable;
import java.text.MessageFormat;
import java.util.Date;

import org.apache.commons.lang3.StringUtils;

import hply.core.Utility;

import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.format.annotation.DateTimeFormat.ISO;

/**
  * 数据表： [t_project_summary]
  * 00_多项目汇总
  */
public class ProjectSummary implements Serializable {
    
    	/**
	 * 
	 */
	private static final long serialVersionUID = 3452350605025320432L;
		/*
    	 * ID
    	 */
        public static final String FIELD_ID = "id";
    	/*
    	 * 记录流程号
    	 */
        public static final String FIELD_SERIAL_ID = "serial_id";
    	/*
    	 * 时间
    	 */
        public static final String FIELD_TRICE = "trice";
    	/*
    	 * 摘要
    	 */
        public static final String FIELD_DESCRIPTION = "description";
    	/*
    	 * 项目ID
    	 */
        public static final String FIELD_PROJECT_ID = "project_id";
    	/*
    	 * 所在部门
    	 */
        public static final String FIELD_ORGANIZATION_ID = "organization_id";
    	/*
    	 * 项目编号
    	 */
        public static final String FIELD_PROJECT_CODE = "project_code";
    	/*
    	 * 项目名称
    	 */
        public static final String FIELD_PROJECT_NAME = "project_name";
    	/*
    	 * 合同金额
    	 */
        public static final String FIELD_CONTRACT_AMOUNT = "contract_amount";
    	/*
    	 * 合同调增额
    	 */
        public static final String FIELD_CHANGE_AMOUNT = "change_amount";
    	/*
    	 * 累计调增额
    	 */
        public static final String FIELD_CHANGE_TOTAL_AMOUNT = "change_total_amount";
    	/*
    	 * 合同结算额
    	 */
        public static final String FIELD_SETTLEMENT_AMOUNT = "settlement_amount";
    	/*
    	 * 比率
    	 */
        public static final String FIELD_MANAGEMENT_RATE = "management_rate";
    	/*
    	 * 应收管理费
    	 */
        public static final String FIELD_MANAGEMENT_PLAN_AMOUNT = "management_plan_amount";
    	/*
    	 * 实收管理费
    	 */
        public static final String FIELD_MANAGEMENT_REAL_AMOUNT = "management_real_amount";
    	/*
    	 * 累计收管理费
    	 */
        public static final String FIELD_MANAGEMENT_TOTAL_AMOUNT = "management_total_amount";
    	/*
    	 * 尚欠管理费
    	 */
        public static final String FIELD_MANAGEMENT_OWE_AMOUNT = "management_owe_amount";
    	/*
    	 * 发票金额
    	 */
        public static final String FIELD_PARTY_BILLING_AMOUNT = "party_billing_amount";
    	/*
    	 * 累计开票
    	 */
        public static final String FIELD_PARTY_BILLING_TOTAL_AMOUNT = "party_billing_total_amount";
    	/*
    	 * 收款金额
    	 */
        public static final String FIELD_COLLECTIONS_AMOUNT = "collections_amount";
    	/*
    	 * 累计收款
    	 */
        public static final String FIELD_COLLECTIONS_TOTAL_AMOUNT = "collections_total_amount";
    	/*
    	 * 回收率
    	 */
        public static final String FIELD_COLLECTIONS_RATE = "collections_rate";
    	/*
    	 * 发票金额
    	 */
        public static final String FIELD_CUSTOMER_BILLING_AMOUNT = "customer_billing_amount";
    	/*
    	 * 累计开票
    	 */
        public static final String FIELD_CUSTOMER_BILLING_TOTAL_AMOUNT = "customer_billing_total_amount";
    	/*
    	 * 支付金额
    	 */
        public static final String FIELD_PAYMENT_AMOUNT = "payment_amount";
    	/*
    	 * 累计
    	 */
        public static final String FIELD_PAYMENT_TOTAL_AMOUNT = "payment_total_amount";
    	/*
    	 * 比率
    	 */
        public static final String FIELD_TAX_RATE = "tax_rate";
    	/*
    	 * 应缴税金
    	 */
        public static final String FIELD_TAX_PLAN_AMOUNT = "tax_plan_amount";
    	/*
    	 * 已缴税金
    	 */
        public static final String FIELD_TAX_REAL_AMOUNT = "tax_real_amount";
    	/*
    	 * 累计已缴税金
    	 */
        public static final String FIELD_TAX_TOTAL_AMOUNT = "tax_total_amount";
    	/*
    	 * 尚欠税金
    	 */
        public static final String FIELD_TAX_OWE_AMOUNT = "tax_owe_amount";
    	/*
    	 * 金额
    	 */
        public static final String FIELD_ARREARS_AMOUNT = "arrears_amount";
    	/*
    	 * 预计用量
    	 */
        public static final String FIELD_EXPECTED_VALUE = "expected_value";
    	/*
    	 * 型材点
    	 */
        public static final String FIELD_PROFILE_POINT = "profile_point";
    	/*
    	 * 
    	 */
        public static final String FIELD_VERSION = "version";
    	/*
    	 * 创建时间，数据生成时间
    	 */
        public static final String FIELD_CREATE_TIME = "create_time";
    	/*
    	 * 
    	 */
        public static final String FIELD_TABLE_NAME = "table_name";
    	/*
    	 * 预留字段01
    	 */
        public static final String FIELD_FIELD_01 = "field_01";
    	/*
    	 * 预留字段02
    	 */
        public static final String FIELD_FIELD_02 = "field_02";
    	/*
    	 * 预留字段03
    	 */
        public static final String FIELD_FIELD_03 = "field_03";
    	/*
    	 * 预留字段04
    	 */
        public static final String FIELD_FIELD_04 = "field_04";
        /*
         * 预留字段05
         */
        public static final String FIELD_FIELD_05 = "field_05";
        /*
         * 销项税金
         */
        public static final String FIELD_PARTY_BILLING_OUTPUT_TAX_AMOUNT = "party_billing_output_tax_amount";
        /*
         * 进项税金
         */
        public static final String FIELD_CUSTOMER_BILLING_INPUT_TAX_AMOUNT = "customer_billing_input_tax_amount";
        /*
         * 异地税金
         */
        public static final String FIELD_PAYMENT_DIFFERENT_TAX_AMOUNT = "payment_different_tax_amount";
    	/*
    	 * 税负率税金
    	 */
        public static final String FIELD_TAX_BEARING_AMOUNT = "tax_bearing_amount";
        /*
         * 合同税率
         */
        public static final String FIELD_CONTRACT_TAX_RATE = "contract_tax_rate";
    	/*
    	 * 合同分类
    	 */
        public static final String FIELD_CONTRACT_TYPE = "contract_type";
    	/*
    	 * 预计用量(吨)
    	 */
        public static final String FIELD_EXPECTED_VALUE_TON = "expected_value_ton";
    	/*
    	 * 预计用量(平米)
    	 */
        public static final String FIELD_EXPECTED_VALUE_SQUARE_METER = "expected_value_square_meter";
        /*
         * 合同签订日期
         */
        public static final String FIELD_CONTRACT_DATE = "contract_date";
        /*
         * 税负率
         */
        public static final String FIELD_TAX_BEARING_RATE = "tax_bearing_rate";
        /*
         * 当期已收税负率税金
         */
        public static final String FIELD_TAX_BEARING_RATE_REAL_AMOUNT = "tax_bearing_real_amount";
        /*
         * 累计已收税负率税金
         */
        public static final String FIELD_TAX_BEARING_RATE_TOTAL_REAL_AMOUNT = "tax_bearing_total_real_amount";
    	/*
    	 * 增值税及附加系数
    	 */
        public static final String FIELD_VAT_ADDITIONAL_COEFFICIENT = "vat_additional_coefficient";
    	/*
    	 * 工程款合计
    	 */
        public static final String FIELD_COLLECTIONS_TOTAL_PROJECT_AMOUNT = "collections_total_project_amount";
    	/*
    	 * 自入款合计
    	 */
        public static final String FIELD_COLLECTIONS_TOTAL_INCOME_AMOUNT = "collections_total_income_amount";
        /*
         * 其他合计
         */
        public static final String FIELD_COLLECTIONS_TOTAL_OTHER_AMOUNT = "collections_total_other_amount";
    	/*
    	 * 累计异地已缴税金
    	 */
        public static final String FIELD_PAYMENT_TOTAL_DIFFERENT_TAX_AMOUNT = "payment_total_different_tax_amount";
        
	/*
	 * 默认构造函数
	 */
	public ProjectSummary() {
		this.id = Utility.getRandomUUID(); 
        this.trice = new Date(); 
        this.version = -1; 
        this.createTime = new Date(); 
	}

    /**
      * [id]，
      * ID
      */
      
      private String id;
      
    /**
      * [serial_id]，
      * 记录流程号
      */
      
      private Integer serialId;
      
    /**
      * [trice]，
      * 时间
      */
      @DateTimeFormat(iso=ISO.DATE)
      private Date trice;
      
    /**
      * [description]，
      * 摘要
      */
      
      private String description;
      
    /**
      * [project_id]，
      * 项目ID
      */
      
      private String projectId;
      
    /**
      * [organization_id]，
      * 所在部门
      */
      
      private String organizationId;
      
    /**
      * [project_code]，
      * 项目编号
      */
      
      private String projectCode;
      
    /**
      * [project_name]，
      * 项目名称
      */
      
      private String projectName;
      
    /**
      * [contract_amount]，
      * 合同金额
      */
      
      private double contractAmount;
      
    /**
      * [change_amount]，
      * 合同调增额
      */
      
      private double changeAmount;
      
    /**
      * [change_total_amount]，
      * 累计调增额
      */
      
      private double changeTotalAmount;
      
    /**
      * [settlement_amount]，
      * 合同结算额
      */
      
      private double settlementAmount;
      
    /**
      * [management_rate]，
      * 比率
      */
      
      private double managementRate;
      
    /**
      * [management_plan_amount]，
      * 应收管理费
      */
      
      private double managementPlanAmount;
      
    /**
      * [management_real_amount]，
      * 实收管理费
      */
      
      private double managementRealAmount;
      
    /**
      * [management_total_amount]，
      * 累计收管理费
      */
      
      private double managementTotalAmount;
      
    /**
      * [management_owe_amount]，
      * 尚欠管理费
      */
      
      private double managementOweAmount;
      
    /**
      * [party_billing_amount]，
      * 发票金额
      */
      
      private double partyBillingAmount;
      
    /**
      * [party_billing_total_amount]，
      * 累计开票
      */
      
      private double partyBillingTotalAmount;
      
    /**
      * [collections_amount]，
      * 收款金额
      */
      
      private double collectionsAmount;
      
    /**
      * [collections_total_amount]，
      * 累计收款
      */
      
      private double collectionsTotalAmount;
      
    /**
      * [collections_rate]，
      * 回收率
      */
      
      private double collectionsRate;
      
    /**
      * [customer_billing_amount]，
      * 发票金额
      */
      
      private double customerBillingAmount;
      
    /**
      * [customer_billing_total_amount]，
      * 累计开票
      */
      
      private double customerBillingTotalAmount;
      
    /**
      * [payment_amount]，
      * 支付金额
      */
      
      private double paymentAmount;
      
    /**
      * [payment_total_amount]，
      * 累计
      */
      
      private double paymentTotalAmount;
      
    /**
      * [tax_rate]，
      * 比率
      */
      
      private double taxRate;
      
    /**
      * [tax_plan_amount]，
      * 应缴税金
      */
      
      private double taxPlanAmount;
      
    /**
      * [tax_real_amount]，
      * 已缴税金
      */
      
      private double taxRealAmount;
      
    /**
      * [tax_total_amount]，
      * 累计已缴税金
      */
      
      private double taxTotalAmount;
      
    /**
      * [tax_owe_amount]，
      * 尚欠税金
      */
      
      private double taxOweAmount;
      
    /**
      * [arrears_amount]，
      * 金额
      */
      
      private double arrearsAmount;
      
    /**
      * [expected_value]，
      * 预计用量
      */
      
      private double expectedValue;
      
    /**
      * [profile_point]，
      * 型材点
      */
      
      private String profilePoint;
      
    /**
      * [version]，
      * 
      */
      
      private Integer version;
      
    /**
      * [create_time]，
      * 创建时间，数据生成时间
      */
      @DateTimeFormat(iso=ISO.DATE)
      private Date createTime;
      
    /**
      * [table_name]，
      * 
      */
      
      private String tableName;
      
    /**
      * [field_01]，
      * 预留字段01
      */
      
      private String field01;
      
    /**
      * [field_02]，
      * 预留字段02
      */
      
      private String field02;
      
    /**
      * [field_03]，
      * 预留字段03
      */
      
      private String field03;
      
    /**
      * [field_04]，
      * 预留字段04
      */
      
      private String field04;
      
    /**
      * [field_05]，
      * 预留字段05
      */
      
      private String field05;
      
    /**
      * [party_billing_output_tax_amount]，
      * 销项税金
      */
      
      private double partyBillingOutputTaxAmount;
      
    /**
      * [customer_billing_input_tax_amount]，
      * 进项税金
      */
      
      private double customerBillingInputTaxAmount;
      
    /**
      * [payment_different_tax_amount]，
      * 异地税金
      */
      
      private double paymentDifferentTaxAmount;
      
    /**
      * [tax_bearing_amount]，
      * 税负率税金
      */
      
      private double taxBearingAmount;
      
      
    /**
      * [contract_tax_rate]，
      * 合同税率
      */
      
      private String contractTaxRate;
      
    /**
      * [contract_type]，
      * 合同分类
      */
      
      private String contractType;
      
    /**
      * [expected_value_ton]，
      * 预计用量(吨)
      */
      
      private double expectedValueTon;
      
    /**
      * [expected_value_square_meter]，
      * 预计用量(平米)
      */
      
      private double expectedValueSquareMeter;

      
      /**
        * [contract_date]，
        * 合同签订日期
        */
        @DateTimeFormat(iso=ISO.DATE)
        private Date contractDate;
        
      /**
        * [tax_bearing_rate]，
        * 税负率
        */
        
        private double taxBearingRate;
        
      /**
        * [tax_bearing_real_amount]，
        * 当期已收税负率税金
        */
        
        private double taxBearingRealAmount;
        
      /**
        * [tax_bearing_total_real_amount]，
        * 累计已收税负率税金
        */
        
        private double taxBearingTotalRealAmount;
     
    /**
      * [vat_additional_coefficient]，
      * 增值税及附加系数
      */
      
      private double vatAdditionalCoefficient;
      
    /**
      * [collections_total_project_amount]，
      * 工程款合计
      */
      
      private double collectionsTotalProjectAmount;
      
    /**
      * [collections_total_income_amount]，
      * 自入款合计
      */
      
      private double collectionsTotalIncomeAmount;
      
    /**
      * [collections_total_other_amount]，
      * 其他合计
      */
      
      private double collectionsTotalOtherAmount;
      
    /**
      * [payment_total_different_tax_amount]，
      * 累计异地已缴税金
      */
      
      private double paymentTotalDifferentTaxAmount;
    
    /**
      * [id] getter，
      * ID
      */
    	public String getId () {
    		return this.id;
    	}

    /**
      * [id] setter，
      * ID
      */
    	public void setId(String id) {
    		this.id = id;
    	}
    /**
      * [serial_id] getter，
      * 记录流程号
      */
    	public Integer getSerialId () {
    		return this.serialId;
    	}

    /**
      * [serial_id] setter，
      * 记录流程号
      */
    	public void setSerialId(Integer serialId) {
    		this.serialId = serialId;
    	}
    /**
      * [trice] getter，
      * 时间
      */
    	public Date getTrice () {
    		return this.trice;
    	}

    /**
      * [trice] setter，
      * 时间
      */
    	public void setTrice(Date trice) {
    		this.trice = trice;
    	}
    /**
      * [description] getter，
      * 摘要
      */
    	public String getDescription () {
    		return this.description;
    	}

    /**
      * [description] setter，
      * 摘要
      */
    	public void setDescription(String description) {
    		this.description = description;
    	}
    /**
      * [project_id] getter，
      * 项目ID
      */
    	public String getProjectId () {
    		return this.projectId;
    	}

    /**
      * [project_id] setter，
      * 项目ID
      */
    	public void setProjectId(String projectId) {
    		this.projectId = projectId;
    	}
    /**
      * [organization_id] getter，
      * 所在部门
      */
    	public String getOrganizationId () {
    		return this.organizationId;
    	}

    /**
      * [organization_id] setter，
      * 所在部门
      */
    	public void setOrganizationId(String organizationId) {
    		this.organizationId = organizationId;
    	}
    /**
      * [project_code] getter，
      * 项目编号
      */
    	public String getProjectCode () {
    		return this.projectCode;
    	}

    /**
      * [project_code] setter，
      * 项目编号
      */
    	public void setProjectCode(String projectCode) {
    		this.projectCode = projectCode;
    	}
    /**
      * [project_name] getter，
      * 项目名称
      */
    	public String getProjectName () {
    		return this.projectName;
    	}

    /**
      * [project_name] setter，
      * 项目名称
      */
    	public void setProjectName(String projectName) {
    		this.projectName = projectName;
    	}
    /**
      * [contract_amount] getter，
      * 合同金额
      */
    	public double getContractAmount () {
    		return this.contractAmount;
    	}

    /**
      * [contract_amount] setter，
      * 合同金额
      */
    	public void setContractAmount(double contractAmount) {
    		this.contractAmount = contractAmount;
    	}
    /**
      * [change_amount] getter，
      * 合同调增额
      */
    	public double getChangeAmount () {
    		return this.changeAmount;
    	}

    /**
      * [change_amount] setter，
      * 合同调增额
      */
    	public void setChangeAmount(double changeAmount) {
    		this.changeAmount = changeAmount;
    	}
    /**
      * [change_total_amount] getter，
      * 累计调增额
      */
    	public double getChangeTotalAmount () {
    		return this.changeTotalAmount;
    	}

    /**
      * [change_total_amount] setter，
      * 累计调增额
      */
    	public void setChangeTotalAmount(double changeTotalAmount) {
    		this.changeTotalAmount = changeTotalAmount;
    	}
    /**
      * [settlement_amount] getter，
      * 合同结算额
      */
    	public double getSettlementAmount () {
    		return this.settlementAmount;
    	}

    /**
      * [settlement_amount] setter，
      * 合同结算额
      */
    	public void setSettlementAmount(double settlementAmount) {
    		this.settlementAmount = settlementAmount;
    	}
    /**
      * [management_rate] getter，
      * 比率
      */
    	public double getManagementRate () {
    		return this.managementRate;
    	}

    /**
      * [management_rate] setter，
      * 比率
      */
    	public void setManagementRate(double managementRate) {
    		this.managementRate = managementRate;
    	}
    /**
      * [management_plan_amount] getter，
      * 应收管理费
      */
    	public double getManagementPlanAmount () {
    		return this.managementPlanAmount;
    	}

    /**
      * [management_plan_amount] setter，
      * 应收管理费
      */
    	public void setManagementPlanAmount(double managementPlanAmount) {
    		this.managementPlanAmount = managementPlanAmount;
    	}
    /**
      * [management_real_amount] getter，
      * 实收管理费
      */
    	public double getManagementRealAmount () {
    		return this.managementRealAmount;
    	}

    /**
      * [management_real_amount] setter，
      * 实收管理费
      */
    	public void setManagementRealAmount(double managementRealAmount) {
    		this.managementRealAmount = managementRealAmount;
    	}
    /**
      * [management_total_amount] getter，
      * 累计收管理费
      */
    	public double getManagementTotalAmount () {
    		return this.managementTotalAmount;
    	}

    /**
      * [management_total_amount] setter，
      * 累计收管理费
      */
    	public void setManagementTotalAmount(double managementTotalAmount) {
    		this.managementTotalAmount = managementTotalAmount;
    	}
    /**
      * [management_owe_amount] getter，
      * 尚欠管理费
      */
    	public double getManagementOweAmount () {
    		return this.managementOweAmount;
    	}

    /**
      * [management_owe_amount] setter，
      * 尚欠管理费
      */
    	public void setManagementOweAmount(double managementOweAmount) {
    		this.managementOweAmount = managementOweAmount;
    	}
    /**
      * [party_billing_amount] getter，
      * 发票金额
      */
    	public double getPartyBillingAmount () {
    		return this.partyBillingAmount;
    	}

    /**
      * [party_billing_amount] setter，
      * 发票金额
      */
    	public void setPartyBillingAmount(double partyBillingAmount) {
    		this.partyBillingAmount = partyBillingAmount;
    	}
    /**
      * [party_billing_total_amount] getter，
      * 累计开票
      */
    	public double getPartyBillingTotalAmount () {
    		return this.partyBillingTotalAmount;
    	}

    /**
      * [party_billing_total_amount] setter，
      * 累计开票
      */
    	public void setPartyBillingTotalAmount(double partyBillingTotalAmount) {
    		this.partyBillingTotalAmount = partyBillingTotalAmount;
    	}
    /**
      * [collections_amount] getter，
      * 收款金额
      */
    	public double getCollectionsAmount () {
    		return this.collectionsAmount;
    	}

    /**
      * [collections_amount] setter，
      * 收款金额
      */
    	public void setCollectionsAmount(double collectionsAmount) {
    		this.collectionsAmount = collectionsAmount;
    	}
    /**
      * [collections_total_amount] getter，
      * 累计收款
      */
    	public double getCollectionsTotalAmount () {
    		return this.collectionsTotalAmount;
    	}

    /**
      * [collections_total_amount] setter，
      * 累计收款
      */
    	public void setCollectionsTotalAmount(double collectionsTotalAmount) {
    		this.collectionsTotalAmount = collectionsTotalAmount;
    	}
    /**
      * [collections_rate] getter，
      * 回收率
      */
    	public double getCollectionsRate () {
    		return this.collectionsRate;
    	}

    /**
      * [collections_rate] setter，
      * 回收率
      */
    	public void setCollectionsRate(double collectionsRate) {
    		this.collectionsRate = collectionsRate;
    	}
    /**
      * [customer_billing_amount] getter，
      * 发票金额
      */
    	public double getCustomerBillingAmount () {
    		return this.customerBillingAmount;
    	}

    /**
      * [customer_billing_amount] setter，
      * 发票金额
      */
    	public void setCustomerBillingAmount(double customerBillingAmount) {
    		this.customerBillingAmount = customerBillingAmount;
    	}
    /**
      * [customer_billing_total_amount] getter，
      * 累计开票
      */
    	public double getCustomerBillingTotalAmount () {
    		return this.customerBillingTotalAmount;
    	}

    /**
      * [customer_billing_total_amount] setter，
      * 累计开票
      */
    	public void setCustomerBillingTotalAmount(double customerBillingTotalAmount) {
    		this.customerBillingTotalAmount = customerBillingTotalAmount;
    	}
    /**
      * [payment_amount] getter，
      * 支付金额
      */
    	public double getPaymentAmount () {
    		return this.paymentAmount;
    	}

    /**
      * [payment_amount] setter，
      * 支付金额
      */
    	public void setPaymentAmount(double paymentAmount) {
    		this.paymentAmount = paymentAmount;
    	}
    /**
      * [payment_total_amount] getter，
      * 累计
      */
    	public double getPaymentTotalAmount () {
    		return this.paymentTotalAmount;
    	}

    /**
      * [payment_total_amount] setter，
      * 累计
      */
    	public void setPaymentTotalAmount(double paymentTotalAmount) {
    		this.paymentTotalAmount = paymentTotalAmount;
    	}
    /**
      * [tax_rate] getter，
      * 比率
      */
    	public double getTaxRate () {
    		return this.taxRate;
    	}

    /**
      * [tax_rate] setter，
      * 比率
      */
    	public void setTaxRate(double taxRate) {
    		this.taxRate = taxRate;
    	}
    /**
      * [tax_plan_amount] getter，
      * 应缴税金
      */
    	public double getTaxPlanAmount () {
    		return this.taxPlanAmount;
    	}

    /**
      * [tax_plan_amount] setter，
      * 应缴税金
      */
    	public void setTaxPlanAmount(double taxPlanAmount) {
    		this.taxPlanAmount = taxPlanAmount;
    	}
    /**
      * [tax_real_amount] getter，
      * 已缴税金
      */
    	public double getTaxRealAmount () {
    		return this.taxRealAmount;
    	}

    /**
      * [tax_real_amount] setter，
      * 已缴税金
      */
    	public void setTaxRealAmount(double taxRealAmount) {
    		this.taxRealAmount = taxRealAmount;
    	}
    /**
      * [tax_total_amount] getter，
      * 累计已缴税金
      */
    	public double getTaxTotalAmount () {
    		return this.taxTotalAmount;
    	}

    /**
      * [tax_total_amount] setter，
      * 累计已缴税金
      */
    	public void setTaxTotalAmount(double taxTotalAmount) {
    		this.taxTotalAmount = taxTotalAmount;
    	}
    /**
      * [tax_owe_amount] getter，
      * 尚欠税金
      */
    	public double getTaxOweAmount () {
    		return this.taxOweAmount;
    	}

    /**
      * [tax_owe_amount] setter，
      * 尚欠税金
      */
    	public void setTaxOweAmount(double taxOweAmount) {
    		this.taxOweAmount = taxOweAmount;
    	}
    /**
      * [arrears_amount] getter，
      * 金额
      */
    	public double getArrearsAmount () {
    		return this.arrearsAmount;
    	}

    /**
      * [arrears_amount] setter，
      * 金额
      */
    	public void setArrearsAmount(double arrearsAmount) {
    		this.arrearsAmount = arrearsAmount;
    	}
    /**
      * [expected_value] getter，
      * 预计用量
      */
    	public double getExpectedValue () {
    		return this.expectedValue;
    	}

    /**
      * [expected_value] setter，
      * 预计用量
      */
    	public void setExpectedValue(double expectedValue) {
    		this.expectedValue = expectedValue;
    	}
    /**
      * [profile_point] getter，
      * 型材点
      */
    	public String getProfilePoint () {
    		return this.profilePoint;
    	}

    /**
      * [profile_point] setter，
      * 型材点
      */
    	public void setProfilePoint(String profilePoint) {
    		this.profilePoint = profilePoint;
    	}
    /**
      * [version] getter，
      * 
      */
    	public Integer getVersion () {
    		return this.version;
    	}

    /**
      * [version] setter，
      * 
      */
    	public void setVersion(Integer version) {
    		this.version = version;
    	}
    /**
      * [create_time] getter，
      * 创建时间，数据生成时间
      */
    	public Date getCreateTime () {
    		return this.createTime;
    	}

    /**
      * [create_time] setter，
      * 创建时间，数据生成时间
      */
    	public void setCreateTime(Date createTime) {
    		this.createTime = createTime;
    	}
    /**
      * [table_name] getter，
      * 
      */
    	public String getTableName () {
    		return this.tableName;
    	}

    /**
      * [table_name] setter，
      * 
      */
    	public void setTableName(String tableName) {
    		this.tableName = tableName;
    	}
    /**
      * [field_01] getter，
      * 预留字段01
      */
    	public String getField01 () {
    		return this.field01;
    	}

    /**
      * [field_01] setter，
      * 预留字段01
      */
    	public void setField01(String field01) {
    		this.field01 = field01;
    	}
    /**
      * [field_02] getter，
      * 预留字段02
      */
    	public String getField02 () {
    		return this.field02;
    	}

    /**
      * [field_02] setter，
      * 预留字段02
      */
    	public void setField02(String field02) {
    		this.field02 = field02;
    	}
    /**
      * [field_03] getter，
      * 预留字段03
      */
    	public String getField03 () {
    		return this.field03;
    	}

    /**
      * [field_03] setter，
      * 预留字段03
      */
    	public void setField03(String field03) {
    		this.field03 = field03;
    	}
    /**
      * [field_04] getter，
      * 预留字段04
      */
    	public String getField04 () {
    		return this.field04;
    	}

    /**
      * [field_04] setter，
      * 预留字段04
      */
    	public void setField04(String field04) {
    		this.field04 = field04;
    	}
    /**
      * [field_05] getter，
      * 预留字段05
      */
    	public String getField05 () {
    		return this.field05;
    	}

    /**
      * [field_05] setter，
      * 预留字段05
      */
    	public void setField05(String field05) {
    		this.field05 = field05;
    	}
    
    	
    	
	public double getPartyBillingOutputTaxAmount() {
		return partyBillingOutputTaxAmount;
	}

	public void setPartyBillingOutputTaxAmount(double partyBillingOutputTaxAmount) {
		this.partyBillingOutputTaxAmount = partyBillingOutputTaxAmount;
	}

	public double getCustomerBillingInputTaxAmount() {
		return customerBillingInputTaxAmount;
	}

	public void setCustomerBillingInputTaxAmount(
			double customerBillingInputTaxAmount) {
		this.customerBillingInputTaxAmount = customerBillingInputTaxAmount;
	}

	public double getPaymentDifferentTaxAmount() {
		return paymentDifferentTaxAmount;
	}

	public void setPaymentDifferentTaxAmount(double paymentDifferentTaxAmount) {
		this.paymentDifferentTaxAmount = paymentDifferentTaxAmount;
	}

	public double getTaxBearingAmount() {
		return taxBearingAmount;
	}

	public void setTaxBearingAmount(double taxBearingAmount) {
		this.taxBearingAmount = taxBearingAmount;
	}
	
	public String getContractTaxRate() {
		return contractTaxRate;
	}

	public void setContractTaxRate(String contractTaxRate) {
		this.contractTaxRate = contractTaxRate;
	}

	public String getContractType() {
		return contractType;
	}

	public void setContractType(String contractType) {
		this.contractType = contractType;
	}

	public double getExpectedValueTon() {
		return expectedValueTon;
	}

	public void setExpectedValueTon(double expectedValueTon) {
		this.expectedValueTon = expectedValueTon;
	}

	public double getExpectedValueSquareMeter() {
		return expectedValueSquareMeter;
	}

	public void setExpectedValueSquareMeter(double expectedValueSquareMeter) {
		this.expectedValueSquareMeter = expectedValueSquareMeter;
	}

	public Date getContractDate() {
		return contractDate;
	}

	public void setContractDate(Date contractDate) {
		this.contractDate = contractDate;
	}

	public double getTaxBearingRate() {
		return taxBearingRate;
	}

	public void setTaxBearingRate(double taxBearingRate) {
		this.taxBearingRate = taxBearingRate;
	}

	public double getVatAdditionalCoefficient() {
		return vatAdditionalCoefficient;
	}

	public void setVatAdditionalCoefficient(double vatAdditionalCoefficient) {
		this.vatAdditionalCoefficient = vatAdditionalCoefficient;
	}
	
	public double getTaxBearingRealAmount() {
		return taxBearingRealAmount;
	}

	public void setTaxBearingRealAmount(double taxBearingRealAmount) {
		this.taxBearingRealAmount = taxBearingRealAmount;
	}

	public double getTaxBearingTotalRealAmount() {
		return taxBearingTotalRealAmount;
	}

	public void setTaxBearingTotalRealAmount(
			double taxBearingTotalRealAmount) {
		this.taxBearingTotalRealAmount = taxBearingTotalRealAmount;
	}

	public double getCollectionsTotalProjectAmount() {
		return collectionsTotalProjectAmount;
	}

	public void setCollectionsTotalProjectAmount(
			double collectionsTotalProjectAmount) {
		this.collectionsTotalProjectAmount = collectionsTotalProjectAmount;
	}

	public double getCollectionsTotalIncomeAmount() {
		return collectionsTotalIncomeAmount;
	}

	public void setCollectionsTotalIncomeAmount(double collectionsTotalIncomeAmount) {
		this.collectionsTotalIncomeAmount = collectionsTotalIncomeAmount;
	}

	public double getCollectionsTotalOtherAmount() {
		return collectionsTotalOtherAmount;
	}

	public void setCollectionsTotalOtherAmount(double collectionsTotalOtherAmount) {
		this.collectionsTotalOtherAmount = collectionsTotalOtherAmount;
	}

	public double getPaymentTotalDifferentTaxAmount() {
		return paymentTotalDifferentTaxAmount;
	}

	public void setPaymentTotalDifferentTaxAmount(
			double paymentTotalDifferentTaxAmount) {
		this.paymentTotalDifferentTaxAmount = paymentTotalDifferentTaxAmount;
	}

	@Override
	public String toString() {
		System.out.println(this.getClass().getName() + ".toString():");
        
        String str = StringUtils.EMPTY;
        str += MessageFormat.format("Id=\"{0}\",", StringUtils.trimToEmpty(this.getId()));
        str += MessageFormat.format("SerialId=\"{0}\",", this.getSerialId());
        str += MessageFormat.format("Trice=\"{0}\",", this.getTrice());
        str += MessageFormat.format("Description=\"{0}\",", StringUtils.trimToEmpty(this.getDescription()));
        str += MessageFormat.format("ProjectId=\"{0}\",", StringUtils.trimToEmpty(this.getProjectId()));
        str += MessageFormat.format("OrganizationId=\"{0}\",", StringUtils.trimToEmpty(this.getOrganizationId()));
        str += MessageFormat.format("ProjectCode=\"{0}\",", StringUtils.trimToEmpty(this.getProjectCode()));
        str += MessageFormat.format("ProjectName=\"{0}\",", StringUtils.trimToEmpty(this.getProjectName()));
        str += MessageFormat.format("ContractAmount=\"{0}\",", this.getContractAmount());
        str += MessageFormat.format("ChangeAmount=\"{0}\",", this.getChangeAmount());
        str += MessageFormat.format("ChangeTotalAmount=\"{0}\",", this.getChangeTotalAmount());
        str += MessageFormat.format("SettlementAmount=\"{0}\",", this.getSettlementAmount());
        str += MessageFormat.format("ManagementRate=\"{0}\",", this.getManagementRate());
        str += MessageFormat.format("ManagementPlanAmount=\"{0}\",", this.getManagementPlanAmount());
        str += MessageFormat.format("ManagementRealAmount=\"{0}\",", this.getManagementRealAmount());
        str += MessageFormat.format("ManagementTotalAmount=\"{0}\",", this.getManagementTotalAmount());
        str += MessageFormat.format("ManagementOweAmount=\"{0}\",", this.getManagementOweAmount());
        str += MessageFormat.format("PartyBillingAmount=\"{0}\",", this.getPartyBillingAmount());
        str += MessageFormat.format("PartyBillingTotalAmount=\"{0}\",", this.getPartyBillingTotalAmount());
        str += MessageFormat.format("CollectionsAmount=\"{0}\",", this.getCollectionsAmount());
        str += MessageFormat.format("CollectionsTotalAmount=\"{0}\",", this.getCollectionsTotalAmount());
        str += MessageFormat.format("CollectionsRate=\"{0}\",", this.getCollectionsRate());
        str += MessageFormat.format("CustomerBillingAmount=\"{0}\",", this.getCustomerBillingAmount());
        str += MessageFormat.format("CustomerBillingTotalAmount=\"{0}\",", this.getCustomerBillingTotalAmount());
        str += MessageFormat.format("PaymentAmount=\"{0}\",", this.getPaymentAmount());
        str += MessageFormat.format("PaymentTotalAmount=\"{0}\",", this.getPaymentTotalAmount());
        str += MessageFormat.format("TaxRate=\"{0}\",", this.getTaxRate());
        str += MessageFormat.format("TaxPlanAmount=\"{0}\",", this.getTaxPlanAmount());
        str += MessageFormat.format("TaxRealAmount=\"{0}\",", this.getTaxRealAmount());
        str += MessageFormat.format("TaxTotalAmount=\"{0}\",", this.getTaxTotalAmount());
        str += MessageFormat.format("TaxOweAmount=\"{0}\",", this.getTaxOweAmount());
        str += MessageFormat.format("ArrearsAmount=\"{0}\",", this.getArrearsAmount());
        str += MessageFormat.format("ExpectedValue=\"{0}\",", this.getExpectedValue());
        str += MessageFormat.format("ProfilePoint=\"{0}\",", StringUtils.trimToEmpty(this.getProfilePoint()));
        str += MessageFormat.format("Version=\"{0}\",", this.getVersion());
        str += MessageFormat.format("CreateTime=\"{0}\",", this.getCreateTime());
        str += MessageFormat.format("TableName=\"{0}\",", StringUtils.trimToEmpty(this.getTableName()));
        str += MessageFormat.format("Field01=\"{0}\",", StringUtils.trimToEmpty(this.getField01()));
        str += MessageFormat.format("Field02=\"{0}\",", StringUtils.trimToEmpty(this.getField02()));
        str += MessageFormat.format("Field03=\"{0}\",", StringUtils.trimToEmpty(this.getField03()));
        str += MessageFormat.format("Field04=\"{0}\",", StringUtils.trimToEmpty(this.getField04()));
        str += MessageFormat.format("Field05=\"{0}\",", StringUtils.trimToEmpty(this.getField05()));
        str += MessageFormat.format("PartyBillingOutputTaxAmount=\"{0}\",", this.getPartyBillingOutputTaxAmount());
        str += MessageFormat.format("CustomerBillingInputTaxAmount=\"{0}\",", this.getCustomerBillingInputTaxAmount());
        str += MessageFormat.format("PaymentDifferentTaxAmount=\"{0}\",", this.getPaymentDifferentTaxAmount());
        str += MessageFormat.format("TaxBearingAmount=\"{0}\",", this.getTaxBearingAmount());
        str += MessageFormat.format("ContractTaxRate=\"{0}\",", StringUtils.trimToEmpty(this.getContractTaxRate()));
        str += MessageFormat.format("ContractType=\"{0}\",", StringUtils.trimToEmpty(this.getContractType()));
        str += MessageFormat.format("ExpectedValueTon=\"{0}\",", this.getExpectedValueTon());
        str += MessageFormat.format("ExpectedValueSquareMeter=\"{0}\",", this.getExpectedValueSquareMeter());
        str += MessageFormat.format("ContractDate=\"{0}\",", this.getContractDate());
        str += MessageFormat.format("TaxBearingRate=\"{0}\",", this.getTaxBearingRate());
        str += MessageFormat.format("TaxBearingRealAmount=\"{0}\",", this.getTaxBearingRealAmount());
        str += MessageFormat.format("TaxBearingTotalRealAmount=\"{0}\",", this.getTaxBearingTotalRealAmount());
        str += MessageFormat.format("VatAdditionalCoefficient=\"{0}\",", this.getVatAdditionalCoefficient());
        str += MessageFormat.format("CollectionsTotalProjectAmount=\"{0}\",", this.getCollectionsTotalProjectAmount());
        str += MessageFormat.format("CollectionsTotalIncomeAmount=\"{0}\",", this.getCollectionsTotalIncomeAmount());
        str += MessageFormat.format("CollectionsTotalOtherAmount=\"{0}\",", this.getCollectionsTotalOtherAmount());
        str += MessageFormat.format("PaymentTotalDifferentTaxAmount=\"{0}\",", this.getPaymentTotalDifferentTaxAmount());
        return str;
                        
	}
}

