/**
  * @ ChengQiyi create in 2014/7/6 21:37:41 by Template at 2014年6月25日21:26:55
  * This class generated by CodeSmith Generator
  */

package hply.domain;

import java.io.Serializable;
import java.util.Date;
import java.text.MessageFormat;
import hply.common.Utility;


/**
  * 模型类，对应的数据库表： [t_sys_parameter]
  * 
  */
public class SysParameter implements Serializable {
        
  /**
	 * 
	 */
	private static final long serialVersionUID = 1054042896309793685L;
private String id;
  
/**
  * 读，数据库列：id  
  * 
  */
	public String getId() {
		return id;
	}

/**
  * 写，数据库列：id  
  * 
  */
	public void setId(String id) {
		this.id = id;
	}
		
        
  private String enName;
  
/**
  * 读，数据库列：en_name  
  * 
  */
	public String getEnName() {
		return enName;
	}

/**
  * 写，数据库列：en_name  
  * 
  */
	public void setEnName(String enName) {
		this.enName = enName;
	}
		
        
  private String cnName;
  
/**
  * 读，数据库列：cn_name  
  * 
  */
	public String getCnName() {
		return cnName;
	}

/**
  * 写，数据库列：cn_name  
  * 
  */
	public void setCnName(String cnName) {
		this.cnName = cnName;
	}
		
        
  private String paramValue;
  
/**
  * 读，数据库列：param_value  
  * 
  */
	public String getParamValue() {
		return paramValue;
	}

/**
  * 写，数据库列：param_value  
  * 
  */
	public void setParamValue(String paramValue) {
		this.paramValue = paramValue;
	}
		
        
  private String defaultValue;
  
/**
  * 读，数据库列：default_value  
  * 
  */
	public String getDefaultValue() {
		return defaultValue;
	}

/**
  * 写，数据库列：default_value  
  * 
  */
	public void setDefaultValue(String defaultValue) {
		this.defaultValue = defaultValue;
	}
		
        
  private int isInner;
  
/**
  * 读，数据库列：is_inner  
  * 
  */
	public int getIsInner() {
		return isInner;
	}

/**
  * 写，数据库列：is_inner  
  * 
  */
	public void setIsInner(int isInner) {
		this.isInner = isInner;
	}
		
        
  private Date createTime;
  
/**
  * 读，数据库列：create_time  
  * 
  */
	public Date getCreateTime() {
		return createTime;
	}

/**
  * 写，数据库列：create_time  
  * 
  */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
		
        
  private String createUser;
  
/**
  * 读，数据库列：create_user  
  * 
  */
	public String getCreateUser() {
		return createUser;
	}

/**
  * 写，数据库列：create_user  
  * 
  */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}
		
        
  private Date updateTime;
  
/**
  * 读，数据库列：update_time  
  * 
  */
	public Date getUpdateTime() {
		return updateTime;
	}

/**
  * 写，数据库列：update_time  
  * 
  */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
		
        
  private String updateUser;
  
/**
  * 读，数据库列：update_user  
  * 
  */
	public String getUpdateUser() {
		return updateUser;
	}

/**
  * 写，数据库列：update_user  
  * 
  */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}
		
        
  private String description;
  
/**
  * 读，数据库列：description  
  * 
  */
	public String getDescription() {
		return description;
	}

/**
  * 写，数据库列：description  
  * 
  */
	public void setDescription(String description) {
		this.description = description;
	}
		
        
    @Override
	public String toString() {
		System.out.println(this.getClass().getName() + ".toString():");
        
        String str = Utility.EMPTY_STRING;
        str += MessageFormat.format("\tId=\"{0}\"\n", this.getId());
        str += MessageFormat.format("\tEnName=\"{0}\"\n", this.getEnName());
        str += MessageFormat.format("\tCnName=\"{0}\"\n", this.getCnName());
        str += MessageFormat.format("\tParamValue=\"{0}\"\n", this.getParamValue());
        str += MessageFormat.format("\tDefaultValue=\"{0}\"\n", this.getDefaultValue());
        str += MessageFormat.format("\tIsInner=\"{0}\"\n", this.getIsInner());
        str += MessageFormat.format("\tCreateTime=\"{0}\"\n", this.getCreateTime());
        str += MessageFormat.format("\tCreateUser=\"{0}\"\n", this.getCreateUser());
        str += MessageFormat.format("\tUpdateTime=\"{0}\"\n", this.getUpdateTime());
        str += MessageFormat.format("\tUpdateUser=\"{0}\"\n", this.getUpdateUser());
        str += MessageFormat.format("\tDescription=\"{0}\"\n", this.getDescription());;
        return str;
                        
	}
    
//======================================================================================
// TODO: 附加的其他方法 （ hply.domain.SysParameter ）
//======================================================================================


}

