/**
 * @ cqiyi create in 2014/7/24 20:49:20 by Template
 * This class generated by Forever Web Rapid Framework Code Generator
 */

package hply.domain;

import hply.Utility;

import java.io.Serializable;
import java.text.MessageFormat;

import javax.validation.constraints.NotNull;

import org.apache.commons.lang3.StringUtils;

/**
 * 数据表： [t_sys_resource]
 * 
 */
public class SysResource implements Serializable {

	/*
	 * 默认构造函数
	 */
	public SysResource() {
		this.id = Utility.getRandomUUID();
		this.version = -1;
	}

	/**
	 * [id]，
	 * 
	 */

	@NotNull
	private String id;

	/**
	 * [rescode]，
	 * 
	 */

	private String rescode;

	/**
	 * [resname]，
	 * 
	 */

	private String resname;

	/**
	 * [icon]，
	 * 
	 */

	private String icon;

	/**
	 * [res_url]，
	 * 
	 */

	private String resUrl;

	/**
	 * [res_type]，
	 * 
	 */

	private String resType;

	/**
	 * [order_by]，
	 * 
	 */

	private int orderBy;

	/**
	 * [parent_id]，
	 * 
	 */

	private String parentId;

	/**
	 * [enabled]，
	 * 
	 */

	private int enabled;

	/**
	 * [description]，
	 * 
	 */

	private String description;

	/**
	 * [version]，
	 * 
	 */

	@NotNull
	private int version;

	/**
	 * [id] getter，
	 * 
	 */
	public String getId() {
		return StringUtils.trimToEmpty(id);
	}

	/**
	 * [id] setter，
	 * 
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * [rescode] getter，
	 * 
	 */
	public String getRescode() {
		return StringUtils.trimToEmpty(rescode);
	}

	/**
	 * [rescode] setter，
	 * 
	 */
	public void setRescode(String rescode) {
		this.rescode = rescode;
	}

	/**
	 * [resname] getter，
	 * 
	 */
	public String getResname() {
		return StringUtils.trimToEmpty(resname);
	}

	/**
	 * [resname] setter，
	 * 
	 */
	public void setResname(String resname) {
		this.resname = resname;
	}

	/**
	 * [icon] getter，
	 * 
	 */
	public String getIcon() {
		return StringUtils.trimToEmpty(icon);
	}

	/**
	 * [icon] setter，
	 * 
	 */
	public void setIcon(String icon) {
		this.icon = icon;
	}

	/**
	 * [res_url] getter，
	 * 
	 */
	public String getResUrl() {
		return StringUtils.trimToEmpty(resUrl);
	}

	/**
	 * [res_url] setter，
	 * 
	 */
	public void setResUrl(String resUrl) {
		this.resUrl = resUrl;
	}

	/**
	 * [res_type] getter，
	 * 
	 */
	public String getResType() {
		return StringUtils.trimToEmpty(resType);
	}

	/**
	 * [res_type] setter，
	 * 
	 */
	public void setResType(String resType) {
		this.resType = resType;
	}

	/**
	 * [order_by] getter，
	 * 
	 */
	public int getOrderBy() {
		return orderBy;
	}

	/**
	 * [order_by] setter，
	 * 
	 */
	public void setOrderBy(int orderBy) {
		this.orderBy = orderBy;
	}

	/**
	 * [parent_id] getter，
	 * 
	 */
	public String getParentId() {
		return StringUtils.trimToEmpty(parentId);
	}

	/**
	 * [parent_id] setter，
	 * 
	 */
	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	/**
	 * [enabled] getter，
	 * 
	 */
	public int getEnabled() {
		return enabled;
	}

	/**
	 * [enabled] setter，
	 * 
	 */
	public void setEnabled(int enabled) {
		this.enabled = enabled;
	}

	/**
	 * [description] getter，
	 * 
	 */
	public String getDescription() {
		return StringUtils.trimToEmpty(description);
	}

	/**
	 * [description] setter，
	 * 
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * [version] getter，
	 * 
	 */
	public int getVersion() {
		return version;
	}

	/**
	 * [version] setter，
	 * 
	 */
	public void setVersion(int version) {
		this.version = version;
	}

	@Override
	public String toString() {
		System.out.println(this.getClass().getName() + ".toString():");

		String str = StringUtils.EMPTY;
		str += MessageFormat.format("Id=\"{0}\",", this.getId());
		str += MessageFormat.format("Rescode=\"{0}\",", this.getRescode());
		str += MessageFormat.format("Resname=\"{0}\",", this.getResname());
		str += MessageFormat.format("Icon=\"{0}\",", this.getIcon());
		str += MessageFormat.format("ResUrl=\"{0}\",", this.getResUrl());
		str += MessageFormat.format("ResType=\"{0}\",", this.getResType());
		str += MessageFormat.format("OrderBy=\"{0}\",", this.getOrderBy());
		str += MessageFormat.format("ParentId=\"{0}\",", this.getParentId());
		str += MessageFormat.format("Enabled=\"{0}\",", this.getEnabled());
		str += MessageFormat.format("Description=\"{0}\",",
				this.getDescription());
		str += MessageFormat.format("Version=\"{0}\",", this.getVersion());
		;
		return str;

	}
}
