/**
  * @ ChengQiyi create in 2014-7-12 23:08:04 by Template at 2014年6月25日21:26:55
  * This class generated by CodeSmith Generator
  */

package hply.domain;

import java.io.Serializable;
import java.util.Date;
import java.text.MessageFormat;
import hply.common.Utility;


/**
  * 模型类，对应的数据库表： [t_sys_resource]
  * 
  */
public class SysResource implements Serializable {
        
  private String id;
  
/**
  * 读，数据库列： ID  
  * 
  */
	public String getId() {
		return id;
	}

/**
  * 写，数据库列：ID  
  * 
  */
	public void setId(String id) {
		this.id = id;
	}
		
        
  private String rescode;
  
/**
  * 读，数据库列： Rescode  
  * 
  */
	public String getRescode() {
		return rescode;
	}

/**
  * 写，数据库列：Rescode  
  * 
  */
	public void setRescode(String rescode) {
		this.rescode = rescode;
	}
		
        
  private String resname;
  
/**
  * 读，数据库列： Resname  
  * 
  */
	public String getResname() {
		return resname;
	}

/**
  * 写，数据库列：Resname  
  * 
  */
	public void setResname(String resname) {
		this.resname = resname;
	}
		
        
  private String icon;
  
/**
  * 读，数据库列： Icon  
  * 
  */
	public String getIcon() {
		return icon;
	}

/**
  * 写，数据库列：Icon  
  * 
  */
	public void setIcon(String icon) {
		this.icon = icon;
	}
		
        
  private String resurl;
  
/**
  * 读，数据库列： ResUrl  
  * 
  */
	public String getResurl() {
		return resurl;
	}

/**
  * 写，数据库列：ResUrl  
  * 
  */
	public void setResurl(String resurl) {
		this.resurl = resurl;
	}
		
        
  private String restype;
  
/**
  * 读，数据库列： ResType  
  * 
  */
	public String getRestype() {
		return restype;
	}

/**
  * 写，数据库列：ResType  
  * 
  */
	public void setRestype(String restype) {
		this.restype = restype;
	}
		
        
  private int orderby;
  
/**
  * 读，数据库列： OrderBY  
  * 
  */
	public int getOrderby() {
		return orderby;
	}

/**
  * 写，数据库列：OrderBY  
  * 
  */
	public void setOrderby(int orderby) {
		this.orderby = orderby;
	}
		
        
  private String parentid;
  
/**
  * 读，数据库列： ParentID  
  * 
  */
	public String getParentid() {
		return parentid;
	}

/**
  * 写，数据库列：ParentID  
  * 
  */
	public void setParentid(String parentid) {
		this.parentid = parentid;
	}
		
        
  private int enabled;
  
/**
  * 读，数据库列： Enabled  
  * 
  */
	public int getEnabled() {
		return enabled;
	}

/**
  * 写，数据库列：Enabled  
  * 
  */
	public void setEnabled(int enabled) {
		this.enabled = enabled;
	}
		
        
  private String description;
  
/**
  * 读，数据库列： Description  
  * 
  */
	public String getDescription() {
		return description;
	}

/**
  * 写，数据库列：Description  
  * 
  */
	public void setDescription(String description) {
		this.description = description;
	}
		
        
    @Override
	public String toString() {
		System.out.println(this.getClass().getName() + ".toString():");
        
        String str = Utility.EMPTY_STRING;
        str += MessageFormat.format("\tId=\"{0}\"\n", this.getId());
        str += MessageFormat.format("\tRescode=\"{0}\"\n", this.getRescode());
        str += MessageFormat.format("\tResname=\"{0}\"\n", this.getResname());
        str += MessageFormat.format("\tIcon=\"{0}\"\n", this.getIcon());
        str += MessageFormat.format("\tResurl=\"{0}\"\n", this.getResurl());
        str += MessageFormat.format("\tRestype=\"{0}\"\n", this.getRestype());
        str += MessageFormat.format("\tOrderby=\"{0}\"\n", this.getOrderby());
        str += MessageFormat.format("\tParentid=\"{0}\"\n", this.getParentid());
        str += MessageFormat.format("\tEnabled=\"{0}\"\n", this.getEnabled());
        str += MessageFormat.format("\tDescription=\"{0}\"\n", this.getDescription());;
        return str;
                        
	}

}

