/**
  * @ cqiyi create in 2014-8-25 23:07:45 by Template
  * This class generated by Forever Web Rapid Framework Code Generator
  */

package hply.domain;

import hply.core.Utility;

import java.io.Serializable;
import java.text.MessageFormat;
import java.util.Date;

import org.apache.commons.lang3.StringUtils;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.format.annotation.DateTimeFormat.ISO;

/**
  * 数据表： [t_sys_user]
  * 11_系统用户
  */
public class SysUser implements Serializable {
    
    	/**
	 * 
	 */
	private static final long serialVersionUID = -1747246418066155146L;
		/*
    	 * ID
    	 */
        public static final String FIELD_ID = "id";
    	/*
    	 * 登陆名
    	 */
        public static final String FIELD_LOGIN_NAME = "login_name";
    	/*
    	 * 姓名
    	 */
        public static final String FIELD_REAL_NAME = "real_name";
    	/*
    	 * 所在部门
    	 */
        public static final String FIELD_ORGANIZATION_ID = "organization_id";
    	/*
    	 * 密码
    	 */
        public static final String FIELD_PASSWORD = "password";
    	/*
    	 * 最后登陆IP
    	 */
        public static final String FIELD_LAST_LOGIN_IP = "last_login_ip";
    	/*
    	 * 最后登陆时间
    	 */
        public static final String FIELD_LAST_LOGIN_TIME = "last_login_time";
    	/*
    	 * 连续登录失败次数
    	 */
        public static final String FIELD_FAILS = "fails";
    	/*
    	 * 登陆总次数
    	 */
        public static final String FIELD_LOGINED = "logined";
    	/*
    	 * 职务
    	 */
        public static final String FIELD_POSITION = "position";
    	/*
    	 * 是否禁用
    	 */
        public static final String FIELD_ENABLED = "enabled";
    	/*
    	 * 顺序号
    	 */
        public static final String FIELD_ORDER_BY = "order_by";
    	/*
    	 * 创建时间
    	 */
        public static final String FIELD_CREATE_TIME = "create_time";
    	/*
    	 * 创建用户
    	 */
        public static final String FIELD_CREATE_USER = "create_user";
    	/*
    	 * 修改时间
    	 */
        public static final String FIELD_UPDATE_TIME = "update_time";
    	/*
    	 * 修改用户
    	 */
        public static final String FIELD_UPDATE_USER = "update_user";
    	/*
    	 * 备注
    	 */
        public static final String FIELD_DESCRIPTION = "description";
    	/*
    	 * 
    	 */
        public static final String FIELD_VERSION = "version";
    	/*
    	 * 下次登录是否必须修改密码
    	 */
        public static final String FIELD_MUST_CHANGE_PASSWORD = "must_change_password";

	/*
	 * 默认构造函数
	 */
	public SysUser() {
		this.id = Utility.getRandomUUID(); 
        this.createTime = new Date(); 
		this.createUser = Utility.getCurrentUserId(); 
        this.version = -1; 
	}

    /**
      * [id]，
      * ID
      */
      
      private String id;
      
    /**
      * [login_name]，
      * 登陆名
      */
      
      private String loginName;
      
    /**
      * [real_name]，
      * 姓名
      */
      
      private String realName;
      
    /**
      * [organization_id]，
      * 所在部门
      */
      
      private String organizationId;
      
    /**
      * [password]，
      * 密码
      */
      
      private String password;
      
    /**
      * [last_login_ip]，
      * 最后登陆IP
      */
      
      private String lastLoginIp;
      
    /**
      * [last_login_time]，
      * 最后登陆时间
      */
      @DateTimeFormat(iso=ISO.DATE)
      private Date lastLoginTime;
      
    /**
      * [fails]，
      * 连续登录失败次数
      */
      
      private Integer fails;
      
    /**
      * [logined]，
      * 登陆总次数
      */
      
      private Integer logined;
      
    /**
      * [position]，
      * 职务
      */
      
      private String position;
      
    /**
      * [enabled]，
      * 是否禁用
      */
      
      private boolean enabled;
      
    /**
      * [order_by]，
      * 顺序号
      */
      
      private Integer orderBy;
      
    /**
      * [create_time]，
      * 创建时间
      */
      @DateTimeFormat(iso=ISO.DATE)
      private Date createTime;
      
    /**
      * [create_user]，
      * 创建用户
      */
      
      private String createUser;
      
    /**
      * [update_time]，
      * 修改时间
      */
      @DateTimeFormat(iso=ISO.DATE)
      private Date updateTime;
      
    /**
      * [update_user]，
      * 修改用户
      */
      
      private String updateUser;
      
    /**
      * [description]，
      * 备注
      */
      
      private String description;
      
    /**
      * [version]，
      * 
      */
      
      private Integer version;
      
    /**
      * [must_change_password]，
      * 下次登录是否必须修改密码
      */
      
      private boolean mustChangePassword;
      
    
    /**
      * [id] getter，
      * ID
      */
    	public String getId () {
    		return this.id;
    	}

    /**
      * [id] setter，
      * ID
      */
    	public void setId(String id) {
    		this.id = id;
    	}
    /**
      * [login_name] getter，
      * 登陆名
      */
    	public String getLoginName () {
    		return this.loginName;
    	}

    /**
      * [login_name] setter，
      * 登陆名
      */
    	public void setLoginName(String loginName) {
    		this.loginName = loginName;
    	}
    /**
      * [real_name] getter，
      * 姓名
      */
    	public String getRealName () {
    		return this.realName;
    	}

    /**
      * [real_name] setter，
      * 姓名
      */
    	public void setRealName(String realName) {
    		this.realName = realName;
    	}
    /**
      * [organization_id] getter，
      * 所在部门
      */
    	public String getOrganizationId () {
    		return this.organizationId;
    	}

    /**
      * [organization_id] setter，
      * 所在部门
      */
    	public void setOrganizationId(String organizationId) {
    		this.organizationId = organizationId;
    	}
    /**
      * [password] getter，
      * 密码
      */
    	public String getPassword () {
    		return this.password;
    	}

    /**
      * [password] setter，
      * 密码
      */
    	public void setPassword(String password) {
    		this.password = password;
    	}
    /**
      * [last_login_ip] getter，
      * 最后登陆IP
      */
    	public String getLastLoginIp () {
    		return this.lastLoginIp;
    	}

    /**
      * [last_login_ip] setter，
      * 最后登陆IP
      */
    	public void setLastLoginIp(String lastLoginIp) {
    		this.lastLoginIp = lastLoginIp;
    	}
    /**
      * [last_login_time] getter，
      * 最后登陆时间
      */
    	public Date getLastLoginTime () {
    		return this.lastLoginTime;
    	}

    /**
      * [last_login_time] setter，
      * 最后登陆时间
      */
    	public void setLastLoginTime(Date lastLoginTime) {
    		this.lastLoginTime = lastLoginTime;
    	}
    /**
      * [fails] getter，
      * 连续登录失败次数
      */
    	public Integer getFails () {
    		return this.fails;
    	}

    /**
      * [fails] setter，
      * 连续登录失败次数
      */
    	public void setFails(Integer fails) {
    		this.fails = fails;
    	}
    /**
      * [logined] getter，
      * 登陆总次数
      */
    	public Integer getLogined () {
    		return this.logined;
    	}

    /**
      * [logined] setter，
      * 登陆总次数
      */
    	public void setLogined(Integer logined) {
    		this.logined = logined;
    	}
    /**
      * [position] getter，
      * 职务
      */
    	public String getPosition () {
    		return this.position;
    	}

    /**
      * [position] setter，
      * 职务
      */
    	public void setPosition(String position) {
    		this.position = position;
    	}
    /**
      * [enabled] getter，
      * 是否禁用
      */
    	public boolean getEnabled () {
    		return this.enabled;
    	}

    /**
      * [enabled] setter，
      * 是否禁用
      */
    	public void setEnabled(boolean enabled) {
    		this.enabled = enabled;
    	}
    /**
      * [order_by] getter，
      * 顺序号
      */
    	public Integer getOrderBy () {
    		return this.orderBy;
    	}

    /**
      * [order_by] setter，
      * 顺序号
      */
    	public void setOrderBy(Integer orderBy) {
    		this.orderBy = orderBy;
    	}
    /**
      * [create_time] getter，
      * 创建时间
      */
    	public Date getCreateTime () {
    		return this.createTime;
    	}

    /**
      * [create_time] setter，
      * 创建时间
      */
    	public void setCreateTime(Date createTime) {
    		this.createTime = createTime;
    	}
    /**
      * [create_user] getter，
      * 创建用户
      */
    	public String getCreateUser () {
    		return this.createUser;
    	}

    /**
      * [create_user] setter，
      * 创建用户
      */
    	public void setCreateUser(String createUser) {
    		this.createUser = createUser;
    	}
    /**
      * [update_time] getter，
      * 修改时间
      */
    	public Date getUpdateTime () {
    		return this.updateTime;
    	}

    /**
      * [update_time] setter，
      * 修改时间
      */
    	public void setUpdateTime(Date updateTime) {
    		this.updateTime = updateTime;
    	}
    /**
      * [update_user] getter，
      * 修改用户
      */
    	public String getUpdateUser () {
    		return this.updateUser;
    	}

    /**
      * [update_user] setter，
      * 修改用户
      */
    	public void setUpdateUser(String updateUser) {
    		this.updateUser = updateUser;
    	}
    /**
      * [description] getter，
      * 备注
      */
    	public String getDescription () {
    		return this.description;
    	}

    /**
      * [description] setter，
      * 备注
      */
    	public void setDescription(String description) {
    		this.description = description;
    	}
    /**
      * [version] getter，
      * 
      */
    	public Integer getVersion () {
    		return this.version;
    	}

    /**
      * [version] setter，
      * 
      */
    	public void setVersion(Integer version) {
    		this.version = version;
    	}
    /**
      * [must_change_password] getter，
      * 下次登录是否必须修改密码
      */
    	public boolean getMustChangePassword () {
    		return this.mustChangePassword;
    	}

    /**
      * [must_change_password] setter，
      * 下次登录是否必须修改密码
      */
    	public void setMustChangePassword(boolean mustChangePassword) {
    		this.mustChangePassword = mustChangePassword;
    	}
    
	@Override
	public String toString() {
		Utility.println(this.getClass().getName() + ".toString():");
        
        String str = StringUtils.EMPTY;
        str += MessageFormat.format("Id=\"{0}\",", StringUtils.trimToEmpty(this.getId()));
        str += MessageFormat.format("LoginName=\"{0}\",", StringUtils.trimToEmpty(this.getLoginName()));
        str += MessageFormat.format("RealName=\"{0}\",", StringUtils.trimToEmpty(this.getRealName()));
        str += MessageFormat.format("OrganizationId=\"{0}\",", StringUtils.trimToEmpty(this.getOrganizationId()));
        str += MessageFormat.format("Password=\"{0}\",", StringUtils.trimToEmpty(this.getPassword()));
        str += MessageFormat.format("LastLoginIp=\"{0}\",", StringUtils.trimToEmpty(this.getLastLoginIp()));
        str += MessageFormat.format("LastLoginTime=\"{0}\",", this.getLastLoginTime());
        str += MessageFormat.format("Fails=\"{0}\",", this.getFails());
        str += MessageFormat.format("Logined=\"{0}\",", this.getLogined());
        str += MessageFormat.format("Position=\"{0}\",", StringUtils.trimToEmpty(this.getPosition()));
        str += MessageFormat.format("Enabled=\"{0}\",", this.getEnabled());
        str += MessageFormat.format("OrderBy=\"{0}\",", this.getOrderBy());
        str += MessageFormat.format("CreateTime=\"{0}\",", this.getCreateTime());
        str += MessageFormat.format("CreateUser=\"{0}\",", StringUtils.trimToEmpty(this.getCreateUser()));
        str += MessageFormat.format("UpdateTime=\"{0}\",", this.getUpdateTime());
        str += MessageFormat.format("UpdateUser=\"{0}\",", StringUtils.trimToEmpty(this.getUpdateUser()));
        str += MessageFormat.format("Description=\"{0}\",", StringUtils.trimToEmpty(this.getDescription()));
        str += MessageFormat.format("Version=\"{0}\",", this.getVersion());
        str += MessageFormat.format("MustChangePassword=\"{0}\",", this.getMustChangePassword());;
        return str;
                        
	}
}

