/**
  * @ cqiyi create in 2014-8-5 22:19:56 by Template
  * This class generated by Forever Web Rapid Framework Code Generator
  */

package hply.domain;

import java.io.Serializable;
import java.text.MessageFormat;
import java.util.Date;

import javax.validation.constraints.NotNull;

import org.apache.commons.lang3.StringUtils;
import hply.core.Utility;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.format.annotation.DateTimeFormat.ISO;

/**
  * 数据表： [t_chop]
  * 09_盖章管理
  */
public class Chop implements Serializable {

	/*
	 * 默认构造函数
	 */
	public Chop() {
		this.id = Utility.getRandomUUID(); 
        this.version = -1; 
	}

    /**
      * [id]，
      * ID
      */
      
      private String id;
      
    /**
      * [chop_code]，
      * 编号
      */
      
      private String chopCode;
      
    /**
      * [project_id]，
      * 项目ID
      */
      
      private String projectId;
      
    /**
      * [project_code]，
      * 项目编号
      */
      
      private String projectCode;
      
    /**
      * [project_name]，
      * 项目名称
      */
      
      private String projectName;
      
    /**
      * [manager]，
      * 项目经理
      */
      
      private String manager;
      
    /**
      * [content]，
      * 主要内容
      */
      
      private String content;
      
    /**
      * [apply_user]，
      * 申请人
      */
      
      private String applyUser;
      
    /**
      * [apply_time]，
      * 申请时间
      */
      @DateTimeFormat(iso=ISO.DATE)
      private Date applyTime;
      
    /**
      * [organization_id]，
      * 所在部门
      */
      
      private String organizationId;
      
    /**
      * [step1_idea]，
      * 事业部/项目部审核意见
      */
      
      private String step1Idea;
      
    /**
      * [step1_user]，
      * 事业部/项目部审核人
      */
      
      private String step1User;
      
    /**
      * [step1_time]，
      * 事业部/项目部审核时间
      */
      @DateTimeFormat(iso=ISO.DATE)
      private Date step1Time;
      
    /**
      * [step2_idea]，
      * 财务部审核意见
      */
      
      private String step2Idea;
      
    /**
      * [step2_user]，
      * 财务部审核人
      */
      
      private String step2User;
      
    /**
      * [step2_time]，
      * 财务部审核时间
      */
      @DateTimeFormat(iso=ISO.DATE)
      private Date step2Time;
      
    /**
      * [step3_idea]，
      * 经办人办理结果
      */
      
      private String step3Idea;
      
    /**
      * [step3_user]，
      * 经办人
      */
      
      private String step3User;
      
    /**
      * [step3_time]，
      * 经办时间
      */
      @DateTimeFormat(iso=ISO.DATE)
      private Date step3Time;
      
    /**
      * [step_status]，
      * 流程状态
      */
      
      private String stepStatus;
      
    /**
      * [version]，
      * 
      */
      
      private Integer version;
      
    /**
      * [status]，
      * 数据状态，0：草稿/1：正式
      */
      
      private Integer status;
      
    
    /**
      * [id] getter，
      * ID
      */
    	public String getId () {
    		return this.id;
    	}

    /**
      * [id] setter，
      * ID
      */
    	public void setId(String id) {
    		this.id = id;
    	}
    /**
      * [chop_code] getter，
      * 编号
      */
    	public String getChopCode () {
    		return this.chopCode;
    	}

    /**
      * [chop_code] setter，
      * 编号
      */
    	public void setChopCode(String chopCode) {
    		this.chopCode = chopCode;
    	}
    /**
      * [project_id] getter，
      * 项目ID
      */
    	public String getProjectId () {
    		return this.projectId;
    	}

    /**
      * [project_id] setter，
      * 项目ID
      */
    	public void setProjectId(String projectId) {
    		this.projectId = projectId;
    	}
    /**
      * [project_code] getter，
      * 项目编号
      */
    	public String getProjectCode () {
    		return this.projectCode;
    	}

    /**
      * [project_code] setter，
      * 项目编号
      */
    	public void setProjectCode(String projectCode) {
    		this.projectCode = projectCode;
    	}
    /**
      * [project_name] getter，
      * 项目名称
      */
    	public String getProjectName () {
    		return this.projectName;
    	}

    /**
      * [project_name] setter，
      * 项目名称
      */
    	public void setProjectName(String projectName) {
    		this.projectName = projectName;
    	}
    /**
      * [manager] getter，
      * 项目经理
      */
    	public String getManager () {
    		return this.manager;
    	}

    /**
      * [manager] setter，
      * 项目经理
      */
    	public void setManager(String manager) {
    		this.manager = manager;
    	}
    /**
      * [content] getter，
      * 主要内容
      */
    	public String getContent () {
    		return this.content;
    	}

    /**
      * [content] setter，
      * 主要内容
      */
    	public void setContent(String content) {
    		this.content = content;
    	}
    /**
      * [apply_user] getter，
      * 申请人
      */
    	public String getApplyUser () {
    		return this.applyUser;
    	}

    /**
      * [apply_user] setter，
      * 申请人
      */
    	public void setApplyUser(String applyUser) {
    		this.applyUser = applyUser;
    	}
    /**
      * [apply_time] getter，
      * 申请时间
      */
    	public Date getApplyTime () {
    		return this.applyTime;
    	}

    /**
      * [apply_time] setter，
      * 申请时间
      */
    	public void setApplyTime(Date applyTime) {
    		this.applyTime = applyTime;
    	}
    /**
      * [organization_id] getter，
      * 所在部门
      */
    	public String getOrganizationId () {
    		return this.organizationId;
    	}

    /**
      * [organization_id] setter，
      * 所在部门
      */
    	public void setOrganizationId(String organizationId) {
    		this.organizationId = organizationId;
    	}
    /**
      * [step1_idea] getter，
      * 事业部/项目部审核意见
      */
    	public String getStep1Idea () {
    		return this.step1Idea;
    	}

    /**
      * [step1_idea] setter，
      * 事业部/项目部审核意见
      */
    	public void setStep1Idea(String step1Idea) {
    		this.step1Idea = step1Idea;
    	}
    /**
      * [step1_user] getter，
      * 事业部/项目部审核人
      */
    	public String getStep1User () {
    		return this.step1User;
    	}

    /**
      * [step1_user] setter，
      * 事业部/项目部审核人
      */
    	public void setStep1User(String step1User) {
    		this.step1User = step1User;
    	}
    /**
      * [step1_time] getter，
      * 事业部/项目部审核时间
      */
    	public Date getStep1Time () {
    		return this.step1Time;
    	}

    /**
      * [step1_time] setter，
      * 事业部/项目部审核时间
      */
    	public void setStep1Time(Date step1Time) {
    		this.step1Time = step1Time;
    	}
    /**
      * [step2_idea] getter，
      * 财务部审核意见
      */
    	public String getStep2Idea () {
    		return this.step2Idea;
    	}

    /**
      * [step2_idea] setter，
      * 财务部审核意见
      */
    	public void setStep2Idea(String step2Idea) {
    		this.step2Idea = step2Idea;
    	}
    /**
      * [step2_user] getter，
      * 财务部审核人
      */
    	public String getStep2User () {
    		return this.step2User;
    	}

    /**
      * [step2_user] setter，
      * 财务部审核人
      */
    	public void setStep2User(String step2User) {
    		this.step2User = step2User;
    	}
    /**
      * [step2_time] getter，
      * 财务部审核时间
      */
    	public Date getStep2Time () {
    		return this.step2Time;
    	}

    /**
      * [step2_time] setter，
      * 财务部审核时间
      */
    	public void setStep2Time(Date step2Time) {
    		this.step2Time = step2Time;
    	}
    /**
      * [step3_idea] getter，
      * 经办人办理结果
      */
    	public String getStep3Idea () {
    		return this.step3Idea;
    	}

    /**
      * [step3_idea] setter，
      * 经办人办理结果
      */
    	public void setStep3Idea(String step3Idea) {
    		this.step3Idea = step3Idea;
    	}
    /**
      * [step3_user] getter，
      * 经办人
      */
    	public String getStep3User () {
    		return this.step3User;
    	}

    /**
      * [step3_user] setter，
      * 经办人
      */
    	public void setStep3User(String step3User) {
    		this.step3User = step3User;
    	}
    /**
      * [step3_time] getter，
      * 经办时间
      */
    	public Date getStep3Time () {
    		return this.step3Time;
    	}

    /**
      * [step3_time] setter，
      * 经办时间
      */
    	public void setStep3Time(Date step3Time) {
    		this.step3Time = step3Time;
    	}
    /**
      * [step_status] getter，
      * 流程状态
      */
    	public String getStepStatus () {
    		return this.stepStatus;
    	}

    /**
      * [step_status] setter，
      * 流程状态
      */
    	public void setStepStatus(String stepStatus) {
    		this.stepStatus = stepStatus;
    	}
    /**
      * [version] getter，
      * 
      */
    	public Integer getVersion () {
    		return this.version;
    	}

    /**
      * [version] setter，
      * 
      */
    	public void setVersion(Integer version) {
    		this.version = version;
    	}
    /**
      * [status] getter，
      * 数据状态，0：草稿/1：正式
      */
    	public Integer getStatus () {
    		return this.status;
    	}

    /**
      * [status] setter，
      * 数据状态，0：草稿/1：正式
      */
    	public void setStatus(Integer status) {
    		this.status = status;
    	}
    
	@Override
	public String toString() {
		System.out.println(this.getClass().getName() + ".toString():");
        
        String str = StringUtils.EMPTY;
        str += MessageFormat.format("Id=\"{0}\",", StringUtils.trimToEmpty(this.getId()));
        str += MessageFormat.format("ChopCode=\"{0}\",", StringUtils.trimToEmpty(this.getChopCode()));
        str += MessageFormat.format("ProjectId=\"{0}\",", StringUtils.trimToEmpty(this.getProjectId()));
        str += MessageFormat.format("ProjectCode=\"{0}\",", StringUtils.trimToEmpty(this.getProjectCode()));
        str += MessageFormat.format("ProjectName=\"{0}\",", StringUtils.trimToEmpty(this.getProjectName()));
        str += MessageFormat.format("Manager=\"{0}\",", StringUtils.trimToEmpty(this.getManager()));
        str += MessageFormat.format("Content=\"{0}\",", StringUtils.trimToEmpty(this.getContent()));
        str += MessageFormat.format("ApplyUser=\"{0}\",", StringUtils.trimToEmpty(this.getApplyUser()));
        str += MessageFormat.format("ApplyTime=\"{0}\",", this.getApplyTime());
        str += MessageFormat.format("OrganizationId=\"{0}\",", StringUtils.trimToEmpty(this.getOrganizationId()));
        str += MessageFormat.format("Step1Idea=\"{0}\",", StringUtils.trimToEmpty(this.getStep1Idea()));
        str += MessageFormat.format("Step1User=\"{0}\",", StringUtils.trimToEmpty(this.getStep1User()));
        str += MessageFormat.format("Step1Time=\"{0}\",", this.getStep1Time());
        str += MessageFormat.format("Step2Idea=\"{0}\",", StringUtils.trimToEmpty(this.getStep2Idea()));
        str += MessageFormat.format("Step2User=\"{0}\",", StringUtils.trimToEmpty(this.getStep2User()));
        str += MessageFormat.format("Step2Time=\"{0}\",", this.getStep2Time());
        str += MessageFormat.format("Step3Idea=\"{0}\",", StringUtils.trimToEmpty(this.getStep3Idea()));
        str += MessageFormat.format("Step3User=\"{0}\",", StringUtils.trimToEmpty(this.getStep3User()));
        str += MessageFormat.format("Step3Time=\"{0}\",", this.getStep3Time());
        str += MessageFormat.format("StepStatus=\"{0}\",", StringUtils.trimToEmpty(this.getStepStatus()));
        str += MessageFormat.format("Version=\"{0}\",", this.getVersion());
        str += MessageFormat.format("Status=\"{0}\",", this.getStatus());;
        return str;
                        
	}
}

