/**
 * @ cqiyi create in 2014-9-23 22:26:27 by Template
 * This class generated by Forever Web Rapid Framework Code Generator
 */

package hply.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import hply.domain.ArrearsInterest;
import hply.mapper.partial.PartialArrearsInterestMapper;

/**
 * 数据表： [t_arrears_interest] 往来欠款的利息计算明细
 */
@Repository
public interface ArrearsInterestMapper extends PartialArrearsInterestMapper {
	public List<ArrearsInterest> getDetail(@Param("arrearsId") String arrearsId);

	public Double getPlanInterest(String projectId);

	public Double getRealInterest(String projectId);
}
