/**
 * @ cqiyi create in 2014-8-5 20:27:38 by Template
 * This class generated by Forever Web Rapid Framework Code Generator
 */

package hply.mapper;

import org.springframework.stereotype.Repository;

import hply.mapper.partial.PartialArrearsMapper;

/**
 * 数据表： [t_arrears] 07_往来欠款
 */
@Repository
public interface ArrearsMapper extends PartialArrearsMapper {
	public Double getTotalByProject(String projectId);
}
