/**
 * @ cqiyi create in 2014-8-25 23:07:45 by Template
 * This class generated by Forever Web Rapid Framework Code Generator
 */

package hply.mapper;

import java.util.List;

import hply.domain.Chop;
import hply.mapper.partial.PartialChopMapper;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

/**
 * 数据表： [t_chop] 09_盖章管理
 */
@Repository
public interface ChopMapper extends PartialChopMapper {

	public List<Chop> getAllPagedByOrganization(@Param("organizationId") String organizationId, @Param("pageIndex") int pageIndex,
			@Param("pageSize") int pageSize);

	public int getRowCountByOrganization(@Param("organizationId") String organizationId);
}
