/**
  * @ cqiyi create in 2014-8-25 23:07:45 by Template
  * This class generated by Forever Web Rapid Framework Code Generator
  */
  
package hply.mapper;

import hply.domain.CustomerBilling;
import hply.mapper.partial.PartialCustomerBillingMapper;

import java.util.List;

import org.springframework.stereotype.Repository;



/**
  * 数据表： [t_customer_billing]
  * 04_客户开票情况
  */
@Repository
public interface CustomerBillingMapper extends PartialCustomerBillingMapper {

	public List<CustomerBilling> getAllByProject(String projectId);
}

