/**
  * @ cqiyi create in 2014-8-25 23:07:45 by Template
  * This class generated by Forever Web Rapid Framework Code Generator
  */
  
package hply.mapper;

import hply.mapper.partial.PartialInformationMapper;

import org.springframework.stereotype.Repository;



/**
  * 数据表： [t_information]
  * 10_信息登记
  */
@Repository
public interface InformationMapper extends PartialInformationMapper {

}

