/**
  * @ cqiyi create in 2014/7/24 20:53:29 by Template
  * This class generated by Forever Web Rapid Framework Code Generator
  */
  
package hply.mapper;

import hply.domain.PartyBilling;

import java.util.List;

import org.springframework.stereotype.Repository;



/**
  * 数据表： [t_party_billing]
  * 
  */
@Repository
public interface PartyBillingMapper {

	  public void insert(PartyBilling partyBilling);
	  
	  public void update(PartyBilling partyBilling);
	  
	  public void delete(String id);
	  
	  public PartyBilling get(String id);
      
	  public int getVersion(String id);
	  
	  public List<PartyBilling> getAll();
}

