/**
  * @ cqiyi create in 2014-8-25 23:07:45 by Template
  * This class generated by Forever Web Rapid Framework Code Generator
  */
  
package hply.mapper;

import java.util.List;

import hply.domain.PaymentDifferentTaxAmount;
import hply.domain.Where;
import hply.mapper.partial.PartialPaymentDifferentTaxAmountMapper;

import org.springframework.stereotype.Repository;



/**
  * 数据表： [t_payment_different_tax_amount]
  * 异地税金
  */
@Repository
public interface PaymentDifferentTaxAmountMapper extends PartialPaymentDifferentTaxAmountMapper {

	public void deleteBy(Where where);
	
	public List<PaymentDifferentTaxAmount> getAllBy(Where where);
}

