/**
  * @ cqiyi create in 2014-8-5 20:27:38 by Template
  * This class generated by Forever Web Rapid Framework Code Generator
  */
  
package hply.mapper;

import java.util.List;

import org.springframework.stereotype.Repository;

import hply.domain.Project;
import hply.domain.ProjectSummary;
import hply.mapper.partial.PartialProjectSummaryMapper;



/**
  * 数据表： [t_project_summary]
  * 00_多项目汇总
  */
@Repository
public interface ProjectSummaryMapper extends PartialProjectSummaryMapper {

}

