/**
 * @ cqiyi create in 2014/7/24 20:53:29 by Template
 * This class generated by Forever Web Rapid Framework Code Generator
 */

package hply.mapper;

import hply.domain.Project;

import java.util.List;

import org.springframework.stereotype.Repository;

/**
 * 数据表： [t_project]
 * 
 */
@Repository
public interface ProjectMapper {

	public void insert(Project project);

	public void update(Project project);

	public void delete(String id);

	public Project get(String id);

	public int getVersion(String id);

	public List<Project> getAll();
}
