/**
  * @ cqiyi create in 2014-8-5 20:27:38 by Template
  * This class generated by Forever Web Rapid Framework Code Generator
  */
  
package hply.mapper;

import org.springframework.stereotype.Repository;
import hply.mapper.partial.PartialSysOrganizationMapper;



/**
  * 数据表： [t_sys_organization]
  * 11+A_组织机构
  */
@Repository
public interface SysOrganizationMapper extends PartialSysOrganizationMapper {

}

