/**
 * @ cqiyi create in 2014/7/24 20:53:29 by Template
 * This class generated by Forever Web Rapid Framework Code Generator
 */

package hply.mapper;

import hply.domain.SysOrganization;

import java.util.List;

import org.springframework.stereotype.Repository;

/**
 * 数据表： [t_sys_organization]
 * 
 */
@Repository
public interface SysOrganizationMapper {

	public void insert(SysOrganization sysOrganization);

	public void update(SysOrganization sysOrganization);

	public void delete(String id);

	public SysOrganization get(String id);

	public int getVersion(String id);

	public List<SysOrganization> getAll();
}
