/**
  * @ cqiyi create in 2014-8-25 23:07:45 by Template
  * This class generated by Forever Web Rapid Framework Code Generator
  */
  
package hply.mapper;

import hply.mapper.partial.PartialSysOrganizationMapper;

import org.springframework.stereotype.Repository;



/**
  * 数据表： [t_sys_organization]
  * 11+A_组织机构
  */
@Repository
public interface SysOrganizationMapper extends PartialSysOrganizationMapper {

}

