/**
 * @ cqiyi create in 2014/8/15 10:25:24 by Template
 * This class generated by Forever Web Rapid Framework Code Generator
 */

package com.hhwy.fresource2.mapper;

import org.springframework.stereotype.Repository;

import com.hhwy.fresource2.mapper.partial.PartialSysRoleMapper;

/**
 * 数据表： [t_sys_role] 系统角色表
 */
@Repository
public interface SysRoleMapper extends PartialSysRoleMapper {

}
