/**
  * @ cqiyi create in 2014/7/24 21:26:49 by Template
  * This class generated by Forever Web Rapid Framework Code Generator
  */

package hply.domain;

import java.io.Serializable;
import java.text.MessageFormat;
import java.util.Date;

import javax.validation.constraints.NotNull;

import org.apache.commons.lang3.StringUtils;
import hply.Utility;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.format.annotation.DateTimeFormat.ISO;

/**
  * 数据表： [t_project]
  * 
  */
public class Project implements Serializable {

	/*
	 * 默认构造函数
	 */
	public Project() {
        this.version = -1;
		this.id = Utility.getRandomUUID();
        
        //设定日期为空时的初始值
        this.dutyPaidTime = new Date(0);this.trice = new Date(0);this.createTime = new Date(0);this.updateTime = new Date(0);
	}

    /**
      * [id]，
      * 
      */
      
      @NotNull
      
      private String id;
      
    /**
      * [project_code]，
      * 
      */
      
      
      
      private String projectCode;
      
    /**
      * [project_name]，
      * 
      */
      
      
      
      private String projectName;
      
    /**
      * [organization_id]，
      * 
      */
      
      
      
      private String organizationId;
      
    /**
      * [party_name]，
      * 
      */
      
      
      
      private String partyName;
      
    /**
      * [party_address]，
      * 
      */
      
      
      
      private String partyAddress;
      
    /**
      * [manager]，
      * 
      */
      
      
      
      private String manager;
      
    /**
      * [contract_code]，
      * 
      */
      
      
      
      private String contractCode;
      
    /**
      * [cooperation]，
      * 
      */
      
      
      
      private String cooperation;
      
    /**
      * [legal_assignee]，
      * 
      */
      
      
      
      private String legalAssignee;
      
    /**
      * [is_withholding_offsite]，
      * 
      */
      
      
      
      private int isWithholdingOffsite;
      
    /**
      * [management_rate]，
      * 
      */
      
      @NotNull
      
      private double managementRate;
      
    /**
      * [tax_rate]，
      * 
      */
      
      @NotNull
      
      private double taxRate;
      
    /**
      * [contract_amount]，
      * 
      */
      
      @NotNull
      
      private double contractAmount;
      
    /**
      * [settlement_amount]，
      * 
      */
      
      @NotNull
      
      private double settlementAmount;
      
    /**
      * [duty_paid_time]，
      * 
      */
      
      
      @DateTimeFormat(iso=ISO.DATE)
      private Date dutyPaidTime;
      
    /**
      * [duty_paid_amount]，
      * 
      */
      
      @NotNull
      
      private double dutyPaidAmount;
      
    /**
      * [duty_paid_code]，
      * 
      */
      
      
      
      private String dutyPaidCode;
      
    /**
      * [capital_occupied]，
      * 
      */
      
      @NotNull
      
      private double capitalOccupied;
      
    /**
      * [project_status]，
      * 
      */
      
      
      
      private int projectStatus;
      
    /**
      * [trice]，
      * 
      */
      
      
      @DateTimeFormat(iso=ISO.DATE)
      private Date trice;
      
    /**
      * [create_time]，
      * 
      */
      
      
      @DateTimeFormat(iso=ISO.DATE)
      private Date createTime;
      
    /**
      * [create_user]，
      * 
      */
      
      
      
      private String createUser;
      
    /**
      * [update_time]，
      * 
      */
      
      
      @DateTimeFormat(iso=ISO.DATE)
      private Date updateTime;
      
    /**
      * [update_user]，
      * 
      */
      
      
      
      private String updateUser;
      
    /**
      * [description]，
      * 
      */
      
      
      
      private String description;
      
    /**
      * [version]，
      * 
      */
      
      @NotNull
      
      private int version;
      
    
    /**
      * [id] getter，
      * 
      */
    	public String getId () {
            return StringUtils.trimToEmpty(id);
    	}

    /**
      * [id] setter，
      * 
      */
    	public void setId(String id) {
    		this.id = id;
    	}
    /**
      * [project_code] getter，
      * 
      */
    	public String getProjectCode () {
            return StringUtils.trimToEmpty(projectCode);
    	}

    /**
      * [project_code] setter，
      * 
      */
    	public void setProjectCode(String projectCode) {
    		this.projectCode = projectCode;
    	}
    /**
      * [project_name] getter，
      * 
      */
    	public String getProjectName () {
            return StringUtils.trimToEmpty(projectName);
    	}

    /**
      * [project_name] setter，
      * 
      */
    	public void setProjectName(String projectName) {
    		this.projectName = projectName;
    	}
    /**
      * [organization_id] getter，
      * 
      */
    	public String getOrganizationId () {
            return StringUtils.trimToEmpty(organizationId);
    	}

    /**
      * [organization_id] setter，
      * 
      */
    	public void setOrganizationId(String organizationId) {
    		this.organizationId = organizationId;
    	}
    /**
      * [party_name] getter，
      * 
      */
    	public String getPartyName () {
            return StringUtils.trimToEmpty(partyName);
    	}

    /**
      * [party_name] setter，
      * 
      */
    	public void setPartyName(String partyName) {
    		this.partyName = partyName;
    	}
    /**
      * [party_address] getter，
      * 
      */
    	public String getPartyAddress () {
            return StringUtils.trimToEmpty(partyAddress);
    	}

    /**
      * [party_address] setter，
      * 
      */
    	public void setPartyAddress(String partyAddress) {
    		this.partyAddress = partyAddress;
    	}
    /**
      * [manager] getter，
      * 
      */
    	public String getManager () {
            return StringUtils.trimToEmpty(manager);
    	}

    /**
      * [manager] setter，
      * 
      */
    	public void setManager(String manager) {
    		this.manager = manager;
    	}
    /**
      * [contract_code] getter，
      * 
      */
    	public String getContractCode () {
            return StringUtils.trimToEmpty(contractCode);
    	}

    /**
      * [contract_code] setter，
      * 
      */
    	public void setContractCode(String contractCode) {
    		this.contractCode = contractCode;
    	}
    /**
      * [cooperation] getter，
      * 
      */
    	public String getCooperation () {
            return StringUtils.trimToEmpty(cooperation);
    	}

    /**
      * [cooperation] setter，
      * 
      */
    	public void setCooperation(String cooperation) {
    		this.cooperation = cooperation;
    	}
    /**
      * [legal_assignee] getter，
      * 
      */
    	public String getLegalAssignee () {
            return StringUtils.trimToEmpty(legalAssignee);
    	}

    /**
      * [legal_assignee] setter，
      * 
      */
    	public void setLegalAssignee(String legalAssignee) {
    		this.legalAssignee = legalAssignee;
    	}
    /**
      * [is_withholding_offsite] getter，
      * 
      */
    	public int getIsWithholdingOffsite () {
    		return isWithholdingOffsite;
    	}

    /**
      * [is_withholding_offsite] setter，
      * 
      */
    	public void setIsWithholdingOffsite(int isWithholdingOffsite) {
    		this.isWithholdingOffsite = isWithholdingOffsite;
    	}
    /**
      * [management_rate] getter，
      * 
      */
    	public double getManagementRate () {
    		return managementRate;
    	}

    /**
      * [management_rate] setter，
      * 
      */
    	public void setManagementRate(double managementRate) {
    		this.managementRate = managementRate;
    	}
    /**
      * [tax_rate] getter，
      * 
      */
    	public double getTaxRate () {
    		return taxRate;
    	}

    /**
      * [tax_rate] setter，
      * 
      */
    	public void setTaxRate(double taxRate) {
    		this.taxRate = taxRate;
    	}
    /**
      * [contract_amount] getter，
      * 
      */
    	public double getContractAmount () {
    		return contractAmount;
    	}

    /**
      * [contract_amount] setter，
      * 
      */
    	public void setContractAmount(double contractAmount) {
    		this.contractAmount = contractAmount;
    	}
    /**
      * [settlement_amount] getter，
      * 
      */
    	public double getSettlementAmount () {
    		return settlementAmount;
    	}

    /**
      * [settlement_amount] setter，
      * 
      */
    	public void setSettlementAmount(double settlementAmount) {
    		this.settlementAmount = settlementAmount;
    	}
    /**
      * [duty_paid_time] getter，
      * 
      */
    	public Date getDutyPaidTime () {
    		return dutyPaidTime;
    	}

    /**
      * [duty_paid_time] setter，
      * 
      */
    	public void setDutyPaidTime(Date dutyPaidTime) {
    		this.dutyPaidTime = dutyPaidTime;
    	}
    /**
      * [duty_paid_amount] getter，
      * 
      */
    	public double getDutyPaidAmount () {
    		return dutyPaidAmount;
    	}

    /**
      * [duty_paid_amount] setter，
      * 
      */
    	public void setDutyPaidAmount(double dutyPaidAmount) {
    		this.dutyPaidAmount = dutyPaidAmount;
    	}
    /**
      * [duty_paid_code] getter，
      * 
      */
    	public String getDutyPaidCode () {
            return StringUtils.trimToEmpty(dutyPaidCode);
    	}

    /**
      * [duty_paid_code] setter，
      * 
      */
    	public void setDutyPaidCode(String dutyPaidCode) {
    		this.dutyPaidCode = dutyPaidCode;
    	}
    /**
      * [capital_occupied] getter，
      * 
      */
    	public double getCapitalOccupied () {
    		return capitalOccupied;
    	}

    /**
      * [capital_occupied] setter，
      * 
      */
    	public void setCapitalOccupied(double capitalOccupied) {
    		this.capitalOccupied = capitalOccupied;
    	}
    /**
      * [project_status] getter，
      * 
      */
    	public int getProjectStatus () {
    		return projectStatus;
    	}

    /**
      * [project_status] setter，
      * 
      */
    	public void setProjectStatus(int projectStatus) {
    		this.projectStatus = projectStatus;
    	}
    /**
      * [trice] getter，
      * 
      */
    	public Date getTrice () {
    		return trice;
    	}

    /**
      * [trice] setter，
      * 
      */
    	public void setTrice(Date trice) {
    		this.trice = trice;
    	}
    /**
      * [create_time] getter，
      * 
      */
    	public Date getCreateTime () {
    		return createTime;
    	}

    /**
      * [create_time] setter，
      * 
      */
    	public void setCreateTime(Date createTime) {
    		this.createTime = createTime;
    	}
    /**
      * [create_user] getter，
      * 
      */
    	public String getCreateUser () {
            return StringUtils.trimToEmpty(createUser);
    	}

    /**
      * [create_user] setter，
      * 
      */
    	public void setCreateUser(String createUser) {
    		this.createUser = createUser;
    	}
    /**
      * [update_time] getter，
      * 
      */
    	public Date getUpdateTime () {
    		return updateTime;
    	}

    /**
      * [update_time] setter，
      * 
      */
    	public void setUpdateTime(Date updateTime) {
    		this.updateTime = updateTime;
    	}
    /**
      * [update_user] getter，
      * 
      */
    	public String getUpdateUser () {
            return StringUtils.trimToEmpty(updateUser);
    	}

    /**
      * [update_user] setter，
      * 
      */
    	public void setUpdateUser(String updateUser) {
    		this.updateUser = updateUser;
    	}
    /**
      * [description] getter，
      * 
      */
    	public String getDescription () {
            return StringUtils.trimToEmpty(description);
    	}

    /**
      * [description] setter，
      * 
      */
    	public void setDescription(String description) {
    		this.description = description;
    	}
    /**
      * [version] getter，
      * 
      */
    	public int getVersion () {
    		return version;
    	}

    /**
      * [version] setter，
      * 
      */
    	public void setVersion(int version) {
    		this.version = version;
    	}
    
	@Override
	public String toString() {
		System.out.println(this.getClass().getName() + ".toString():");
        
        String str = StringUtils.EMPTY;
        str += MessageFormat.format("Id=\"{0}\",", this.getId());
        str += MessageFormat.format("ProjectCode=\"{0}\",", this.getProjectCode());
        str += MessageFormat.format("ProjectName=\"{0}\",", this.getProjectName());
        str += MessageFormat.format("OrganizationId=\"{0}\",", this.getOrganizationId());
        str += MessageFormat.format("PartyName=\"{0}\",", this.getPartyName());
        str += MessageFormat.format("PartyAddress=\"{0}\",", this.getPartyAddress());
        str += MessageFormat.format("Manager=\"{0}\",", this.getManager());
        str += MessageFormat.format("ContractCode=\"{0}\",", this.getContractCode());
        str += MessageFormat.format("Cooperation=\"{0}\",", this.getCooperation());
        str += MessageFormat.format("LegalAssignee=\"{0}\",", this.getLegalAssignee());
        str += MessageFormat.format("IsWithholdingOffsite=\"{0}\",", this.getIsWithholdingOffsite());
        str += MessageFormat.format("ManagementRate=\"{0}\",", this.getManagementRate());
        str += MessageFormat.format("TaxRate=\"{0}\",", this.getTaxRate());
        str += MessageFormat.format("ContractAmount=\"{0}\",", this.getContractAmount());
        str += MessageFormat.format("SettlementAmount=\"{0}\",", this.getSettlementAmount());
        str += MessageFormat.format("DutyPaidTime=\"{0}\",", this.getDutyPaidTime());
        str += MessageFormat.format("DutyPaidAmount=\"{0}\",", this.getDutyPaidAmount());
        str += MessageFormat.format("DutyPaidCode=\"{0}\",", this.getDutyPaidCode());
        str += MessageFormat.format("CapitalOccupied=\"{0}\",", this.getCapitalOccupied());
        str += MessageFormat.format("ProjectStatus=\"{0}\",", this.getProjectStatus());
        str += MessageFormat.format("Trice=\"{0}\",", this.getTrice());
        str += MessageFormat.format("CreateTime=\"{0}\",", this.getCreateTime());
        str += MessageFormat.format("CreateUser=\"{0}\",", this.getCreateUser());
        str += MessageFormat.format("UpdateTime=\"{0}\",", this.getUpdateTime());
        str += MessageFormat.format("UpdateUser=\"{0}\",", this.getUpdateUser());
        str += MessageFormat.format("Description=\"{0}\",", this.getDescription());
        str += MessageFormat.format("Version=\"{0}\",", this.getVersion());;
        return str;
                        
	}
}

