/**
  * @ cqiyi create in 2014/8/5 18:00:54 by Template
  * This class generated by Forever Web Rapid Framework Code Generator
  */

package org.hhwy.fweb1.domain;

import java.io.Serializable;
import java.text.MessageFormat;
import java.util.Date;

import javax.validation.constraints.NotNull;

import org.apache.commons.lang3.StringUtils;
import org.hhwy.fweb1.core.Utility;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.format.annotation.DateTimeFormat.ISO;

/**
  * 数据表： [t_sys_resource]
  * 系统资源
  */
public class SysResource implements Serializable {

	/*
	 * 默认构造函数
	 */
	public SysResource() {
		this.id = Utility.getRandomUUID(); 
        this.version = -1; 
	}

    /**
      * [id]，
      * ID
      */
      
      private String id;
      
    /**
      * [resource_code]，
      * 资源编码
      */
      
      private String resourceCode;
      
    /**
      * [resource_name]，
      * 资源名称
      */
      
      private String resourceName;
      
    /**
      * [icon]，
      * 图标路径
      */
      
      private String icon;
      
    /**
      * [resource_uri]，
      * URL地址
      */
      
      private String resourceUri;
      
    /**
      * [resource_type]，
      * 资源类型
      */
      
      private String resourceType;
      
    /**
      * [order_id]，
      * 顺序号
      */
      
      private Integer orderId;
      
    /**
      * [parent_id]，
      * 父ID
      */
      
      private String parentId;
      
    /**
      * [enabled]，
      * 是否禁用
      */
      
      private String enabled;
      
    /**
      * [description]，
      * 备注
      */
      
      private String description;
      
    /**
      * [version]，
      * 
      */
      
      private Integer version;
      
    
    /**
      * [id] getter，
      * ID
      */
    	public String getId () {
    		return this.id;
    	}

    /**
      * [id] setter，
      * ID
      */
    	public void setId(String id) {
    		this.id = id;
    	}
    /**
      * [resource_code] getter，
      * 资源编码
      */
    	public String getResourceCode () {
    		return this.resourceCode;
    	}

    /**
      * [resource_code] setter，
      * 资源编码
      */
    	public void setResourceCode(String resourceCode) {
    		this.resourceCode = resourceCode;
    	}
    /**
      * [resource_name] getter，
      * 资源名称
      */
    	public String getResourceName () {
    		return this.resourceName;
    	}

    /**
      * [resource_name] setter，
      * 资源名称
      */
    	public void setResourceName(String resourceName) {
    		this.resourceName = resourceName;
    	}
    /**
      * [icon] getter，
      * 图标路径
      */
    	public String getIcon () {
    		return this.icon;
    	}

    /**
      * [icon] setter，
      * 图标路径
      */
    	public void setIcon(String icon) {
    		this.icon = icon;
    	}
    /**
      * [resource_uri] getter，
      * URL地址
      */
    	public String getResourceUri () {
    		return this.resourceUri;
    	}

    /**
      * [resource_uri] setter，
      * URL地址
      */
    	public void setResourceUri(String resourceUri) {
    		this.resourceUri = resourceUri;
    	}
    /**
      * [resource_type] getter，
      * 资源类型
      */
    	public String getResourceType () {
    		return this.resourceType;
    	}

    /**
      * [resource_type] setter，
      * 资源类型
      */
    	public void setResourceType(String resourceType) {
    		this.resourceType = resourceType;
    	}
    /**
      * [order_id] getter，
      * 顺序号
      */
    	public Integer getOrderId () {
    		return this.orderId;
    	}

    /**
      * [order_id] setter，
      * 顺序号
      */
    	public void setOrderId(Integer orderId) {
    		this.orderId = orderId;
    	}
    /**
      * [parent_id] getter，
      * 父ID
      */
    	public String getParentId () {
    		return this.parentId;
    	}

    /**
      * [parent_id] setter，
      * 父ID
      */
    	public void setParentId(String parentId) {
    		this.parentId = parentId;
    	}
    /**
      * [enabled] getter，
      * 是否禁用
      */
    	public String getEnabled () {
    		return this.enabled;
    	}

    /**
      * [enabled] setter，
      * 是否禁用
      */
    	public void setEnabled(String enabled) {
    		this.enabled = enabled;
    	}
    /**
      * [description] getter，
      * 备注
      */
    	public String getDescription () {
    		return this.description;
    	}

    /**
      * [description] setter，
      * 备注
      */
    	public void setDescription(String description) {
    		this.description = description;
    	}
    /**
      * [version] getter，
      * 
      */
    	public Integer getVersion () {
    		return this.version;
    	}

    /**
      * [version] setter，
      * 
      */
    	public void setVersion(Integer version) {
    		this.version = version;
    	}
    
	@Override
	public String toString() {
		System.out.println(this.getClass().getName() + ".toString():");
        
        String str = StringUtils.EMPTY;
        str += MessageFormat.format("Id=\"{0}\",", StringUtils.trimToEmpty(this.getId()));
        str += MessageFormat.format("ResourceCode=\"{0}\",", StringUtils.trimToEmpty(this.getResourceCode()));
        str += MessageFormat.format("ResourceName=\"{0}\",", StringUtils.trimToEmpty(this.getResourceName()));
        str += MessageFormat.format("Icon=\"{0}\",", StringUtils.trimToEmpty(this.getIcon()));
        str += MessageFormat.format("ResourceUri=\"{0}\",", StringUtils.trimToEmpty(this.getResourceUri()));
        str += MessageFormat.format("ResourceType=\"{0}\",", StringUtils.trimToEmpty(this.getResourceType()));
        str += MessageFormat.format("OrderId=\"{0}\",", this.getOrderId());
        str += MessageFormat.format("ParentId=\"{0}\",", StringUtils.trimToEmpty(this.getParentId()));
        str += MessageFormat.format("Enabled=\"{0}\",", StringUtils.trimToEmpty(this.getEnabled()));
        str += MessageFormat.format("Description=\"{0}\",", StringUtils.trimToEmpty(this.getDescription()));
        str += MessageFormat.format("Version=\"{0}\",", this.getVersion());;
        return str;
                        
	}
}

