/**
  * @ cqiyi create in 2014/7/24 21:26:50 by Template
  * This class generated by Forever Web Rapid Framework Code Generator
  */

package hply.domain;

import java.io.Serializable;
import java.text.MessageFormat;
import java.util.Date;

import javax.validation.constraints.NotNull;

import org.apache.commons.lang3.StringUtils;
import hply.Utility;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.format.annotation.DateTimeFormat.ISO;

/**
  * 数据表： [t_sys_user]
  * 
  */
public class SysUser implements Serializable {

	/*
	 * 默认构造函数
	 */
	public SysUser() {
        this.version = -1;
		this.id = Utility.getRandomUUID();
        
        //设定日期为空时的初始值
        this.lastLoginTime = new Date(0);this.createTime = new Date(0);this.updateTime = new Date(0);
	}

    /**
      * [id]，
      * 
      */
      
      @NotNull
      
      private String id;
      
    /**
      * [login_name]，
      * 
      */
      
      
      
      private String loginName;
      
    /**
      * [real_name]，
      * 
      */
      
      
      
      private String realName;
      
    /**
      * [organization_id]，
      * 
      */
      
      
      
      private String organizationId;
      
    /**
      * [password]，
      * 
      */
      
      
      
      private String password;
      
    /**
      * [last_login_ip]，
      * 
      */
      
      
      
      private String lastLoginIp;
      
    /**
      * [last_login_time]，
      * 
      */
      
      
      @DateTimeFormat(iso=ISO.DATE)
      private Date lastLoginTime;
      
    /**
      * [fails]，
      * 
      */
      
      
      
      private int fails;
      
    /**
      * [logined]，
      * 
      */
      
      
      
      private int logined;
      
    /**
      * [position]，
      * 
      */
      
      
      
      private String position;
      
    /**
      * [enabled]，
      * 
      */
      
      
      
      private int enabled;
      
    /**
      * [order_by]，
      * 
      */
      
      
      
      private int orderBy;
      
    /**
      * [create_time]，
      * 
      */
      
      
      @DateTimeFormat(iso=ISO.DATE)
      private Date createTime;
      
    /**
      * [create_user]，
      * 
      */
      
      
      
      private String createUser;
      
    /**
      * [update_time]，
      * 
      */
      
      
      @DateTimeFormat(iso=ISO.DATE)
      private Date updateTime;
      
    /**
      * [update_user]，
      * 
      */
      
      
      
      private String updateUser;
      
    /**
      * [description]，
      * 
      */
      
      
      
      private String description;
      
    /**
      * [version]，
      * 
      */
      
      @NotNull
      
      private int version;
      
    /**
      * [must_change_password]，
      * 
      */
      
      
      
      private int mustChangePassword;
      
    
    /**
      * [id] getter，
      * 
      */
    	public String getId () {
            return StringUtils.trimToEmpty(id);
    	}

    /**
      * [id] setter，
      * 
      */
    	public void setId(String id) {
    		this.id = id;
    	}
    /**
      * [login_name] getter，
      * 
      */
    	public String getLoginName () {
            return StringUtils.trimToEmpty(loginName);
    	}

    /**
      * [login_name] setter，
      * 
      */
    	public void setLoginName(String loginName) {
    		this.loginName = loginName;
    	}
    /**
      * [real_name] getter，
      * 
      */
    	public String getRealName () {
            return StringUtils.trimToEmpty(realName);
    	}

    /**
      * [real_name] setter，
      * 
      */
    	public void setRealName(String realName) {
    		this.realName = realName;
    	}
    /**
      * [organization_id] getter，
      * 
      */
    	public String getOrganizationId () {
            return StringUtils.trimToEmpty(organizationId);
    	}

    /**
      * [organization_id] setter，
      * 
      */
    	public void setOrganizationId(String organizationId) {
    		this.organizationId = organizationId;
    	}
    /**
      * [password] getter，
      * 
      */
    	public String getPassword () {
            return StringUtils.trimToEmpty(password);
    	}

    /**
      * [password] setter，
      * 
      */
    	public void setPassword(String password) {
    		this.password = password;
    	}
    /**
      * [last_login_ip] getter，
      * 
      */
    	public String getLastLoginIp () {
            return StringUtils.trimToEmpty(lastLoginIp);
    	}

    /**
      * [last_login_ip] setter，
      * 
      */
    	public void setLastLoginIp(String lastLoginIp) {
    		this.lastLoginIp = lastLoginIp;
    	}
    /**
      * [last_login_time] getter，
      * 
      */
    	public Date getLastLoginTime () {
    		return lastLoginTime;
    	}

    /**
      * [last_login_time] setter，
      * 
      */
    	public void setLastLoginTime(Date lastLoginTime) {
    		this.lastLoginTime = lastLoginTime;
    	}
    /**
      * [fails] getter，
      * 
      */
    	public int getFails () {
    		return fails;
    	}

    /**
      * [fails] setter，
      * 
      */
    	public void setFails(int fails) {
    		this.fails = fails;
    	}
    /**
      * [logined] getter，
      * 
      */
    	public int getLogined () {
    		return logined;
    	}

    /**
      * [logined] setter，
      * 
      */
    	public void setLogined(int logined) {
    		this.logined = logined;
    	}
    /**
      * [position] getter，
      * 
      */
    	public String getPosition () {
            return StringUtils.trimToEmpty(position);
    	}

    /**
      * [position] setter，
      * 
      */
    	public void setPosition(String position) {
    		this.position = position;
    	}
    /**
      * [enabled] getter，
      * 
      */
    	public int getEnabled () {
    		return enabled;
    	}

    /**
      * [enabled] setter，
      * 
      */
    	public void setEnabled(int enabled) {
    		this.enabled = enabled;
    	}
    /**
      * [order_by] getter，
      * 
      */
    	public int getOrderBy () {
    		return orderBy;
    	}

    /**
      * [order_by] setter，
      * 
      */
    	public void setOrderBy(int orderBy) {
    		this.orderBy = orderBy;
    	}
    /**
      * [create_time] getter，
      * 
      */
    	public Date getCreateTime () {
    		return createTime;
    	}

    /**
      * [create_time] setter，
      * 
      */
    	public void setCreateTime(Date createTime) {
    		this.createTime = createTime;
    	}
    /**
      * [create_user] getter，
      * 
      */
    	public String getCreateUser () {
            return StringUtils.trimToEmpty(createUser);
    	}

    /**
      * [create_user] setter，
      * 
      */
    	public void setCreateUser(String createUser) {
    		this.createUser = createUser;
    	}
    /**
      * [update_time] getter，
      * 
      */
    	public Date getUpdateTime () {
    		return updateTime;
    	}

    /**
      * [update_time] setter，
      * 
      */
    	public void setUpdateTime(Date updateTime) {
    		this.updateTime = updateTime;
    	}
    /**
      * [update_user] getter，
      * 
      */
    	public String getUpdateUser () {
            return StringUtils.trimToEmpty(updateUser);
    	}

    /**
      * [update_user] setter，
      * 
      */
    	public void setUpdateUser(String updateUser) {
    		this.updateUser = updateUser;
    	}
    /**
      * [description] getter，
      * 
      */
    	public String getDescription () {
            return StringUtils.trimToEmpty(description);
    	}

    /**
      * [description] setter，
      * 
      */
    	public void setDescription(String description) {
    		this.description = description;
    	}
    /**
      * [version] getter，
      * 
      */
    	public int getVersion () {
    		return version;
    	}

    /**
      * [version] setter，
      * 
      */
    	public void setVersion(int version) {
    		this.version = version;
    	}
    /**
      * [must_change_password] getter，
      * 
      */
    	public int getMustChangePassword () {
    		return mustChangePassword;
    	}

    /**
      * [must_change_password] setter，
      * 
      */
    	public void setMustChangePassword(int mustChangePassword) {
    		this.mustChangePassword = mustChangePassword;
    	}
    
	@Override
	public String toString() {
		System.out.println(this.getClass().getName() + ".toString():");
        
        String str = StringUtils.EMPTY;
        str += MessageFormat.format("Id=\"{0}\",", this.getId());
        str += MessageFormat.format("LoginName=\"{0}\",", this.getLoginName());
        str += MessageFormat.format("RealName=\"{0}\",", this.getRealName());
        str += MessageFormat.format("OrganizationId=\"{0}\",", this.getOrganizationId());
        str += MessageFormat.format("Password=\"{0}\",", this.getPassword());
        str += MessageFormat.format("LastLoginIp=\"{0}\",", this.getLastLoginIp());
        str += MessageFormat.format("LastLoginTime=\"{0}\",", this.getLastLoginTime());
        str += MessageFormat.format("Fails=\"{0}\",", this.getFails());
        str += MessageFormat.format("Logined=\"{0}\",", this.getLogined());
        str += MessageFormat.format("Position=\"{0}\",", this.getPosition());
        str += MessageFormat.format("Enabled=\"{0}\",", this.getEnabled());
        str += MessageFormat.format("OrderBy=\"{0}\",", this.getOrderBy());
        str += MessageFormat.format("CreateTime=\"{0}\",", this.getCreateTime());
        str += MessageFormat.format("CreateUser=\"{0}\",", this.getCreateUser());
        str += MessageFormat.format("UpdateTime=\"{0}\",", this.getUpdateTime());
        str += MessageFormat.format("UpdateUser=\"{0}\",", this.getUpdateUser());
        str += MessageFormat.format("Description=\"{0}\",", this.getDescription());
        str += MessageFormat.format("Version=\"{0}\",", this.getVersion());
        str += MessageFormat.format("MustChangePassword=\"{0}\",", this.getMustChangePassword());;
        return str;
                        
	}
}

