CREATE DATABASE 'localhost:D:\bjhp.cqy'
USER 'sysdba' PASSWORD 'masterkey';

CREATE USER USER01 PASSWORD 'qqw';

--Table: T_SYS_CACHE
--DROP TABLE T_SYS_CACHE;
CREATE TABLE T_SYS_CACHE (
  ID           CHAR(36) NOT NULL,
  LOCATION     VARCHAR(500),
  "DATA"       VARCHAR(1000),
  CREATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  /* Keys */
  PRIMARY KEY (ID)
);

GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES
  ON TABLE T_SYS_CACHE
TO USER01 WITH GRANT OPTION;

--Table: T_SYS_LOG
--DROP TABLE T_SYS_LOG;
CREATE TABLE T_SYS_LOG (
  ID           CHAR(36) NOT NULL,
  LOCATION     VARCHAR(500),
  "MESSAGE"    VARCHAR(1000),
  LOG_TYPE     VARCHAR(200),
  CREATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  /* Keys */
  PRIMARY KEY (ID)
);

GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES
  ON TABLE T_SYS_LOG
TO USER01 WITH GRANT OPTION;

--Table: T_SYS_USER
--DROP TABLE T_SYS_USER;
CREATE TABLE T_SYS_USER (
  ID               CHAR(36) NOT NULL,
  LOGIN_NAME       VARCHAR(200),
  REAL_NAME        VARCHAR(200),
  "PASSWORD"       VARCHAR(200),
  CREATE_TIME      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  LOGIN_COUNT      INTEGER DEFAULT 0,
  LAST_FAIL_COUNT  INTEGER DEFAULT 0,
  LAST_LOGIN_TIME  INTEGER,
  /* Keys */
  PRIMARY KEY (ID), 
  CONSTRAINT T_SYS_USER_INDEX01
    UNIQUE (LOGIN_NAME)
);

GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES
  ON TABLE T_SYS_USER
TO USER01 WITH GRANT OPTION;

insert into t_sys_user(id, login_name, real_name, password) values('21AFE4A7_EB87_48DF_B757D5FC61A9C8F8', 'user1', '成七一', '123');
insert into t_sys_user(id, login_name, real_name, password) values('9F4E1F27_3CFB_437B_AD4390971BF9B37A', 'user2', '孙月萍', '123');
insert into t_sys_user(id, login_name, real_name, password) values('AEBC6E75_70F1_4E85_BE86E626A7F8F2ED', 'system', '系统管理员', '123');

select * from t_sys_user;