/**
  * @Template info: 2013/08/16, Chengqiyi.
  * ChengQiyi create in 2014-7-13 15:02:00
  * This class generated by CodeSmith Generator
  */

package hply.service;

import java.util.List;
import java.util.Map;
import javax.annotation.Resource;
import org.springframework.stereotype.Repository;
import hply.persistence.ArrearsMapper;

import hply.domain.Arrears;

@Repository(value = "arrearsService")
public class ArrearsService {
    
    @Resource(name = "arrearsMapper")
    private ArrearsMapper arrearsMapper;

	  public void insert(Arrears arrears){
        arrearsMapper.insert(arrears);
      }
	  
	  public void update(Arrears arrears){
        arrearsMapper.update(arrears);
      
      }
	  
	  public void delete(String id){
        arrearsMapper.delete(id);
      }
	  
	  public Arrears get(String id){
        return arrearsMapper.get(id);
      }
	  
	  public List<Arrears> getAll(){
        return arrearsMapper.getAll();
      }
}


