/**
 * @Template info: 2013/08/16, Chengqiyi.
 * ChengQiyi create in 2014-7-13 15:02:00
 * This class generated by CodeSmith Generator
 */

package hply.service;

import hply.domain.ContractSupplementalAgreement;
import hply.persistence.ContractSupplementalAgreementMapper;

import java.util.List;

import javax.annotation.Resource;

import org.springframework.stereotype.Repository;

@Repository(value = "contractSupplementalAgreementService")
public class ContractSupplementalAgreementService {

	@Resource(name = "contractSupplementalAgreementMapper")
	private ContractSupplementalAgreementMapper contractSupplementalAgreementMapper;

	public void insert(
			ContractSupplementalAgreement contractSupplementalAgreement) {
		contractSupplementalAgreementMapper
				.insert(contractSupplementalAgreement);
	}

	public void update(
			ContractSupplementalAgreement contractSupplementalAgreement) {
		contractSupplementalAgreementMapper
				.update(contractSupplementalAgreement);

	}

	public void delete(String id) {
		contractSupplementalAgreementMapper.delete(id);
	}

	public ContractSupplementalAgreement get(String id) {
		return contractSupplementalAgreementMapper.get(id);
	}

	public List<ContractSupplementalAgreement> getAll() {
		return contractSupplementalAgreementMapper.getAll();
	}
}
