/**
 * @Template info: 2013/08/16, Chengqiyi.
 * ChengQiyi create in 2014-7-13 15:02:00
 * This class generated by CodeSmith Generator
 */

package hply.service;

import hply.domain.CustomerBilling;
import hply.persistence.CustomerBillingMapper;

import java.util.List;

import javax.annotation.Resource;

import org.springframework.stereotype.Repository;

@Repository(value = "customerBillingService")
public class CustomerBillingService {

	@Resource(name = "customerBillingMapper")
	private CustomerBillingMapper customerBillingMapper;

	public void insert(CustomerBilling customerBilling) {
		customerBillingMapper.insert(customerBilling);
	}

	public void update(CustomerBilling customerBilling) {
		customerBillingMapper.update(customerBilling);

	}

	public void delete(String id) {
		customerBillingMapper.delete(id);
	}

	public CustomerBilling get(String id) {
		return customerBillingMapper.get(id);
	}

	public List<CustomerBilling> getAll() {
		return customerBillingMapper.getAll();
	}
}
