/**
 * @Template info: 2013/08/16, Chengqiyi.
 * ChengQiyi create in 2014-7-13 15:02:00
 * This class generated by CodeSmith Generator
 */

package hply.service;

import hply.domain.Information;
import hply.persistence.InformationMapper;

import java.util.List;

import javax.annotation.Resource;

import org.springframework.stereotype.Repository;

@Repository(value = "informationService")
public class InformationService {

	@Resource(name = "informationMapper")
	private InformationMapper informationMapper;

	public void insert(Information information) {
		informationMapper.insert(information);
	}

	public void update(Information information) {
		informationMapper.update(information);

	}

	public void delete(String id) {
		informationMapper.delete(id);
	}

	public Information get(String id) {
		return informationMapper.get(id);
	}

	public List<Information> getAll() {
		return informationMapper.getAll();
	}
}
