/**
 * @Template info: 2013/08/16, Chengqiyi.
 * ChengQiyi create in 2014-7-13 15:02:00
 * This class generated by CodeSmith Generator
 */

package hply.service;

import hply.domain.PartyBilling;
import hply.persistence.PartyBillingMapper;

import java.util.List;

import javax.annotation.Resource;

import org.springframework.stereotype.Repository;

@Repository(value = "partyBillingService")
public class PartyBillingService {

	@Resource(name = "partyBillingMapper")
	private PartyBillingMapper partyBillingMapper;

	public void insert(PartyBilling partyBilling) {
		partyBillingMapper.insert(partyBilling);
	}

	public void update(PartyBilling partyBilling) {
		partyBillingMapper.update(partyBilling);

	}

	public void delete(String id) {
		partyBillingMapper.delete(id);
	}

	public PartyBilling get(String id) {
		return partyBillingMapper.get(id);
	}

	public List<PartyBilling> getAll() {
		return partyBillingMapper.getAll();
	}
}
