/**
 * @Template info: 2013/08/16, Chengqiyi.
 * ChengQiyi create in 2014/7/8 8:24:25
 * This class generated by CodeSmith Generator
 */

package hply.service;

import hply.domain.SysAuthorization;
import hply.persistence.SysAuthorizationMapper;
import java.util.List;
import javax.annotation.Resource;
import org.springframework.stereotype.Repository;


@Repository(value = "sysAuthorizationService")
public class SysAuthorizationService {

	@Resource(name = "sysAuthorizationMapper")
	private SysAuthorizationMapper sysAuthorizationMapper;

	public void insert(SysAuthorization sysAuthorization) {

	}

	public void update(SysAuthorization sysAuthorization) {

	}

	public void delete(SysAuthorization sysAuthorization) {

	}

	public SysAuthorization get(String id) {
		return null;
	}

	public List<SysAuthorization> getAll() {
		return null;
	}
}
