/**
 * @Template info: 2013/08/16, Chengqiyi.
 * ChengQiyi create in 2014-7-13 15:02:00
 * This class generated by CodeSmith Generator
 */

package hply.service;

import hply.domain.SysAuthorization;
import hply.persistence.SysAuthorizationMapper;

import java.util.List;

import javax.annotation.Resource;

import org.springframework.stereotype.Repository;

@Repository(value = "sysAuthorizationService")
public class SysAuthorizationService {

	@Resource(name = "sysAuthorizationMapper")
	private SysAuthorizationMapper sysAuthorizationMapper;

	public void insert(SysAuthorization sysAuthorization) {
		sysAuthorizationMapper.insert(sysAuthorization);
	}

	public void update(SysAuthorization sysAuthorization) {
		sysAuthorizationMapper.update(sysAuthorization);

	}

	public void delete(String id) {
		sysAuthorizationMapper.delete(id);
	}

	public SysAuthorization get(String id) {
		return sysAuthorizationMapper.get(id);
	}

	public List<SysAuthorization> getAll() {
		return sysAuthorizationMapper.getAll();
	}
}
