/**
  * @Template info: 2013/08/16, Chengqiyi.
  * ChengQiyi create in 2014/7/8 14:30:21
  * This class generated by CodeSmith Generator
  */

package hply.service;

import hply.domain.SysResource;
import hply.domain.TreeNode;
import hply.persistence.SysResourceMapper;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.stereotype.Repository;

@Repository(value = "sysResourceService")
public class SysResourceService {
	
	private final static String ROOT_PARENT_ID = "ROOT";
    
    @Resource(name = "sysResourceMapper")
    private SysResourceMapper sysResourceMapper;

	  public void insert(SysResource sysResource){
        sysResourceMapper.insert(sysResource);
      }
	  
	  public void update(SysResource sysResource){
        sysResourceMapper.update(sysResource);
      
      }
	  
	  public void delete(String id){
        sysResourceMapper.delete(id);
      }
	  
	  public SysResource get(String id){
        return sysResourceMapper.get(id);
      }
	  
	  public List<SysResource> getChildren(String id){
		  return sysResourceMapper.getChildren(id);
	  }
	  
	  public List<SysResource> getAll(){
        return sysResourceMapper.getAll();
      }
	  
	  public List<TreeNode> getTreeNodeList(String userId){
		  String pid = ROOT_PARENT_ID;
		  
		  List<SysResource> list1 = this.getChildren(pid);		  
		  List<TreeNode> list = new ArrayList<TreeNode>();
		  for(SysResource item : list1){
			  TreeNode node = new TreeNode();
			  node.setId(item.getId());
			  node.setTitle(item.getResName());
		  }
		  
		  
		  
		  return root;
		  
		  
	  }
}


