/**
  * @Template info: 2013/08/16, Chengqiyi.
  * ChengQiyi create in 2014/7/8 14:30:08
  * This class generated by CodeSmith Generator
  */

package hply.service;

import hply.domain.SysUser;
import hply.persistence.SysUserMapper;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class SysUserService {
    
	@Autowired
    private SysUserMapper sysUserMapper;

	  public void insert(SysUser sysUser){
        sysUserMapper.insert(sysUser);
      }
	  
	  public void update(SysUser sysUser){
        sysUserMapper.update(sysUser);
      
      }
	  
	  public void delete(String id){
        sysUserMapper.delete(id);
      }
	  
	  public SysUser get(String id){
        return sysUserMapper.get(id);
      }
	  
	  public List<SysUser> getAll(){
        return sysUserMapper.getAll();
      }
}


