/**
  * @ ChengQiyi create in 2014-7-13 16:09:15 by Template at 2014年6月25日21:26:55
  * This class generated by CodeSmith Generator
  */

package hply.domain;

import java.io.Serializable;
import java.util.Date;
import java.text.MessageFormat;
import hply.common.Utility;
import org.apache.commons.lang3.StringUtils;


/**
  * 模型类，对应的数据库表： [t_information]
  * 
  */
public class Information implements Serializable {
        
  private String id;
  
/**
  * 读，数据库列： ID  
  * 
  */
	public String getId() {
        return StringUtils.trimToEmpty(id);
	}

/**
  * 写，数据库列：ID  
  * 
  */
	public void setId(String id) {
		this.id = id;
	}
		
        
  private String organizationid;
  
/**
  * 读，数据库列： OrganizationID  
  * 
  */
	public String getOrganizationid() {
        return StringUtils.trimToEmpty(organizationid);
	}

/**
  * 写，数据库列：OrganizationID  
  * 
  */
	public void setOrganizationid(String organizationid) {
		this.organizationid = organizationid;
	}
		
        
  private String projectname;
  
/**
  * 读，数据库列： ProjectName  
  * 
  */
	public String getProjectname() {
        return StringUtils.trimToEmpty(projectname);
	}

/**
  * 写，数据库列：ProjectName  
  * 
  */
	public void setProjectname(String projectname) {
		this.projectname = projectname;
	}
		
        
  private String address;
  
/**
  * 读，数据库列： Address  
  * 
  */
	public String getAddress() {
        return StringUtils.trimToEmpty(address);
	}

/**
  * 写，数据库列：Address  
  * 
  */
	public void setAddress(String address) {
		this.address = address;
	}
		
        
  private String developer;
  
/**
  * 读，数据库列： Developer  
  * 
  */
	public String getDeveloper() {
        return StringUtils.trimToEmpty(developer);
	}

/**
  * 写，数据库列：Developer  
  * 
  */
	public void setDeveloper(String developer) {
		this.developer = developer;
	}
		
        
  private String epccorporation;
  
/**
  * 读，数据库列： EpcCorporation  
  * 
  */
	public String getEpccorporation() {
        return StringUtils.trimToEmpty(epccorporation);
	}

/**
  * 写，数据库列：EpcCorporation  
  * 
  */
	public void setEpccorporation(String epccorporation) {
		this.epccorporation = epccorporation;
	}
		
        
  private String variety;
  
/**
  * 读，数据库列： Variety  
  * 
  */
	public String getVariety() {
        return StringUtils.trimToEmpty(variety);
	}

/**
  * 写，数据库列：Variety  
  * 
  */
	public void setVariety(String variety) {
		this.variety = variety;
	}
		
        
  private String totalarea;
  
/**
  * 读，数据库列： TotalArea  
  * 
  */
	public String getTotalarea() {
        return StringUtils.trimToEmpty(totalarea);
	}

/**
  * 写，数据库列：TotalArea  
  * 
  */
	public void setTotalarea(String totalarea) {
		this.totalarea = totalarea;
	}
		
        
  private String realname;
  
/**
  * 读，数据库列： RealName  
  * 
  */
	public String getRealname() {
        return StringUtils.trimToEmpty(realname);
	}

/**
  * 写，数据库列：RealName  
  * 
  */
	public void setRealname(String realname) {
		this.realname = realname;
	}
		
        
  private String identification;
  
/**
  * 读，数据库列： Identification  
  * 
  */
	public String getIdentification() {
        return StringUtils.trimToEmpty(identification);
	}

/**
  * 写，数据库列：Identification  
  * 
  */
	public void setIdentification(String identification) {
		this.identification = identification;
	}
		
        
  private String contact;
  
/**
  * 读，数据库列： Contact  
  * 
  */
	public String getContact() {
        return StringUtils.trimToEmpty(contact);
	}

/**
  * 写，数据库列：Contact  
  * 
  */
	public void setContact(String contact) {
		this.contact = contact;
	}
		
        
  private String subscriber;
  
/**
  * 读，数据库列： Subscriber  
  * 
  */
	public String getSubscriber() {
        return StringUtils.trimToEmpty(subscriber);
	}

/**
  * 写，数据库列：Subscriber  
  * 
  */
	public void setSubscriber(String subscriber) {
		this.subscriber = subscriber;
	}
		
        
  private Date trice;
  
/**
  * 读，数据库列： Trice  
  * 
  */
	public Date getTrice() {
		return trice;
	}

/**
  * 写，数据库列：Trice  
  * 
  */
	public void setTrice(Date trice) {
		this.trice = trice;
	}
		
        
  private Date createtime;
  
/**
  * 读，数据库列： CreateTime  
  * 
  */
	public Date getCreatetime() {
		return createtime;
	}

/**
  * 写，数据库列：CreateTime  
  * 
  */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}
		
        
  private String createuser;
  
/**
  * 读，数据库列： CreateUser  
  * 
  */
	public String getCreateuser() {
        return StringUtils.trimToEmpty(createuser);
	}

/**
  * 写，数据库列：CreateUser  
  * 
  */
	public void setCreateuser(String createuser) {
		this.createuser = createuser;
	}
		
        
  private Date updatetime;
  
/**
  * 读，数据库列： UpdateTime  
  * 
  */
	public Date getUpdatetime() {
		return updatetime;
	}

/**
  * 写，数据库列：UpdateTime  
  * 
  */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}
		
        
  private String updateuser;
  
/**
  * 读，数据库列： UpdateUser  
  * 
  */
	public String getUpdateuser() {
        return StringUtils.trimToEmpty(updateuser);
	}

/**
  * 写，数据库列：UpdateUser  
  * 
  */
	public void setUpdateuser(String updateuser) {
		this.updateuser = updateuser;
	}
		
        
  private String description;
  
/**
  * 读，数据库列： Description  
  * 
  */
	public String getDescription() {
        return StringUtils.trimToEmpty(description);
	}

/**
  * 写，数据库列：Description  
  * 
  */
	public void setDescription(String description) {
		this.description = description;
	}
		
        
    @Override
	public String toString() {
		System.out.println(this.getClass().getName() + ".toString():");
        
        String str = Utility.EMPTY_STRING;
        str += MessageFormat.format("\tId=\"{0}\"\n", this.getId());
        str += MessageFormat.format("\tOrganizationid=\"{0}\"\n", this.getOrganizationid());
        str += MessageFormat.format("\tProjectname=\"{0}\"\n", this.getProjectname());
        str += MessageFormat.format("\tAddress=\"{0}\"\n", this.getAddress());
        str += MessageFormat.format("\tDeveloper=\"{0}\"\n", this.getDeveloper());
        str += MessageFormat.format("\tEpccorporation=\"{0}\"\n", this.getEpccorporation());
        str += MessageFormat.format("\tVariety=\"{0}\"\n", this.getVariety());
        str += MessageFormat.format("\tTotalarea=\"{0}\"\n", this.getTotalarea());
        str += MessageFormat.format("\tRealname=\"{0}\"\n", this.getRealname());
        str += MessageFormat.format("\tIdentification=\"{0}\"\n", this.getIdentification());
        str += MessageFormat.format("\tContact=\"{0}\"\n", this.getContact());
        str += MessageFormat.format("\tSubscriber=\"{0}\"\n", this.getSubscriber());
        str += MessageFormat.format("\tTrice=\"{0}\"\n", this.getTrice());
        str += MessageFormat.format("\tCreatetime=\"{0}\"\n", this.getCreatetime());
        str += MessageFormat.format("\tCreateuser=\"{0}\"\n", this.getCreateuser());
        str += MessageFormat.format("\tUpdatetime=\"{0}\"\n", this.getUpdatetime());
        str += MessageFormat.format("\tUpdateuser=\"{0}\"\n", this.getUpdateuser());
        str += MessageFormat.format("\tDescription=\"{0}\"\n", this.getDescription());;
        return str;
                        
	}

}

