/**
 * @ cqiyi create in 2014/8/15 10:25:23 by Template
 * This class generated by Forever Web Rapid Framework Code Generator
 */

package com.hhwy.fresource2.domain;

import java.io.Serializable;
import java.text.MessageFormat;
import java.util.Date;

import org.apache.commons.lang3.StringUtils;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.format.annotation.DateTimeFormat.ISO;

import com.hhwy.fresource2.core.Utility;

/**
 * 数据表： [t_field_types] 一个Demo测试样表
 */
public class FieldTypes implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6955277473398989626L;

	/*
	 * 默认构造函数
	 */
	public FieldTypes() {
		this.id = Utility.getRandomUUID();
		this.version = -1;
	}

	/**
	 * [id]， 主键
	 */

	private String id;

	/**
	 * [field_t01]， 字段一
	 */

	private String fieldT01;

	/**
	 * [field_t02]， 字段二
	 */

	private double fieldT02;

	/**
	 * [field_t03]， 字段三
	 */
	@DateTimeFormat(iso = ISO.DATE)
	private Date fieldT03;

	/**
	 * [field_t04]， 字段四
	 */

	private double fieldT04;

	/**
	 * [field_t05]， 自端午
	 */

	private boolean fieldT05;

	/**
	 * [field_t06]， 字段六
	 */
	@DateTimeFormat(iso = ISO.DATE)
	private Date fieldT06;

	/**
	 * [field_t07]， 字段七
	 */

	private double fieldT07;

	/**
	 * [field_t08]， 字段八
	 */

	private Integer fieldT08;

	/**
	 * [version]，
	 * 
	 */

	private Integer version;

	/**
	 * [id] getter， 主键
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * [id] setter， 主键
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * [field_t01] getter， 字段一
	 */
	public String getFieldT01() {
		return this.fieldT01;
	}

	/**
	 * [field_t01] setter， 字段一
	 */
	public void setFieldT01(String fieldT01) {
		this.fieldT01 = fieldT01;
	}

	/**
	 * [field_t02] getter， 字段二
	 */
	public double getFieldT02() {
		return this.fieldT02;
	}

	/**
	 * [field_t02] setter， 字段二
	 */
	public void setFieldT02(double fieldT02) {
		this.fieldT02 = fieldT02;
	}

	/**
	 * [field_t03] getter， 字段三
	 */
	public Date getFieldT03() {
		return this.fieldT03;
	}

	/**
	 * [field_t03] setter， 字段三
	 */
	public void setFieldT03(Date fieldT03) {
		this.fieldT03 = fieldT03;
	}

	/**
	 * [field_t04] getter， 字段四
	 */
	public double getFieldT04() {
		return this.fieldT04;
	}

	/**
	 * [field_t04] setter， 字段四
	 */
	public void setFieldT04(double fieldT04) {
		this.fieldT04 = fieldT04;
	}

	/**
	 * [field_t05] getter， 自端午
	 */
	public boolean getFieldT05() {
		return this.fieldT05;
	}

	/**
	 * [field_t05] setter， 自端午
	 */
	public void setFieldT05(boolean fieldT05) {
		this.fieldT05 = fieldT05;
	}

	/**
	 * [field_t06] getter， 字段六
	 */
	public Date getFieldT06() {
		return this.fieldT06;
	}

	/**
	 * [field_t06] setter， 字段六
	 */
	public void setFieldT06(Date fieldT06) {
		this.fieldT06 = fieldT06;
	}

	/**
	 * [field_t07] getter， 字段七
	 */
	public double getFieldT07() {
		return this.fieldT07;
	}

	/**
	 * [field_t07] setter， 字段七
	 */
	public void setFieldT07(double fieldT07) {
		this.fieldT07 = fieldT07;
	}

	/**
	 * [field_t08] getter， 字段八
	 */
	public Integer getFieldT08() {
		return this.fieldT08;
	}

	/**
	 * [field_t08] setter， 字段八
	 */
	public void setFieldT08(Integer fieldT08) {
		this.fieldT08 = fieldT08;
	}

	/**
	 * [version] getter，
	 * 
	 */
	public Integer getVersion() {
		return this.version;
	}

	/**
	 * [version] setter，
	 * 
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	@Override
	public String toString() {
		System.out.println(this.getClass().getName() + ".toString():");

		String str = StringUtils.EMPTY;
		str += MessageFormat.format("Id=\"{0}\",",
				StringUtils.trimToEmpty(this.getId()));
		str += MessageFormat.format("FieldT01=\"{0}\",",
				StringUtils.trimToEmpty(this.getFieldT01()));
		str += MessageFormat.format("FieldT02=\"{0}\",", this.getFieldT02());
		str += MessageFormat.format("FieldT03=\"{0}\",", this.getFieldT03());
		str += MessageFormat.format("FieldT04=\"{0}\",", this.getFieldT04());
		str += MessageFormat.format("FieldT05=\"{0}\",", this.getFieldT05());
		str += MessageFormat.format("FieldT06=\"{0}\",", this.getFieldT06());
		str += MessageFormat.format("FieldT07=\"{0}\",", this.getFieldT07());
		str += MessageFormat.format("FieldT08=\"{0}\",", this.getFieldT08());
		str += MessageFormat.format("Version=\"{0}\",", this.getVersion());
		;
		return str;

	}
}
