/**
  * @ cqiyi create in 2014/8/4 18:33:52 by Template
  * This class generated by Forever Web Rapid Framework Code Generator
  */

package org.hhwy.fweb1.domain;

import java.io.Serializable;
import java.text.MessageFormat;
import java.util.Date;

import javax.validation.constraints.NotNull;

import org.apache.commons.lang3.StringUtils;
import org.hhwy.fweb1.core.Utility;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.format.annotation.DateTimeFormat.ISO;

/**
  * 数据表： [t_sys_role]
  * 系统角色表
  */
public class SysRole implements Serializable {

	/*
	 * 默认构造函数
	 */
	public SysRole() {
		this.id = Utility.getRandomUUID();
        this.version = -1;
	}

    /**
      * [id]，
      * 主键
      */
      
      private String id;
      
    /**
      * [name]，
      * 角色名称
      */
      
      private String name;
      
    /**
      * [description]，
      * 描述
      */
      
      private String description;
      
    /**
      * [is_default]，
      * 是否是默认角色
      */
      
      private String isDefault;
      
    /**
      * [version]，
      * 
      */
      
      private Integer version;
      
    
    /**
      * [id] getter，
      * 主键
      */
    	public String getId () {
    		return this.id;
    	}

    /**
      * [id] setter，
      * 主键
      */
    	public void setId(String id) {
    		this.id = id;
    	}
    /**
      * [name] getter，
      * 角色名称
      */
    	public String getName () {
    		return this.name;
    	}

    /**
      * [name] setter，
      * 角色名称
      */
    	public void setName(String name) {
    		this.name = name;
    	}
    /**
      * [description] getter，
      * 描述
      */
    	public String getDescription () {
    		return this.description;
    	}

    /**
      * [description] setter，
      * 描述
      */
    	public void setDescription(String description) {
    		this.description = description;
    	}
    /**
      * [is_default] getter，
      * 是否是默认角色
      */
    	public String getIsDefault () {
    		return this.isDefault;
    	}

    /**
      * [is_default] setter，
      * 是否是默认角色
      */
    	public void setIsDefault(String isDefault) {
    		this.isDefault = isDefault;
    	}
    /**
      * [version] getter，
      * 
      */
    	public Integer getVersion () {
    		return this.version;
    	}

    /**
      * [version] setter，
      * 
      */
    	public void setVersion(Integer version) {
    		this.version = version;
    	}
    
	@Override
	public String toString() {
		System.out.println(this.getClass().getName() + ".toString():");
        
        String str = StringUtils.EMPTY;
        str += MessageFormat.format("Id=\"{0}\",", StringUtils.trimToEmpty(this.getId()));
        str += MessageFormat.format("Name=\"{0}\",", StringUtils.trimToEmpty(this.getName()));
        str += MessageFormat.format("Description=\"{0}\",", StringUtils.trimToEmpty(this.getDescription()));
        str += MessageFormat.format("IsDefault=\"{0}\",", StringUtils.trimToEmpty(this.getIsDefault()));
        str += MessageFormat.format("Version=\"{0}\",", this.getVersion());;
        return str;
                        
	}
}

