/**
  * @ cqiyi create in 2014/8/5 18:07:40 by Template
  * This class generated by Forever Web Rapid Framework Code Generator
  */
  
package org.hhwy.fweb1.mapper.partial;

import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;
import org.hhwy.fweb1.domain.SysRoleUser;



/**
  * 数据表： [t_sys_role_user]
  * 角色与用户的对应表，多对多
  */
@Repository
public interface PartialSysRoleUserMapper {

	  public void insert(SysRoleUser sysRoleUser);
	  
	  public void update(SysRoleUser sysRoleUser);
	  
	  public void delete(String id);
	  
	  public SysRoleUser get(String id);
      
	  public int getVersion(String id);
	  
	  public List<SysRoleUser> getAll();
}

