/**
  * @ cqiyi create in 2014/7/17 20:31:35 by Template
  * This class generated by Forever Web Rapid Framework Code Generator
  */
  
package org.hhwy.rdc.fweb1.mapper;

import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;
import org.hhwy.rdc.fweb1.domain.SysResource;



/**
  * 数据表： [t_sys_resource]
  * 12_系统资源
  */
@Repository
public interface SysResourceMapper {

	  public void insert(SysResource sysResource);
	  
	  public void update(SysResource sysResource);
	  
	  public void delete(String id);
	  
	  public SysResource get(String id);
      
	  public int getVersion(String id);
	  
	  public List<SysResource> getAll();
}

