/**
  * @Template info: 2013/08/16, Chengqiyi.
  * ChengQiyi create in 2014-7-13 16:09:18
  * This class generated by CodeSmith Generator
  */

package hply.persistence;

import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;
import hply.domain.Arrears;

@Repository(value = "arrearsMapper")
public interface ArrearsMapper {

	  public void insert(Arrears arrears);
	  
	  public void update(Arrears arrears);
	  
	  public void delete(String id);
	  
	  public Arrears get(String id);
	  
	  public List<Arrears> getAll();
}


