/**
  * @Template info: 2013/08/16, Chengqiyi.
  * ChengQiyi create in 2014-7-13 16:09:18
  * This class generated by CodeSmith Generator
  */

package hply.persistence;

import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;
import hply.domain.ContractSupplementalAgreement;

@Repository(value = "contractSupplementalAgreementMapper")
public interface ContractSupplementalAgreementMapper {

	  public void insert(ContractSupplementalAgreement contractSupplementalAgreement);
	  
	  public void update(ContractSupplementalAgreement contractSupplementalAgreement);
	  
	  public void delete(String id);
	  
	  public ContractSupplementalAgreement get(String id);
	  
	  public List<ContractSupplementalAgreement> getAll();
}


