/**
  * @Template info: 2013/08/16, Chengqiyi.
  * ChengQiyi create in 2014-7-13 16:09:18
  * This class generated by CodeSmith Generator
  */

package hply.persistence;

import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;
import hply.domain.PartyBilling;

@Repository(value = "partyBillingMapper")
public interface PartyBillingMapper {

	  public void insert(PartyBilling partyBilling);
	  
	  public void update(PartyBilling partyBilling);
	  
	  public void delete(String id);
	  
	  public PartyBilling get(String id);
	  
	  public List<PartyBilling> getAll();
}


