/**
  * @ cqiyi create in 2014-8-5 20:27:38 by Template
  * This class generated by Forever Web Rapid Framework Code Generator
  */
  
package hply.mapper;

import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;
import hply.domain.Collections;
import hply.mapper.partial.PartialCollectionsMapper;



/**
  * 数据表： [t_collections]
  * 05_收款情况
  */
@Repository
public interface CollectionsMapper extends PartialCollectionsMapper {

}

