/**
  * @ cqiyi create in 2014-8-5 20:27:38 by Template
  * This class generated by Forever Web Rapid Framework Code Generator
  */
  
package hply.mapper;

import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;
import hply.domain.FieldTypes;
import hply.mapper.partial.PartialFieldTypesMapper;



/**
  * 数据表： [t_field_types]
  * 所有数据类型的测试样表
  */
@Repository
public interface FieldTypesMapper extends PartialFieldTypesMapper {

}

