/**
  * @ cqiyi create in 2014-8-5 20:27:38 by Template
  * This class generated by Forever Web Rapid Framework Code Generator
  */
  
package hply.mapper;

import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;
import hply.domain.PaymentItem;
import hply.mapper.partial.PartialPaymentItemMapper;



/**
  * 数据表： [t_payment_item]
  * 06+A_付款科目
  */
@Repository
public interface PaymentItemMapper extends PartialPaymentItemMapper {

}

