/**
  * @ cqiyi create in 2014-8-5 20:27:38 by Template
  * This class generated by Forever Web Rapid Framework Code Generator
  */
  
package hply.mapper;

import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;
import hply.domain.Project;
import hply.mapper.partial.PartialProjectMapper;



/**
  * 数据表： [t_project]
  * 01_合同项目信息
  */
@Repository
public interface ProjectMapper extends PartialProjectMapper {

}

