/**
  * @ cqiyi create in 2014-8-5 20:27:38 by Template
  * This class generated by Forever Web Rapid Framework Code Generator
  */
  
package hply.mapper;

import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;
import hply.domain.SysParameter;
import hply.mapper.partial.PartialSysParameterMapper;



/**
  * 数据表： [t_sys_parameter]
  * 14_系统参数
  */
@Repository
public interface SysParameterMapper extends PartialSysParameterMapper {

}

