/**
 * @ cqiyi create in 2014/8/15 10:25:23 by Template
 * This class generated by Forever Web Rapid Framework Code Generator
 */

package com.hhwy.fresource2.mapper.partial;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.hhwy.fresource2.domain.FieldTypes;

/**
 * 数据表： [t_field_types] 一个Demo测试样表
 */
@Repository
public interface PartialFieldTypesMapper {

	public void insert(FieldTypes fieldTypes);

	public void update(FieldTypes fieldTypes);

	public void delete(String id);

	public FieldTypes get(String id);

	public int getVersion(String id);

	public List<FieldTypes> getAll();
}
