CREATE DEFINER=`root`@`localhost` TRIGGER `hplydb`.`tr_arrears` AFTER INSERT ON hplydb.t_arrears FOR EACH ROW
BEGIN
	
INSERT INTO `t_project_summary`
(`id`,
`trice`,
`description`,
`project_id`,
`organization_id`,
`project_code`,
`project_name`,
`contract_amount`,
`change_amount`,
`change_total_amount`,
`settlement_amount`,
`management_rate`,
`management_plan_amount`,
`management_real_amount`,
`management_total_amount`,
`management_owe_amount`,
`party_billing_amount`,
`party_billing_total_amount`,
`collections_amount`,
`collections_total_amount`,
`collections_rate`,
`customer_billing_amount`,
`customer_billing_total_amount`,
`payment_amount`,
`payment_total_amount`,
`tax_rate`,
`tax_plan_amount`,
`tax_real_amount`,
`tax_total_amount`,
`tax_owe_amount`,
`arrears_amount`,
`expected_value`,
`profile_point`,
`version`,
`create_time`,
`table_name`)
SELECT 
	new.`id`,
    /*登记时间*/ new.`trice`,
    /*备注*/ new.`description`,
    `project_id`,
    `organization_id`,
    `project_code`,
    `project_name`,
    `contract_amount`,
    /*change_amount*/ 0,
	change_total_amount,
    `settlement_amount`,
    `management_rate`,
    `management_plan_amount`,
    /*management_real_amount*/ 0,
    `management_total_amount`,
    `management_owe_amount`,
    /*party_billing_amount*/ 0,
    `party_billing_total_amount`,
    /* collections_amount */ 0,
    `collections_total_amount`,
    `collections_rate`,
    /*customer_billing_amount*/ 0,
    `customer_billing_total_amount`,
    /* payment_amount */ 0,
    `payment_total_amount`,
    `tax_rate`,
    `tax_plan_amount`,
    /* tax_real_amount */ 0,
    `tax_total_amount`,
    `tax_owe_amount`,
    /*arrears_amount，垫付资金，包含利息*/ new.amount + new.interest_amount + arrears_amount,
    /* expected_value */ 0,
    /* profile_point */ '',
    `version` + 1, 
/*create_time*/CURRENT_TIMESTAMP,
/*table_name*/ 't_arrears'
FROM `t_project_summary` where serial_id=(select max(serial_id) from t_project_summary where project_id=new.project_id and version >= 0); /*version =-1 作为删除标记*/
END;

CREATE DEFINER=`root`@`localhost` TRIGGER `hplydb`.`tr_collections` AFTER INSERT ON hplydb.t_collections FOR EACH ROW
BEGIN
INSERT INTO `t_project_summary`
(`id`,
`trice`,
`description`,
`project_id`,
`organization_id`,
`project_code`,
`project_name`,
`contract_amount`,
`change_amount`,
`change_total_amount`,
`settlement_amount`,
`management_rate`,
`management_plan_amount`,
`management_real_amount`,
`management_total_amount`,
`management_owe_amount`,
`party_billing_amount`,
`party_billing_total_amount`,
`collections_amount`,
`collections_total_amount`,
`collections_rate`,
`customer_billing_amount`,
`customer_billing_total_amount`,
`payment_amount`,
`payment_total_amount`,
`tax_rate`,
`tax_plan_amount`,
`tax_real_amount`,
`tax_total_amount`,
`tax_owe_amount`,
`arrears_amount`,
`expected_value`,
`profile_point`,
`version`,
`create_time`,
`table_name`)
SELECT 
	new.`id`,
    /*登记时间*/ new.`trice`,
    /*备注*/ new.`description`,
    `project_id`,
    `organization_id`,
    `project_code`,
    `project_name`,
    `contract_amount`,
    `change_amount`,
	`change_total_amount`,
    `settlement_amount`,
    `management_rate`,
    `management_plan_amount`,
    if(new.source_of = '管理费', new.amount, 0 ) as `management_real_amount`,
    if(new.source_of = '管理费', new.amount, 0 ) + `management_total_amount` as `management_total_amount`,
    if(new.source_of = '管理费', management_owe_amount - new.amount, management_owe_amount ) as `management_owe_amount`,
    `party_billing_amount`,
    `party_billing_total_amount`,
    new.amount,
    new.amount + collections_total_amount as `collections_total_amount`,
    (new.amount + collections_total_amount)/if(`settlement_amount` > 0, `settlement_amount`, `contract_amount` + change_total_amount ) `collections_rate`,
    `customer_billing_amount`,
    `customer_billing_total_amount`,
    `payment_amount`,
    `payment_total_amount`,
    `tax_rate`,
    `tax_plan_amount`,
    if(new.source_of = '税金', new.amount, 0 ) as `tax_real_amount`,
    if(new.source_of = '税金', new.amount, 0 ) + tax_total_amount as `tax_total_amount`,
    if(new.source_of = '税金', tax_owe_amount - new.amount, tax_owe_amount ) as `tax_owe_amount`,
    `arrears_amount`,
    `expected_value`,
    `profile_point`,
    `version` + 1, 
/*create_time*/CURRENT_TIMESTAMP,
/*table_name*/ 't_collections'
FROM `t_project_summary` where serial_id=(select max(serial_id) from t_project_summary where project_id=new.project_id and version >= 0); /*version =-1 作为删除标记*/
    
END;

CREATE DEFINER=`root`@`localhost` TRIGGER `hplydb`.`tr_contract_change` AFTER INSERT ON hplydb.t_contract_change FOR EACH ROW
BEGIN
INSERT INTO `t_project_summary`
(`id`,
`trice`,
`description`,
`project_id`,
`organization_id`,
`project_code`,
`project_name`,
`contract_amount`,
`change_amount`,
`change_total_amount`,
`settlement_amount`,
`management_rate`,
`management_plan_amount`,
`management_real_amount`,
`management_total_amount`,
`management_owe_amount`,
`party_billing_amount`,
`party_billing_total_amount`,
`collections_amount`,
`collections_total_amount`,
`collections_rate`,
`customer_billing_amount`,
`customer_billing_total_amount`,
`payment_amount`,
`payment_total_amount`,
`tax_rate`,
`tax_plan_amount`,
`tax_real_amount`,
`tax_total_amount`,
`tax_owe_amount`,
`arrears_amount`,
`expected_value`,
`profile_point`,
`version`,
`create_time`,
`table_name`)
SELECT 
	new.`id`,
    /*登记时间*/ new.`trice`,
    /*备注*/ new.`description`,
    `project_id`,
    `organization_id`,
    `project_code`,
    `project_name`,
    `contract_amount`,
    new.`change_amount`,
	/*累计增减金额*/ new.`change_amount` + `change_total_amount` as `change_total_amount`,
    `settlement_amount`,
    /*管理费率*/ new.`management_rate`,
    /*应收管理费*/ new.`management_rate` * if(`settlement_amount` > 0, `settlement_amount`, `contract_amount` +  new.`change_amount` + `change_total_amount`) as `management_plan_amount`,
    `management_real_amount`,
    `management_total_amount`,
    new.`management_rate` * if(`settlement_amount` > 0, `settlement_amount`, `contract_amount` +  new.`change_amount` + `change_total_amount`) - `management_total_amount` as `management_owe_amount`,
    /* party_billing_amount */ 0,
    `party_billing_total_amount`,
    /* collections_amount */ 0,
    `collections_total_amount`,
    `collections_rate`,
    /* customer_billing_amount */ 0,
    `customer_billing_total_amount`,
    /* payment_amount */ 0,
    `payment_total_amount`,
    `tax_rate`,
    `tax_plan_amount`,
    /* tax_real_amount */ 0,
    `tax_total_amount`,
    `tax_owe_amount`,
    `arrears_amount`,
    /* expected_value */ 0,
    /* profile_point */ '',
    `version` + 1, 
/*create_time*/CURRENT_TIMESTAMP,
/*table_name*/ 't_contract_change'
FROM `t_project_summary` where serial_id=(select max(serial_id) from t_project_summary where project_id=new.project_id and version >= 0); /*version =-1 作为删除标记*/
END;	

CREATE DEFINER=`root`@`localhost` TRIGGER `hplydb`.`tr_customer_billing` AFTER INSERT ON hplydb.t_customer_billing FOR EACH ROW
BEGIN
	
INSERT INTO `t_project_summary`
(`id`,
`trice`,
`description`,
`project_id`,
`organization_id`,
`project_code`,
`project_name`,
`contract_amount`,
`change_amount`,
`change_total_amount`,
`settlement_amount`,
`management_rate`,
`management_plan_amount`,
`management_real_amount`,
`management_total_amount`,
`management_owe_amount`,
`party_billing_amount`,
`party_billing_total_amount`,
`collections_amount`,
`collections_total_amount`,
`collections_rate`,
`customer_billing_amount`,
`customer_billing_total_amount`,
`payment_amount`,
`payment_total_amount`,
`tax_rate`,
`tax_plan_amount`,
`tax_real_amount`,
`tax_total_amount`,
`tax_owe_amount`,
`arrears_amount`,
`expected_value`,
`profile_point`,
`version`,
`create_time`,
`table_name`)
SELECT 
	new.`id`,
    /*登记时间*/ new.`trice`,
    /*备注*/ new.`description`,
    `project_id`,
    `organization_id`,
    `project_code`,
    `project_name`,
    `contract_amount`,
    /*change_amount*/ 0,
	change_total_amount,
    `settlement_amount`,
    `management_rate`,
    `management_plan_amount`,
    /*management_real_amount*/ 0,
    `management_total_amount`,
    `management_owe_amount`,
    /*party_billing_amount*/ 0,
    `party_billing_total_amount`,
    /* collections_amount */ 0,
    `collections_total_amount`,
    `collections_rate`,
    /*customer_billing_amount*/ new.amount,
    new.amount + `customer_billing_total_amount` as `customer_billing_total_amount`,
    /* payment_amount */ 0,
    `payment_total_amount`,
    `tax_rate`,
    `tax_plan_amount`,
    /* tax_real_amount */ 0,
    `tax_total_amount`,
    `tax_owe_amount`,
    /*arrears_amount*/ 0,
    /* expected_value */ 0,
    /* profile_point */ '',
    `version` + 1, 
/*create_time*/CURRENT_TIMESTAMP,
/*table_name*/ 't_customer_billing'
FROM `t_project_summary` where serial_id=(select max(serial_id) from t_project_summary where project_id=new.project_id and version >= 0); /*version =-1 作为删除标记*/
END;

CREATE DEFINER=`root`@`localhost` TRIGGER `hplydb`.`tr_party_billing` AFTER UPDATE ON hplydb.t_party_billing FOR EACH ROW
BEGIN
    if new.step_status = 1 and old.step_status != 1 then 
	
	/*流程审批通过时，触发*/
	
INSERT INTO `t_project_summary`
(`id`,
`trice`,
`description`,
`project_id`,
`organization_id`,
`project_code`,
`project_name`,
`contract_amount`,
`change_amount`,
`change_total_amount`,
`settlement_amount`,
`management_rate`,
`management_plan_amount`,
`management_real_amount`,
`management_total_amount`,
`management_owe_amount`,
`party_billing_amount`,
`party_billing_total_amount`,
`collections_amount`,
`collections_total_amount`,
`collections_rate`,
`customer_billing_amount`,
`customer_billing_total_amount`,
`payment_amount`,
`payment_total_amount`,
`tax_rate`,
`tax_plan_amount`,
`tax_real_amount`,
`tax_total_amount`,
`tax_owe_amount`,
`arrears_amount`,
`expected_value`,
`profile_point`,
`version`,
`create_time`,
`table_name`)
SELECT 
	new.`id`,
    /*登记时间*/ new.`trice`,
    /*备注*/ new.`description`,
    `project_id`,
    `organization_id`,
    `project_code`,
    `project_name`,
    `contract_amount`,
    /*change_amount*/ 0,
	change_total_amount,
    `settlement_amount`,
    `management_rate`,
    `management_plan_amount`,
    /*management_real_amount*/ 0,
    `management_total_amount`,
    `management_owe_amount`,
    new.amount party_billing_amount,
    new.amount + party_billing_total_amount as `party_billing_total_amount`,
    /* collections_amount */ 0,
    `collections_total_amount`,
    `collections_rate`,
    /* customer_billing_amount */ 0,
    `customer_billing_total_amount`,
    /* payment_amount */ 0,
    `payment_total_amount`,
    new.`tax_rate`,
    new.`tax_rate` * (new.amount + party_billing_total_amount) as `tax_plan_amount`,
    /* tax_real_amount */ 0,
    `tax_total_amount`,
    new.`tax_rate` * (new.amount + party_billing_total_amount) - tax_total_amount as `tax_owe_amount`,
    /*arrears_amount*/ 0,
    /* expected_value */ 0,
    /* profile_point */ '',
    `version` + 1, 
/*create_time*/CURRENT_TIMESTAMP,
/*table_name*/ 't_party_billing'
FROM `t_project_summary` where serial_id=(select max(serial_id) from t_project_summary where project_id=new.project_id and version >= 0); /*version =-1 作为删除标记*/

 end if;
END;

CREATE DEFINER=`root`@`localhost` TRIGGER `hplydb`.`tr_payment` AFTER INSERT ON hplydb.t_payment FOR EACH ROW
BEGIN
	
INSERT INTO `t_project_summary`
(`id`,
`trice`,
`description`,
`project_id`,
`organization_id`,
`project_code`,
`project_name`,
`contract_amount`,
`change_amount`,
`change_total_amount`,
`settlement_amount`,
`management_rate`,
`management_plan_amount`,
`management_real_amount`,
`management_total_amount`,
`management_owe_amount`,
`party_billing_amount`,
`party_billing_total_amount`,
`collections_amount`,
`collections_total_amount`,
`collections_rate`,
`customer_billing_amount`,
`customer_billing_total_amount`,
`payment_amount`,
`payment_total_amount`,
`tax_rate`,
`tax_plan_amount`,
`tax_real_amount`,
`tax_total_amount`,
`tax_owe_amount`,
`arrears_amount`,
`expected_value`,
`profile_point`,
`version`,
`create_time`,
`table_name`)
SELECT 
	new.`id`,
    /*登记时间*/ new.`trice`,
    /*备注*/ new.`description`,
    `project_id`,
    `organization_id`,
    `project_code`,
    `project_name`,
    `contract_amount`,
    /*change_amount*/ 0,
	change_total_amount,
    `settlement_amount`,
    `management_rate`,
    `management_plan_amount`,
    /*management_real_amount*/ 0,
    `management_total_amount`,
    `management_owe_amount`,
    /*party_billing_amount*/ 0,
    `party_billing_total_amount`,
    /* collections_amount */ 0,
    `collections_total_amount`,
    `collections_rate`,
    /*customer_billing_amount*/ 0,
    `customer_billing_total_amount`,
    /* payment_amount */ new.amount,
    new.amount + payment_total_amount as `payment_total_amount`,
    `tax_rate`,
    `tax_plan_amount`,
    /* tax_real_amount */ 0,
    `tax_total_amount`,
    `tax_owe_amount`,
    /*arrears_amount*/ 0,
    /* expected_value */ 0,
    /* profile_point */ '',
    `version` + 1, 
/*create_time*/CURRENT_TIMESTAMP,
/*table_name*/ 't_payment'
FROM `t_project_summary` where serial_id=(select max(serial_id) from t_project_summary where project_id=new.project_id and version >= 0); /*version =-1 作为删除标记*/
END;

CREATE DEFINER=`root`@`localhost` TRIGGER `hplydb`.`tr_profile` AFTER INSERT ON hplydb.t_profile FOR EACH ROW
BEGIN
	
INSERT INTO `t_project_summary`
(`id`,
`trice`,
`description`,
`project_id`,
`organization_id`,
`project_code`,
`project_name`,
`contract_amount`,
`change_amount`,
`change_total_amount`,
`settlement_amount`,
`management_rate`,
`management_plan_amount`,
`management_real_amount`,
`management_total_amount`,
`management_owe_amount`,
`party_billing_amount`,
`party_billing_total_amount`,
`collections_amount`,
`collections_total_amount`,
`collections_rate`,
`customer_billing_amount`,
`customer_billing_total_amount`,
`payment_amount`,
`payment_total_amount`,
`tax_rate`,
`tax_plan_amount`,
`tax_real_amount`,
`tax_total_amount`,
`tax_owe_amount`,
`arrears_amount`,
`expected_value`,
`profile_point`,
`version`,
`create_time`,
`table_name`)
SELECT 
	new.`id`,
    /*登记时间*/ new.`trice`,
    /*备注*/ new.`description`,
    `project_id`,
    `organization_id`,
    `project_code`,
    `project_name`,
    `contract_amount`,
    /*change_amount*/ 0,
	change_total_amount,
    `settlement_amount`,
    `management_rate`,
    `management_plan_amount`,
    /*management_real_amount*/ 0,
    `management_total_amount`,
    `management_owe_amount`,
    /*party_billing_amount*/ 0,
    `party_billing_total_amount`,
    /* collections_amount */ 0,
    `collections_total_amount`,
    `collections_rate`,
    /*customer_billing_amount*/ 0,
    `customer_billing_total_amount`,
    /* payment_amount */ 0,
    `payment_total_amount`,
    `tax_rate`,
    `tax_plan_amount`,
    /* tax_real_amount */ 0,
    `tax_total_amount`,
    `tax_owe_amount`,
    `arrears_amount`,
    /* expected_value */ new.expected_value,
    /* profile_point */ new.profile_point,
    `version` + 1, 
/*create_time*/CURRENT_TIMESTAMP,
/*table_name*/ 't_arrears'
FROM `t_project_summary` where serial_id=(select max(serial_id) from t_project_summary where project_id=new.project_id and version >= 0); /*version =-1 作为删除标记*/
END;

CREATE DEFINER=`root`@`localhost` TRIGGER `hplydb`.`tr_project` AFTER INSERT ON hplydb.t_project FOR EACH ROW
BEGIN
    INSERT INTO `t_project_summary`
(`id`,
`trice`,
`description`,
`project_id`,
`organization_id`,
`project_code`,
`project_name`,
`contract_amount`,
`change_amount`,
`change_total_amount`,
`settlement_amount`,
`management_rate`,
`management_plan_amount`,
`management_real_amount`,
`management_total_amount`,
`management_owe_amount`,
`party_billing_amount`,
`party_billing_total_amount`,
`collections_amount`,
`collections_total_amount`,
`collections_rate`,
`customer_billing_amount`,
`customer_billing_total_amount`,
`payment_amount`,
`payment_total_amount`,
`tax_rate`,
`tax_plan_amount`,
`tax_real_amount`,
`tax_total_amount`,
`tax_owe_amount`,
`arrears_amount`,
`expected_value`,
`profile_point`,
`version`,
`create_time`,
`table_name`)
VALUES
(/*id:*/ new.id, 
/*trice*/ new.trice, 
/*description*/ new.description, 
/*project_id*/ new.id, 
/*organization_id*/ new.organization_id, 
/*project_code*/ new.project_code, 
/*project_name*/ new.project_name, 
/*contract_amount*/ new.contract_amount, 
/*change_amount*/0.0000, 
/*change_total_amount*/ 0.0000,
/*settlement_amount*/ new.settlement_amount, 
/*management_rate*/ new.management_rate, 
/*management_plan_amount*/ new.management_plan_amount, 
/*management_real_amount*/0.0000, 
/*management_total_amount*/0.0000, 
/*management_owe_amount*/ new.management_plan_amount, 
/*party_billing_amount*/0.0000, 
/*party_billing_total_amount*/0.0000, 
/*collections_amount*/0.0000, 
/*collections_total_amount*/0.0000, 
/*collections_rate*/0.0000, 
/*customer_billing_amount*/0.0000, 
/*customer_billing_total_amount*/0.0000, 
/*payment_amount*/0.0000, 
/*payment_total_amount*/0.0000, 
/*tax_rate*/ new.tax_rate, 
/*tax_plan_amount*/ 0, 
/*tax_real_amount*/0.0000, 
/*tax_total_amount*/0.0000, 
/*tax_owe_amount*/ 0, 
/*arrears_amount*/0.0000, 
/*expected_value*/0.0000, 
/*profile_point*/ '', 
/*version*/0, 
/*create_time*/CURRENT_TIMESTAMP,
/*table_name*/'t_project');

END;