/**
  * @Template info: 2013/08/16, Chengqiyi.
  * ChengQiyi create in 2014-7-13 16:09:22
  * This class generated by CodeSmith Generator
  */

package hply.service;

import java.util.List;
import java.util.Map;
import javax.annotation.Resource;
import org.springframework.stereotype.Service;
import hply.persistence.ChopMapper;

import hply.domain.Chop;

@Service(value = "chopService")
public class ChopService {
    
    @Resource(name = "chopMapper")
    private ChopMapper chopMapper;

	  public void insert(Chop chop){
        chopMapper.insert(chop);
      }
	  
	  public void update(Chop chop){
        chopMapper.update(chop);
      
      }
	  
	  public void delete(String id){
        chopMapper.delete(id);
      }
	  
	  public Chop get(String id){
        return chopMapper.get(id);
      }
	  
	  public List<Chop> getAll(){
        return chopMapper.getAll();
      }
}


