/**
  * @Template info: 2013/08/16, Chengqiyi.
  * ChengQiyi create in 2014-7-13 16:09:22
  * This class generated by CodeSmith Generator
  */

package hply.service;

import java.util.List;
import java.util.Map;
import javax.annotation.Resource;
import org.springframework.stereotype.Service;
import hply.persistence.PaymentItemMapper;

import hply.domain.PaymentItem;

@Service(value = "paymentItemService")
public class PaymentItemService {
    
    @Resource(name = "paymentItemMapper")
    private PaymentItemMapper paymentItemMapper;

	  public void insert(PaymentItem paymentItem){
        paymentItemMapper.insert(paymentItem);
      }
	  
	  public void update(PaymentItem paymentItem){
        paymentItemMapper.update(paymentItem);
      
      }
	  
	  public void delete(String id){
        paymentItemMapper.delete(id);
      }
	  
	  public PaymentItem get(String id){
        return paymentItemMapper.get(id);
      }
	  
	  public List<PaymentItem> getAll(){
        return paymentItemMapper.getAll();
      }
}


