/**
  * @ cqiyi create in 2014-8-5 20:19:53 by Template
  * This class generated by Forever Web Rapid Framework Code Generator
  */
  
package hply.mapper.partial;

import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;
import hply.domain.SysParameter;



/**
  * 数据表： [t_sys_parameter]
  * 14_系统参数
  */
@Repository
public interface PartialSysParameterMapper {

	  public void insert(SysParameter sysParameter);
	  
	  public void update(SysParameter sysParameter);
	  
	  public void delete(String id);
	  
	  public SysParameter get(String id);
      
	  public int getVersion(String id);
	  
	  public List<SysParameter> getAll();
}

