/**
  * @ cqiyi create in 2014-8-5 20:19:53 by Template
  * This class generated by Forever Web Rapid Framework Code Generator
  */
  
package hply.mapper.partial;

import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;
import hply.domain.Payment;



/**
  * 数据表： [t_payment]
  * 06_付款情况
  */
@Repository
public interface PartialPaymentMapper {

	  public void insert(Payment payment);
	  
	  public void update(Payment payment);
	  
	  public void delete(String id);
	  
	  public Payment get(String id);
      
	  public int getVersion(String id);
	  
	  public List<Payment> getAll();
}

