/**
  * @Template info: 2013/08/16, Chengqiyi.
  * ChengQiyi create in 2014-7-13 15:01:55
  * This class generated by CodeSmith Generator
  */

package hply.persistence;

import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;
import hply.domain.PaymentItem;

@Repository(value = "paymentItemMapper")
public interface PaymentItemMapper {

	  public void insert(PaymentItem paymentItem);
	  
	  public void update(PaymentItem paymentItem);
	  
	  public void delete(String id);
	  
	  public PaymentItem get(String id);
	  
	  public List<PaymentItem> getAll();
}


