/**
  * @ cqiyi create in 2014/8/5 18:13:27 by Template
  * This class generated by Forever Web Rapid Framework Code Generator
  */
  
package org.hhwy.fweb1.mapper;

import org.hhwy.fweb1.mapper.partial.PartialFieldTypesMapper;
import org.springframework.stereotype.Repository;



/**
  * 数据表： [t_field_types]
  * 所有数据类型的测试样表
  */
@Repository
public interface FieldTypesMapper extends PartialFieldTypesMapper {

}

