/**
  * @ cqiyi create in 2014/7/18 15:46:24 by Template
  * This class generated by Forever Web Rapid Framework Code Generator
  */
  
package org.hhwy.fweb1.mapper;

import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;
import org.hhwy.fweb1.domain.FieldTypes;



/**
  * 数据表： [t_field_types]
  * 所有数据类型的测试样表
  */
@Repository
public interface FieldTypesMapper {

	  public void insert(FieldTypes fieldTypes);
	  
	  public void update(FieldTypes fieldTypes);
	  
	  public void delete(String id);
	  
	  public FieldTypes get(String id);
      
	  public int getVersion(String id);
	  
	  public List<FieldTypes> getAll();
}

