/**
  * @ cqiyi create in 2014/7/18 15:46:24 by Template
  * This class generated by Forever Web Rapid Framework Code Generator
  */
  
package org.hhwy.fweb1.mapper;

import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;
import org.hhwy.fweb1.domain.Payment;



/**
  * 数据表： [t_payment]
  * 06_付款情况
  */
@Repository
public interface PaymentMapper {

	  public void insert(Payment payment);
	  
	  public void update(Payment payment);
	  
	  public void delete(String id);
	  
	  public Payment get(String id);
      
	  public int getVersion(String id);
	  
	  public List<Payment> getAll();
}

