/**
 * @ cqiyi create in 2014/8/4 12:25:04 by Template
 * This class generated by Forever Web Rapid Framework Code Generator
 */

package org.hhwy.fweb1.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.hhwy.fweb1.domain.SysAuthorization;
import org.springframework.stereotype.Repository;

/**
 * 数据表： [t_sys_authorization] 授权关系
 */
@Repository
public interface SysAuthorizationMapper {

	public void insert(SysAuthorization sysAuthorization);

	public void update(SysAuthorization sysAuthorization);

	public void delete(String id);

	public SysAuthorization get(String id);

	public int getVersion(String id);

	public List<SysAuthorization> getAll();

	public List<SysAuthorization> getAuthorizationByUserId(String userId);

	public SysAuthorization getByUserIdAndResource(
			@Param("userId") String userId,
			@Param("resourceId") String resourceId);
}
