/**
 * @ cqiyi create in 2014/8/4 14:52:23 by Template
 * This class generated by Forever Web Rapid Framework Code Generator
 */

package org.hhwy.fweb1.mapper;

import java.util.List;

import org.hhwy.fweb1.domain.SysOrganization;
import org.springframework.stereotype.Repository;

/**
 * 数据表： [t_sys_organization] 组织机构
 */
@Repository
public interface SysOrganizationMapper {

	public void insert(SysOrganization sysOrganization);

	public void update(SysOrganization sysOrganization);

	public void delete(String id);

	public SysOrganization get(String id);

	public int getVersion(String id);

	public List<SysOrganization> getAll();
}
