/**
  * @ cqiyi create in 2014/8/4 11:31:08 by Template
  * This class generated by Forever Web Rapid Framework Code Generator
  */
  
package org.hhwy.fweb1.mapper;

import java.util.List;
import org.springframework.stereotype.Repository;
import org.hhwy.fweb1.domain.SysRoleResource;



/**
  * 数据表： [t_sys_role_resource]
  * 角色与资源的对应表
  */
@Repository
public interface SysRoleResourceMapper {

	  public void insert(SysRoleResource sysRoleResource);
	  
	  public void update(SysRoleResource sysRoleResource);
	  
	  public void delete(String id);
	  
	  public SysRoleResource get(String id);
      
	  public int getVersion(String id);
	  
	  public List<SysRoleResource> getAll();
}

