/**
  * @ cqiyi create in 2014/8/4 11:31:08 by Template
  * This class generated by Forever Web Rapid Framework Code Generator
  */
  
package org.hhwy.fweb1.mapper;

import java.util.List;
import org.springframework.stereotype.Repository;
import org.hhwy.fweb1.domain.SysRole;



/**
  * 数据表： [t_sys_role]
  * 系统角色表
  */
@Repository
public interface SysRoleMapper {

	  public void insert(SysRole sysRole);
	  
	  public void update(SysRole sysRole);
	  
	  public void delete(String id);
	  
	  public SysRole get(String id);
      
	  public int getVersion(String id);
	  
	  public List<SysRole> getAll();
}

