/**
 * @ cqiyi create in 2014/8/4 11:31:08 by Template
 * This class generated by Forever Web Rapid Framework Code Generator
 */

package org.hhwy.fweb1.mapper;

import java.util.List;
import org.springframework.stereotype.Repository;
import org.hhwy.fweb1.domain.SysUser;

/**
 * 数据表： [t_sys_user] 系统用户
 */
@Repository
public interface SysUserMapper {

	public void insert(SysUser sysUser);

	public void update(SysUser sysUser);

	public void delete(String id);

	public SysUser get(String id);

	public int getVersion(String id);

	public List<SysUser> getAll();

	public SysUser getByLoginName(String loginName);
}
