/**
  * @ cqiyi create in 2014-8-25 23:07:45 by Template
  * This class generated by Forever Web Rapid Framework Code Generator
  */
  
package hply.mapper.partial;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import hply.domain.SysUser;



/**
  * 数据表： [t_sys_user]
  * 11_系统用户
  */
@Repository
public interface PartialSysUserMapper {

	  public void insert(SysUser sysUser);
	  
	  public void update(SysUser sysUser);
	  
	  public void delete(String id);
	  
	  public SysUser get(String id);
      
	  public int getVersion(String id);
	  
	  public List<SysUser> getAll();
      
	  public int getRowCount();
	  
	  public List<SysUser> getAllPaged(@Param("pageIndex") int pageIndex, @Param("pageSize") int pageSize);
}

