/**
  * @ cqiyi create in 2014-8-25 23:07:45 by Template
  * This class generated by Forever Web Rapid Framework Code Generator
  */
  
package hply.mapper.partial;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import hply.domain.PartyBilling;



/**
  * 数据表： [t_party_billing]
  * 03_甲方开票情况
  */
@Repository
public interface PartialPartyBillingMapper {

	  public void insert(PartyBilling partyBilling);
	  
	  public void update(PartyBilling partyBilling);
	  
	  public void delete(String id);
	  
	  public PartyBilling get(String id);
      
	  public int getVersion(String id);
	  
	  public List<PartyBilling> getAll();
      
	  public int getRowCount();
	  
	  public List<PartyBilling> getAllPaged(@Param("pageIndex") int pageIndex, @Param("pageSize") int pageSize);
}

