/**
  * @Template info: 2013/08/16, Chengqiyi.
  * ChengQiyi create in 2014-7-13 16:09:22
  * This class generated by CodeSmith Generator
  */

package hply.service;

import java.util.List;
import java.util.Map;
import javax.annotation.Resource;
import org.springframework.stereotype.Service;
import hply.persistence.SysOrganizationMapper;

import hply.domain.SysOrganization;

@Service(value = "sysOrganizationService")
public class SysOrganizationService {
    
    @Resource(name = "sysOrganizationMapper")
    private SysOrganizationMapper sysOrganizationMapper;

	  public void insert(SysOrganization sysOrganization){
        sysOrganizationMapper.insert(sysOrganization);
      }
	  
	  public void update(SysOrganization sysOrganization){
        sysOrganizationMapper.update(sysOrganization);
      
      }
	  
	  public void delete(String id){
        sysOrganizationMapper.delete(id);
      }
	  
	  public SysOrganization get(String id){
        return sysOrganizationMapper.get(id);
      }
	  
	  public List<SysOrganization> getAll(){
        return sysOrganizationMapper.getAll();
      }
}


